### ISSUE TITLE
[General] 3-1：字串長度

### ISSUE THREAD

**Issue by ray079548** [coding-coworking-club/python-spring-2021#1]
## 提交連結

https://judge.ccclub.io/problem/180005

## 程式碼

```python
s = input("s=")
s_len = len(s)
n = int(input("n="))
print(s_len==n)
```
```python
s = input()
s_len = len(s)
n = int(input())
print(s_len==n)
```
## 問題描述

我寫了兩種寫法，第一種寫法在批改後，會被認定是wrong answer。第二種寫法批改後會是Accepted。
我認為兩種寫法是一樣的，用python跑出來的結果也相同；
但批改系統卻認定第一種寫法是wrong answer，第二種寫法批改後會是Accepted。
想請問這兩種寫法有甚麼差別呢?

**Comment by TJ72** [comment]
因為在 Judge系統中的 input是不接受預設字元/字串的，所以第一種寫法才會出現 Wrong Answer。
btw 下次GitHub Issue上的提交連結要貼提交程式碼之後的 ID 連結，在 Judge裡面的 Status中可以找到。
(i.e. https://judge.ccclub.io/status/447d91a56205760ece5390af1e59d216)

**Comment by ray079548** [comment]
好的，了解了。
謝謝你。
