### ISSUE TITLE
[General] 連續整數分堆

### ISSUE THREAD

**Issue by ghost** [coding-coworking-club/python-spring-2021#101]
## 提交連結

https://judge.ccclub.io/status/3ad17decba6d065e061afb3127b3648b
## 程式碼

```python
n=[int(i) for i in input().split(' ')]
lst=[]
for i in range(len(n)):
    
    try:
        if n[i]+1!=n[i+1]:
            
            l=n[:i+1]
            lst.append(l)
#             print(lst)
            
    except IndexError:
        lst.append(n[:i+1])
#         print(n[:i+1])
lst
l=[]
for i in range(len(lst)):
    if i==0:
        l.append(lst[0])
    else:
        l.append(lst[i][len(lst[i-1]):])
#print(l)
for i in l:
    for j in i:
        print(j,end=' ')
    print()

```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/52339710/110737727-debbee80-8268-11eb-8bde-2d391fd84027.png)

## 問題描述
Hint:sample 1 中，輸入為「1 2 3 5 6 7」，過程中你會得到 lst = [[1, 2, 3], [5, 6, 7]]
最後，將 lst 依照規則輸出，即得到答案。

幫我看倒數四行就好謝謝，因為我最後有做出上面的 lst = [[1, 2, 3], [5, 6, 7]]，但我真的不知道他想要什麼格式，在jupyter notebook上都一模一樣，然後WA。每一題debug的時間>>>>>>>寫扣的時間。

**Comment by TJ72** [comment]
按照題目的敘述，每行輸出分堆好的數字，然後數字間用空格作為間隔。以上面的 Sample舉例的話，就是輸出：
```
1 2 3
5 6 7
```
我看最後四行的 code，感覺你輸出到最後一個數字時還是有留一個空格(end = ' ')
另外，下次貼程式碼貼時，不要變動裡面預設的內容(像是 Python的那串字)喔～

**Comment by ghost** [comment]
> 按照題目的敘述，每行輸出分堆好的數字，然後數字間用空格作為間隔。以上面的 Sample舉例的話，就是輸出：
> 
> ```
> 1 2 3
> 5 6 7
> ```
> 
> 我看最後四行的 code，感覺你輸出到最後一個數字時還是有留一個空格(end = ' ')
> 另外，下次貼程式碼貼時，不要變動裡面預設的內容(像是 Python的那串字)喔～

好的感謝
