### ISSUE TITLE
[General] 打字機

### ISSUE THREAD

**Issue by konichihuahua** [coding-coworking-club/python-spring-2021#103]
## 提交連結

https://judge.ccclub.io/status/6d0d3d6ed2094d33afa13e6aee64493c

## 程式碼

```python

n=[ i for i in input()]
final=[]


for i in range(len(n)):
  if n[i]=="+":
    if i!=0:
      final.append(final[-1])
    
  elif n[i]=="-":
    if i!=0:
      final.pop()

  elif n[i]=="*":
    if i!=0:
      a=final[:]
      for j in a:
        final.append(j)
    
  else:
    final.append(n[i]) 
 
  


print("".join(final))



```

## 錯誤訊息

RUNTIME ERROR
## 問題描述

不知道...為什麼...錯....
有點...不明白...題敘...
很SAD.......

更
換了一個寫法
仍是疑惑

**Comment by TJ72** [comment]
因為在執行 "+"的時候你是拿上一個讀到 "非+-*的字元"加進 `final`，而題目的意思是"拿 final中最後一個字加進 final中"。所以如果是輸入"CCCA--+"的話，就沒辦法得到想要的結果

**Comment by konichihuahua** [comment]
可說是十分的不解

**Comment by konichihuahua** [comment]
我知道了~~~~~~~~~~~~~~~~~~~~~~~(裸奔

**Comment by konichihuahua** [comment]
i!=0 設的不對
應該是len(final)!=0

**Comment by TJ72** [comment]
> 可說是十分的不解

抱歉～沒追蹤到你已經更新解法了～
