### ISSUE TITLE
[Week 3] 比賽排名

### ISSUE THREAD

**Issue by jimmy97332** [coding-coworking-club/python-spring-2021#106]
## 程式碼

```python
a=input().split(" ")
c=[]
for j in a:    
  c.append(int(j))

ans=[]
while min(c)!= float('inf'):
  ans.append(c.index(min(c))) 
  c[ans[-1]]=float('inf')
for i in range(len(ans)):  
  if i != len(ans)-1:
    print(f'{ans[i]}',end=" ")
  else:
    print(ans[i],end=" ")    
```

## 問題描述

不好意思，剛剛例題有點趕我有些不懂的地方
1.while裡面ans.append(c.index(min(c))) 為何可以逐步把小的抓出來，不用先把原本c裡面最小的給remove掉嗎?
2.不太懂while當中最後一行的意思，c[ans[-1]]=float('inf')
3.最後印出時為何要拆成兩段，不能直接
    if i != len(ans):
       print(f'{ans[i]}',end=" ")
印出全部嗎?

**Comment by TJ72** [comment]
A1：凱文 demo時的作法是"每次迴圈中選到秒數最小的人`min(c)`，選到之後得到最小秒數的人的 index `c.index()`，將 index 加進 ans 的串列中，最後再把 c 串列中相對應的位置改成無限大" 所以最後全部排完之後，所有 c串列中的元素都會被轉換成無限大，就會跳出 while-loop了！當然用 remove也是好的方法，但用 remove要注意的是要想辦法保留原串列中各選手的 index。
A2： ans[-1] 是剛剛加進 ans串列中選到最小值的 index，所以 c[ans[-1]] = float('inf') 就是將 c 相對應位置的值改成無限大的意思。
A3：最後要分開來輸出，是因為題目要求整數間以空白間隔，但在結尾是不能有空白的，所以分成"最後一個"與"其他位置"分開來輸出。但我記得凱文最後應該有改成這樣：
```python
if i != len(ans)-1:
    print(f'{ans[i]} ',end="")
else:
    print(ans[i],end="")
```
空格擺在 f-string的最後面～

**Comment by jimmy97332** [comment]
原來如此!!謝謝助教
