### ISSUE TITLE
[Week 3] 小明採蘋果

### ISSUE THREAD

**Issue by nelly0421** [coding-coworking-club/python-spring-2021#107]
## 提交連結
https://judge.ccclub.io/status/645d923cb01477b72005299dcf99fda5

### 
```python
s=input()
s=s.split(',')
l=[int(num) for num in s]
maxans=0
max=l[0]+l[1]
for i in range(1,len(l)-1):
    total=l[i]+l[i-1]+l[i+1]
    if max>=total:
        max==max
        maxans==maxans
    else:
        max==total
        maxans==i
other=l[len(l)-1]+l[len(l)-2]
if max>=other:
    max==max
    maxans==maxans
else:
    max==other
    maxans=int(len(l)-1)
print(maxans)


## 問題描述

我是分成頭，中間，跟尾去比較。先把頭當成大值去慢慢比，檢查了很多次,還是找不到哪裡出了問題

**Comment by TJ72** [comment]
請先幫我補上提交連結並修正程式碼位置，細節請參考[GitHub 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)

**Comment by nelly0421** [comment]
> 請先幫我補上提交連結並修正程式碼位置，細節請參考[GitHub 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)

不好意思!已修正!

**Comment by TJ72** [comment]
變數的賦值是用一個等號喔～所以像是第 9 行的`max == max`應該是要寫成 `max = max`才行喔！另外你的出發點雖然很好，但還要考慮只有一棵樹的情況

**Comment by nelly0421** [comment]
> 變數的賦值是用一個等號喔～所以像是第 9 行的`max == max`應該是要寫成 `max = max`才行喔！另外你的出發點雖然很好，但還要考慮只有一棵樹的情況

好的!謝謝!
