### ISSUE TITLE
[General] 串列insert功能

### ISSUE THREAD

**Issue by CKJK47** [coding-coworking-club/python-spring-2021#108]
## 程式碼

```python
s1 = [9, 9, 9, 9]
s1.insert(-1, 6)
print(s1)
```

## 問題描述

這一段code的輸出為[9, 9, 9, 6, 9]
想請問insert功能是將元素插入至指定位置，為什麼這邊插入index為-1的地方會變成在倒數第二個呢？謝謝！

**Comment by TJ72** [comment]
`list.insert(i, x)`根據網路的[參考文件](https://stackoverflow.com/questions/53932704/array-insert-with-negative-index)是 inserts the element at the given index, shifting elements to the right.
如果是想要加元素到串列的最後一個位置的話，要用 ` list.insert(len(list), x)` 或 `list.append(x)`。不過建議還是用 .append()會比較好一點。
