### ISSUE TITLE
[Week 3] 串列切割

### ISSUE THREAD

**Issue by lova999** [coding-coworking-club/python-spring-2021#109]
## 程式碼

```python
input_lst = input().split(',')
print(input_lst)
```

## 問題描述

我想請教一下:
1. 為什麼這個print出來是['123'] 而不是 1,2,3
2. split 中的,代表什麼意思? 不是以逗號分割字串嗎? 
3. 如果沒有space就無法分割，那打","的目的是什麼?

還請不吝賜教，謝謝

**Comment by TJ72** [comment]
`s.split()`這個語法是將 s 這個字串，照著括號內的字元做切割，然後切割完後存在串列中。所以如果我們輸入'1,2,3'的話
```python
num = input()
input_lst = num.split(',')
print(input_lst)
```
這樣輸出 input_lst 就會得到 ['1', '2', '3']的串列喔

**Comment by lova999** [comment]
謝謝
