### ISSUE TITLE
[General] 串列複製疑問

### ISSUE THREAD

**Issue by chianshianli** [coding-coworking-club/python-spring-2021#110]
## 程式碼

```python
a = [1,2,3]
b = a
c = a[:]
a = [3,4,5]
print(a)
print(b)
print(c)
```

## 問題描述
課程上教學是說 ``` b = a ```，是將 b 指向 a，如果 a 更動了 b 也會更動，如果想要複製 a 的話寫法是 ``` c = a[:] ```，但我自己練習的時候 print 出來發現兩者都會變成原始的 a 不會隨之更動，想請問是甚麼緣故呢？

![image](https://user-images.githubusercontent.com/18030336/110912025-6af41180-834e-11eb-91e1-949b3a88963e.png)

**Comment by TJ72** [comment]
一開始 list a、b的確指向同一塊存著 [1, 2, 3]的記憶體，然後 list c指向不同塊 [1, 2, 3]。但當你重新指定 `a = [3, 4, 5]`時，Python是重新開一塊記憶體空間存[3, 4, 5]然後讓 list a指向他，所以如果我們用 `print(id(a), id(b), id(c))`看記憶體位置的話，就會發現 list a指向的記憶體位置換了。
而昨天介紹的不能複製串列是這樣的：
```python
alst = [1, 2, 3]
blst = alst
clst = alst[:]
alst[0] = 6
print(alst)
print(blst)
print(clst)
```
你會發現 blst[0]也跟著被改成 6了

**Comment by chianshianli** [comment]
原來如此，了解了! 謝謝 😄
