### ISSUE TITLE
[Week 3] 串列切割

### ISSUE THREAD

**Issue by david89820923** [coding-coworking-club/python-spring-2021#111]
## 程式碼

```python
a = input().split(",")
L = [float(i) for i in a]
result = "false"

for j in range(len(L)):
    if sum(L[:j]) == sum(L[j:]):
        result = "True"
print(result)
```

## 問題描述

參考實體班demo程式碼之後自己再重新寫了一遍
但是程式碼在if sum這行就會出現錯誤
顯示: 'int' object is not callable
後來直接把demo程式碼貼上jupyter跑也顯示一樣的狀況
想詢問是設定有誤還是我有漏了甚麼部分呢?

**Comment by Din0-3** [comment]
嗨嗨
你在練習的時候有把sum指定成某個變數嗎?

BTW你的False 沒有大寫哦
