### ISSUE TITLE
[General] 7-2：加減長方形

### ISSUE THREAD

**Issue by nelly0421** [coding-coworking-club/python-spring-2021#112]
## 提交連結
https://judge.ccclub.io/status/f10e07d516023ad79806548a4692a5e2

## 程式碼

```python
l=int(input())
w=int(input())
for i in range(w):
        for j in range(l):
            if (i+j)%2==0 :
                print('+',end="")
            else:
                print('-',end="")
        print()


```

## 問題描述
自己帶數跟題目上給的式子都是正確的，想請問是哪個部分出錯?

**Comment by sqark912** [comment]
4*4的時候會跟sample答案不一樣

你的code
第一列會是+-+-
可是第二列第一個符號， i=1 j=0 會print "-" 出來

題目我猜
應該是設定每一列的第一個符號
要跟前一列的符號不一樣
造成L是偶數的話，每一列長的都會一樣

**Comment by nelly0421** [comment]
> 4*4的時候會跟sample答案不一樣
> 
> 你的code
> 第一列會是+-+-
> 可是第二列第一個符號， i=1 j=0 會print "-" 出來
> 
> 題目我猜
> 應該是設定每一列的第一個符號
> 要跟前一列的符號不一樣
> 造成L是偶數的話，每一列長的都會一樣
原來是這樣!我懂了~謝謝

**Comment by nelly0421** [comment]
> 4*4的時候會跟sample答案不一樣
> 
> 你的code
> 第一列會是+-+-
> 可是第二列第一個符號， i=1 j=0 會print "-" 出來
> 
> 題目我猜
> 應該是設定每一列的第一個符號
> 要跟前一列的符號不一樣
> 造成L是偶數的話，每一列長的都會一樣

原來是這樣!我懂了~謝謝
