### ISSUE TITLE
[Week 3] 串列切割

### ISSUE THREAD

**Issue by j84022814** [coding-coworking-club/python-spring-2021#120]
## 提交連結

https://judge.ccclub.io/status/7653706d6d68d818687f19caaeb3e662
## 程式碼

```python
a = input().split(',')
list = [int(i) for i in a]
for c in range(len(list)):
    if sum(list[:c]) == sum(list[c:]):
        result = "True"
    else:
        result = "False"
print(result)
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/79981947/111032240-32cffa00-8446-11eb-9ae3-4536c13cb1df.png)

## 問題描述

算是參考DEMO的程式碼後寫出，但我發現在jupyter notebook可以 但在judge卻一直出現runtime error是為什麼呢?還有就是我截圖的那個部分，明明左右兩邊都可以切成17，為何跳出來的答案卻是false??感謝感謝

**Comment by TJ72** [comment]
題目敘述是給定數個以逗號分隔的"**浮點數**"～另外這樣寫的話會有一個 bug，就是雖然可能在迴圈中的某一次可以找到左右兩邊和相等的串列切割，但下一輪如果和不是相等的話，前一輪`result = "True"`的結果就被洗掉變成`result = False`囉

**Comment by TJ72** [comment]
BTW 建議不要使用 list 作為變數名稱～

**Comment by j84022814** [comment]
好的謝謝您
