### ISSUE TITLE
[Homework 1] 吉吉整理書

### ISSUE THREAD

**Issue by lova999** [coding-coworking-club/python-spring-2021#121]
## 程式碼

```python
number=input()
snumber=number.split(" ")
snumber=list(snumber)
lenth=len(snumber)
print(snumber)
print(lenth)

```

## 錯誤訊息
TypeError                                 Traceback (most recent call last)
<ipython-input-23-2a608accc39e> in <module>
      2 snumber=number.split(" ")
      3 snumber=list(snumber)
----> 4 lenth=len(snumber)
      5 print(snumber)
      6 print(lenth)

TypeError: 'int' object is not callable

## 問題描述
你好
我想請問一下
為何我在這裡不能取sumber的len
不論我有沒有轉成list都無法

**Comment by hchbiggrass** [comment]
以我自己的經驗，通常遇到XX object is not callable是因為上面的cell影響到這一個cell，因此只要restart kernal就可以解決了。

**Comment by lova999** [comment]
> 以我自己的經驗，通常遇到XX object is not callable是因為上面的cell影響到這一個cell，因此只要restart kernal就可以解決了。

可以了謝謝
