### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by dann1227** [coding-coworking-club/python-spring-2021#122]
## 提交連結

https://judge.ccclub.io/status/e1882ec0eaa6a4cb83c46435f5d7d837
## 程式碼

```python
a=int(input())
b=int(input())
lst=[a]
while (a//b != 0):
    c=a//b
    lst.append(c)
    a=c
print(sum(lst))
```

## 問題描述

我的想法是：
a為一開始的數量
b為兌換數量
一開始的串列中已有初始值
while迴圈的判斷是當a//b不等於0 #代表還可以兌換
執行迴圈內容
c為該次迴圈可以兌換的數量
將c加入串列中
再把c的值assing給a重新執行迴圈直到不能再兌換為止
最後print出串列裡的總和

目前看不出來問題會在哪裡，試了input data也都正常
是否需考慮input 2可能為1或0的情形呢？
若需考慮，output應該為無限大以及error嗎？
謝謝解答

**Comment by jeje898281** [comment]
(非助教，僅供參考)
從程式碼的理解和測試，我自己有找到的問題是，沒有考慮到當每一次兌換完後沒換出去的瓶數（意思就是a%b）

例如假設原本瓶數5（變數a），2（變數b）瓶可兌換。這組資料，理論上答案是9，但用你的程式碼會輸出8。

**Comment by dann1227** [comment]
> (非助教，僅供參考)
> 從程式碼的理解和測試，我自己有找到的問題是，沒有考慮到當每一次兌換完後沒換出去的瓶數（意思就是a%b）
> 
> 例如假設原本瓶數5（變數a），2（變數b）瓶可兌換。這組資料，理論上答案是9，但用你的程式碼會輸出8。

**Comment by dann1227** [comment]
> (非助教，僅供參考)
> 從程式碼的理解和測試，我自己有找到的問題是，沒有考慮到當每一次兌換完後沒換出去的瓶數（意思就是a%b）
> 
> 例如假設原本瓶數5（變數a），2（變數b）瓶可兌換。這組資料，理論上答案是9，但用你的程式碼會輸出8。

**Comment by dann1227** [comment]
@jeje898281 謝謝提醒，確實沒有考慮到這點，我再來修改程式碼試試看
