### ISSUE TITLE
[Homework 1] 吉吉印方型

### ISSUE THREAD

**Issue by alonso1331** [coding-coworking-club/python-spring-2021#123]
## 提交連結

https://judge.ccclub.io/status/ddf1d0cfe37c6cb85dfba476d9b5e4be

## 程式碼

side = int(input())
print(side * '*')
for i in range(side-2):
    print(('*' + ' ' *(side-2) + '*'))
print(side * '*')

```python

```

## 錯誤訊息

Wrong Answer

## 問題描述

我程式的表達是先輸入方型的邊side
然後頭、尾行輸出的程式是邊side乘以*
中間用for 變數 in range(side-2)，去除頭尾已經設定的樣式，表達中間要呈現的中空樣式
在jupyter測試是成功的，但上傳作業卻顯示是錯誤的。

**Comment by alonso1331** [comment]
奇怪，我上一留言第4行有打縮排，但是沒辦法呈現。

**Comment by hchbiggrass** [comment]
你要不要試試看從邊長為0測試到邊長為10的結果是否都符合預期?

**Comment by alonso1331** [comment]
測試過了，除了0、1沒辦法顯示出空心的方型，其他都可以。

**Comment by hchbiggrass** [comment]
依照題意，輸入0的話要輸出邊長為0的正方形，也就是沒有輸出；輸入1的話要輸出邊長為1的正方形，也就是1顆星；輸入2的話要輸出邊長為2的正方形，也就是4顆星。請再確認一次。

**Comment by alonso1331** [comment]
side = int(input())
for i in range(1):
    print(side * '*')
    for i in range(side-2):
        print('*' + (side-2) * ' ' + '*')

換個寫法，雖然輸入1可以出現1個星，但是沒辦法形成完整的空心方型，少了最下面一排星。

**Comment by alonso1331** [comment]
解決了。
