### ISSUE TITLE
[Week 3] 小明採蘋果

### ISSUE THREAD

**Issue by Hongzhang0404** [coding-coworking-club/python-spring-2021#125]
## 提交連結
https://judge.ccclub.io/status/18d5421218d0f1f99a4270e094a267b7

## 程式碼

```python
ls= [int(i) for i in input().split(',')]
sum= [s for s in range(len(ls))]
for j in range(len(ls)):
    if 0<j<len(ls)-1:
        sum[j]= ls[j-1]+ls[j]+ls[j+1]
    elif j==0:
        sum[j]= ls[j]+ls[j+1]
    elif j==len(ls)-1:
        sum[j]= ls[1]+ls[j]
print(sum.index(max(sum)))
```

## 錯誤訊息
Runtime Error

## 問題描述
用測資測試都正常，用Python Tutor也測過，請問可能是哪裡出了問題?

**Comment by TJ72** [comment]
在算最後兩棵樹上有的蘋果樹，index擺錯了。另外程式好像沒有考慮到只有一棵蘋果樹的情況～

btw下次貼程式碼時，不要變動預設的模板喔(e.g.貼程式碼地方的 Python字樣)

**Comment by Hongzhang0404** [comment]
感謝回答，再請問“只有一棵蘋果樹的情況“，測資要怎麼設定?

**Comment by TJ72** [comment]
只有一棵蘋果樹的測資就是只有一個正整數的情況 e.g. input = '5'

**Comment by Hongzhang0404** [comment]
謝謝解答，問題已解決。
