### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by GingerSmolNeko** [coding-coworking-club/python-spring-2021#127]
## 提交連結

https://judge.ccclub.io/status/213d91df371dd01fbdb4618887705f78

## 程式碼

```python
buy=int(input())
goal=int(input())

#goal=1的情況與沒買的情況
if buy == 0:
    print(0)
elif goal == 1:
    print('inf')
#無後續兌換的情況
elif buy//goal < 1:
    print(buy)
#有後續兌換的情況
else:
    rewards = buy//goal
    if rewards//goal == 1:
        rewards += 1
        print(buy+rewards)
    else:
        while rewards//goal > 1:
            rewards += rewards//goal
        if rewards//goal == 1:
            rewards += 1
            print(buy+rewards)
        else:
            last=int(rewards%goal)
            print(buy+rewards+last)

```

## 錯誤訊息

<img width="360" alt="截圖 2021-03-14 下午3 04 00" src="https://user-images.githubusercontent.com/79833970/111060265-8427ca00-84d6-11eb-805d-49ecb71aa9ac.png">

## 問題描述

請問「時間超過」通常問題是出在哪個面向？運算式過為複雜？解題邏輯多繞了幾圈？迴圈執行次數過多？
練習到現在出現過幾次這種狀況，還沒有掌握到解決的訣竅，懇請指點迷津～

（我以為現在寫出的判斷邏輯已經勉強算乾淨了，不過時間還是超過了...一時也想不到更簡化的敘述🤣）

**Comment by TJ72** [comment]
目前的階段出現 Time Limit Exceeded 通常是因為 while-loop出現無窮迴圈喔～通常判斷邏輯不會造成TLE

**Comment by chi811008** [comment]
[while 迴圈的用法可以參考medium文章](https://medium.com/ccclub/ccclub-python-for-beginners-tutorial-4990a5757aa6)
while-loop 適用在「無法預知迴圈數」的問題上。因為不知道"每次換回來的可樂"，還可以"再去換回多少瓶"，所以每次都要把多換回的空瓶+上原本剩下湊不齊的空瓶(可能是0個，也可能是1, 2, 3, ....小於規定的兌換瓶數)。
因為程式需要不斷地重覆"(換回的空瓶+上原本剩下湊不齊的空瓶) / 規定可兌換的數量"運算，一直到出現指定的特殊狀況（這裡就是上面雙引號的數值 < 1）時才停止，這種情形就比較適合用 while-loop 來實現。
while-loop 在執行其內部敘述之前，都會先檢查條件判斷式(while 後面的條件，也就是你的"rewards//goal > 1")，如果其判斷值為真 (True)，則執行迴圈內部的敘述；否則就結束 while-loop。
所以你可以檢查一下，你的條件判斷式會有成立的時候，那會有不成立的時候嗎？沒有不成立的時候，while loop 是不會停下來的

**Comment by GingerSmolNeko** [comment]
感謝提示，剛剛的確發現while-loop無限迴圈以及變數邏輯有誤的問題，現在修正如後，不過跑出來是wrong answer：

提交連結
https://judge.ccclub.io/status/969ebc537b020a879562f29708ae143d

```python

#小葉喝可樂 重寫
buy=int(input())
goal=int(input())

#goal=1的情況與沒買的情況
if buy == 0:
    print(0)
elif goal == 1:
    print('inf')
#無後續兌換的情況
elif buy//goal < 1:
    print(buy)
#有後續兌換的情況
else:
    rewards = buy//goal #每次的獎品數，初始為第一次購入
    rewards_sum = 0 #總獎品數
    if rewards//goal == 1:
        rewards += 1
        print(buy+rewards)
    else:      
        while rewards//goal > 1:
            rewards_sum += rewards//goal
            rewards = rewards//goal #problemetic?
        if rewards//goal == 1:
            rewards_sum += 1
            print(buy+rewards_sum)
        else:
            rewards_sum += rewards%goal
            print(buy+rewards_sum)
   ```

錯誤訊息：
<img width="358" alt="截圖 2021-03-14 下午5 48 08" src="https://user-images.githubusercontent.com/79833970/111064154-716cbf80-84ed-11eb-9067-d5a545e401ea.png">

這次我新增一個變數，將贈品總和與每次換到的新空瓶數量分開，修正原有程式碼計算下一次可兌換空瓶的邏輯錯誤和無限迴圈。
我目前還沒看出公式的問題，另外while-loop標註problemetic的地方我也懷疑設定可能有誤？
再請協助提示🥺非常感謝～

**Comment by chi811008** [comment]
> ```python
> while rewards//goal > 1:
> ```

你再確定一下這行條件判斷式的意思
這行的意思是，如果多換回來的空瓶，再拿去兌換的結果，如果大於1，就進入while迴圈
但是如果兌等於1呢？

**Comment by GingerSmolNeko** [comment]
> > ```python
> > while rewards//goal > 1:
> > ```
> 
> 你再確定一下這行條件判斷式的意思
> 這行的意思是，如果多換回來的空瓶，再拿去兌換的結果，如果大於1，就進入while迴圈
> 但是如果兌等於1呢？

我在試寫的時候，已先在前面的if-else中排除第一次兌換即rewards//goal == 1的狀況，另外我以為當while迴圈中新指定的rewards不再>1的時候，就會結束迴圈進到後面的if-else敘述，也就是剩下的rewards//goal == 1及剩餘不足兌換之狀況：

```python
        if rewards//goal == 1: #過濾第一次兌換即rewards//goal == 1的狀況，直接輸出
            rewards += 1
            print(buy+rewards)
        else:
            while rewards//goal > 1:
                rewards_sum += rewards//goal
                rewards = rewards//goal #當新指定的rewards除以goal不再>1，結束迴圈，執行if-else
            if rewards//goal == 1:
                rewards_sum += 1
                print(buy+rewards_sum)
            else:
                rewards_sum += rewards%goal
                print(buy+rewards_sum)
```

關於這幾點，不知我的觀念是否有錯？還是必須在rewards = rewards//goal後一行再加個break條件（if rewards//goal <= 1:）（不過我剛剛稍微試了一下好像還是WA）？
再煩助教和路過的同學們指點～

**Comment by cyhsieh264** [comment]
@GingerSmolNeko 不知道是不是沒有考慮到 `goal = 2` 的狀況？
例如 `buy = 5` 與 `goal = 2` 時，預期的輸出應該是 `9` ，但你目前的寫法好像會少算～

現在這個寫法用了很多的條件判斷，的確會讓程式變得比較複雜，不容易釐清思路。
其實可以嘗試把它統整然後簡單化，可能就不用寫那麼多層條件判斷：
比如說一開始的時候設定好執行 while 迴圈的條件，並且記得更新剩餘的可樂數量就可以了。
有空的話可以參考看看社團裡貼的 [作業一提示](https://www.notion.so/HW1-Hint-6613ab7ba9c243e6a6b2e65e0b0afc3e)

**Comment by GingerSmolNeko** [comment]
@cyhsieh264 謝謝！我後來有發現我最後幾行算式邏輯有少算的問題，最後乾脆整個重寫 🥺
先關閉這個討論，感謝過程伸出援手的所有人～
