### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by minornotes** [coding-coworking-club/python-spring-2021#128]
## 提交連結

https://judge.ccclub.io/status/89ab04b727756081e195e928e91b915a
## 程式碼

```python
buy = int(input()) #小葉初始購買可樂的數量
bottle = int(input()) #賣場規定需集滿的空瓶數量
total = buy + buy // bottle #小葉可以喝到的可樂總數
  
while (buy % bottle + buy // bottle) >= bottle: #小葉換剩下的可樂＋小葉這次換到的可樂
    total += (buy % bottle + buy // bottle) // bottle
    buy = buy // bottle
print(total)
```

## 錯誤訊息

wrong answer

## 問題描述

在jupyter notebook 試了多組數字都是對的，但在judge 提交時一直是 wrong answer，想請助教看看有可能是哪裡出錯了？

**Comment by TJ72** [comment]
這樣的算法每次的迴圈只有用到上一次換剩的空瓶，再上一次或更之前換剩的空瓶就沒有存到了
可以試一下這組測資：buy = 13, bottle = 2，輸出的 total = 25

**Comment by TJ72** [comment]
btw 下次發 GitHub Issue記得要注意貼程式碼的位置喔～細節可以參考[GitHub 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)
