### ISSUE TITLE
[Week 3] 串列切割

### ISSUE THREAD

**Issue by lova999** [coding-coworking-club/python-spring-2021#129]
## 程式碼

```python
input_lst = input().split(',')
print(input_lst)
lst = []
for num in input_lst:
    lst=lst.append(float(num))
# lst = [float(num) for num in input().split(',')]

flag = False
for index in range(len(lst)):
    if sum(lst[:index]) == sum(lst[index:]):
        flag = True

print(flag)
```

## 錯誤訊息
AttributeError                            Traceback (most recent call last)
<ipython-input-15-abecaa3f18f9> in <module>
      3 lst = []
      4 for num in input_lst:
----> 5     lst=lst.append(float(num))
      6 # lst = [float(num) for num in input().split(',')]
      7 

AttributeError: 'NoneType' object has no attribute 'append'

## 問題描述
我想請教一下
為何在第5行的地方不能用lst=lst.append(float(num))
而用lst.append(float(num)) 就可以
我不能重新定義lst嗎~
還是說插入之後就代表重新定義了

感謝指教

**Comment by TJ72** [comment]
使用 `lst.append(element)`不用再重新指定回 lst 喔～
正確的用法應該是下面這樣就可以囉：
```python
lst = []
for num in input_lst:
    lst.append(float(num))
```
