### ISSUE TITLE
[Week 2] 停車費

### ISSUE THREAD

**Issue by jennabanana** [coding-coworking-club/python-spring-2021#13]
## 提交連結

https://judge.ccclub.io/status/856404ce8e8fd2e46912a9caa56f9b64

## 程式碼

```python
a=input()
b=input()
c=input()
d=(int(b[0:2])*60+int(b[3:]))-(int(a[0:2])*60+int(a[3:]))
e=(int(d/30)+1)*20
if d>0:
    if c=="Y":
        if c=="Y"and d<30: 
            print("0")
        else:
            print(int(e/2))
    else:
        print(int(e))
else:
    print("0")
```

## 錯誤訊息

![截圖 2021-03-04 下午11 47 01](https://user-images.githubusercontent.com/80043361/109990639-8bb3da00-7d44-11eb-9a7b-f0c94bf4b362.png)

## 問題描述

1.請問要怎麼把“離開時間不能超過23:59"這個條件表現出來呢，用if嗎？
2. 除了上題，程式其他部分寫的是對的嗎？謝謝～

**Comment by TJ72** [comment]
A1：在這題不用特別把“離開時間不能超過23:59"這個條件表現出來喔！因為測資不會有過夜的情形。
A2：我發現在算停車費(e)的時候，如果停車時間剛好是 30 or 30的倍數，就會被你強迫 +1囉！
