### ISSUE TITLE
[Week 3] 比賽排名

### ISSUE THREAD

**Issue by catherine1010** [coding-coworking-club/python-spring-2021#131]
## 程式碼

```python
input_lst = input().split()
lst = []
for num in input_lst:
    lst.append(int(num))

ans = []
while min(lst) != float("inf"):
    ans.append(lst.index(min(lst)))
    lst[ans[-1]] = float("inf")

for i in range(len(ans)):
    print(ans[i], end=" ")
```

## 問題描述

想問一下助教在課堂上demo時的範例如下:
input_lst = input().split()
lst = []
for num in input_lst:
    lst.append(int(num))

ans = []
while min(lst) != float('inf'):
    ans.append(lst.index(min(lst)))
    lst[ans[-1]] = float('inf')

for i in range(len(ans)):
    if i != len(ans) - 1:
        print(f'{ans[i]} ', end='')
    else:
        print(ans[i], end='')
其中出現了f'{ans[i]}這個東西，我嘗試著把這個東西拿掉後還是能得到Accepted，
所以想請問f'{ }的功用是什麼?該如何正確使用?謝謝

**Comment by hchbiggrass** [comment]
這個稱為f-string，用來工整地輸入字串，詳細用法可以去google看看例子。
