### ISSUE TITLE
[Homework 1] 吉吉把數字歸零

### ISSUE THREAD

**Issue by yutingchen526** [coding-coworking-club/python-spring-2021#132]
## 提交連結

http://localhost:8888/notebooks/吉吉把數字歸零.ipynb

## 程式碼

num = int(input())
times = 0

while num -1 != 0:
    if num % 2 != 0:
        num = (num - 1) / 2
        times += 2
    if num % 2 == 0:
        num = num / 2
        times += 1
    if num - 1 == 0:
        times += 1

print(times)

## 問題描述

在Jupyter上跑出來的output是正確的，但繳交至批改系統則出現WA，找不到錯誤的地方在哪...
作題想法是當num-1不是0的時候迴圈繼續跑，再來看數字能不能被2整除，分別執行對應狀況的指令。
調整了好多寫法都是WA，請各位大神協助看看到底錯在哪...感激！！！

**Comment by TJ72** [comment]
如果 num = 1的話，就不會跑進 while-loop裡了。

**Comment by TJ72** [comment]
下次發 GitHub Issue請注意格式，細節請參考[GitHub 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)

**Comment by yutingchen526** [comment]
非常抱歉！下次會依照規定格式發問！
將 num-1 == 0 的調整至第一順位，並且在while迴圈之外再新增一個 if num == 1 的條件，就答對了！！
感謝助教，一語點醒夢中人><
