### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by zoee22** [coding-coworking-club/python-spring-2021#133]
## 提交連結

https://judge.ccclub.io/status/c97bde684483e6b92a01dadfc50f118f
## 程式碼

```python
origin=int(input())
rule=int(input())
if origin<rule:
    print(origin)
for i in range(origin):
    exchange1=origin//rule
    leave=origin-exchange1*rule
    exchange2=(exchange1+leave)//rule 
    total=origin+exchange1+exchange2
print(total)
```

## 錯誤訊息

![123](https://user-images.githubusercontent.com/80198686/111073932-c1fb1180-851b-11eb-9ecf-17fd61f49c70.png)

## 問題描述

在jupyter上測試都可以，但是繳交judge卻是WA，不太清楚自己的盲點，希望助教指點!謝謝!

**Comment by TJ72** [comment]
我有一點不太懂你程式碼的邏輯耶～建議可以在紙上算算看幾個實際的例子，觀察一下那些例子的規律。然後一個小提示：這題用 while-loop比較好寫喔～

**Comment by zoee22** [comment]
好的我用while先試試看 謝謝!
