### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by yutingchen526** [coding-coworking-club/python-spring-2021#135]
## 提交連結

http://localhost:8888/notebooks/小葉喝可樂.ipynb

## 程式碼

```python
buy = int(input()) #初始買入瓶數
qty = int(input()) #規定需集滿空瓶數
exchange = buy // qty #每輪兌換的瓶數
last = buy % qty #一開始剩餘的空瓶
total_exchange = 0 #總共兌換的瓶數

if buy < qty:
    total_exchange = 0 #如果初始購買的數量就不足夠兌換的話，總兌換瓶數即為0

else:
    while exchange + last >= qty: #當兌換的瓶數+剩餘的空瓶>規定的數量時，即迴圈成立
        exchange = (exchange + last) // qty #新兌換的瓶數=上次兌換到的瓶數加上次剩餘的空瓶//規定的數量
        last = (exchange + last) % qty + exchange #新剩餘數量=上次剩餘的空瓶+後來新兌換的數量
        total_exchange += exchange

print(buy + total_exchange)
```

## 問題描述

作題邏輯如程式碼的註記，使用sample input結果得到了不對的答案，不太確定是不是遺漏了什麼，測出來的結果都會比正確答案少...

**Comment by TJ72** [comment]
你算 while-loop 裡面的`last`用的`exchange`已經被上個算式的`exchange`的值替換了，不會是你期待上一輪 while-loop換得的可樂

**Comment by yutingchen526** [comment]
謝謝助教提點，但還是想不出來該怎麼解決，想說直接把remain拿掉看能不能排除問題，結果還是失敗...
while exchange + (exchange % rule) >= rule:
        exchange = (exchange + (exchange % rule)) // rule
        total += exchange

**Comment by TJ72** [comment]
可能可以交換一下`exchange`和`last`運算的順序，或是可以創一個中間的變數去存原本的數值，兩個方法應該都可以解決這個問題喔

**Comment by yutingchen526** [comment]
http://localhost:8888/notebooks/Untitled7.ipynb?kernel_name=python3
