### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by maamli** [coding-coworking-club/python-spring-2021#136]
## 提交連結
https://judge.ccclub.io/status/d7e9f142bbe91390b65095397678db6a

## 程式碼

```python
buy=int(input())   #buy:購買的數量
rule=int(input())   #rule:賣場規定集滿的空瓶數量
exchange=buy//rule     #exchange:多換回的可樂
exchange1=exchange    #exchange1:第一次換回的瓶數
last=buy%rule              #last: 剩下的空瓶
total=0
if buy<rule:     #如果購買量小於規定，顯示買量
    print(buy) 
while buy>=rule:         #如果購買量大於規定
    if (exchange+last)>=rule: 
        exchange=(last+exchange)//rule   #(多換回的+空瓶)可以再換回幾瓶
        last=(last+exchange1)%rule           #(多換回的+空瓶)再次兌換後，不足規定的空瓶(餘數)
        total+=exchange         #總共換回多少瓶
    if (exchange+last)<rule:   #如果(換回的+空瓶)小於規定，break
        break  
print(total+buy+exchange1) #喝的總數=買量+第一次兌換的瓶數+之後兌換的瓶數`
```

## 問題描述

在jupyter 上測試答案是對的，不過Judge上改了幾次都是wrong answer，使用Trace code順了思路還是找不到癥結點，相當苦惱，再麻煩指點方向，謝謝

**Comment by lazyYC** [comment]
@maamli
你好，我發現當你的buy < rule的時候，一開始會先執行：```print(buy)```
最後又會執行：```print(total+buy+exchange1)```
因此，在此情況下會有兩次output，造成wrong answer。
建議可以在  ```print(buy)```後面、```while```前面加上```else```這樣就不會print兩次了。

**Comment by maamli** [comment]
@lazyYC 
謝謝你的解答!如同建議在print(buy)後加上else，放入Trace code檢查不會再有print 2次結果的情況，出來1個結果後就Done running；再驗證buy>rule的情況同樣沒問題後再次提交，不過依然WA??苦惱
連結:
https://judge.ccclub.io/status/75b7df6435fe91556559af0174c4feab

**Comment by cyhsieh264** [comment]
@maamli 如果是 `rule = 2` 這樣的情況呢？

試試看 `buy = 7` 與 `rule = 2` ，預期的輸出應該是 `13` ，但你的程式碼會輸出 `14`。

再看看 `buy = 5` 與 `rule = 2` ，預期的輸出應該是 `9` ，但你程式當中的迴圈會一直跑下去。

建議可以再重新梳理一下程式的邏輯～
