### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by vickilovehippo** [coding-coworking-club/python-spring-2021#139]
## 提交連結
https://judge.ccclub.io/status/752f00398b46fca9e9b67726d029f59c

## 程式碼

```python
colabuy=int(input()) 
rule=int(input())  
freecola= colabuy//rule 
totalcola= colabuy+ freecola 
left = colabuy%rule 

if colabuy < rule:
    print(totalcola)
else:
    while freecola+ left >= rule:
        freecola = (freecola + left)// rule
        left = freecola % rule
        totalcola += freecola
    print(totalcola)


```

## 錯誤訊息

time limit exceed

## 問題描述

第一次兌換可樂數量等於 買入數量//規定兌換瓶數
其餘可以免費兌換的數量等於 [免費兌換數量+餘數(沒有兌換的數量)]/規定兌換瓶數
輸入兩個input皆等於output 但顯示 time limit exceed
我想不出更精簡的程式了 還請指點 謝謝!

**Comment by hchbiggrass** [comment]
其實你寫得很精簡了，問題是出在程式的邏輯有點錯誤。最後的輸出在某些情況正確不一定表示所有過程都正確。建議可以用[Trace code](http://pythontutor.com/visualize.html#mode=edit)檢查每一步是否都符合你的預期。

**Comment by cyhsieh264** [comment]
@vickilovehippo 可以參考一下 #38 這篇提問，看起來是沒有考慮到 `rule = 2` 的情況，導致迴圈一直跑下去。
