### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by zoee22** [coding-coworking-club/python-spring-2021#142]
## 提交連結

https://judge.ccclub.io/status/508145baf397bb39caa5244cd94067d6
## 程式碼

```python
buy=int(input())
rule=int(input())
if buy<rule:
    print(buy)
while buy>=rule:
    total_1=buy//rule
    buy-=total_1*rule
    total_2=(total_1+buy%rule)//rule
print(buy+total_1*rule+total_1+total_2)
```

## 錯誤訊息

![123](https://user-images.githubusercontent.com/80198686/111110620-d1b83b80-8597-11eb-9fdb-d38c23a1e40f.png)

## 問題描述

在jupyter測試是正確的，也試過單項分開輸出(buy,total_1,total_2)，結果也沒錯，但judge顯示wrong answer，想請問有什麼沒有注意到的細節嗎?謝謝!
我的想法是:先兌換第一次(數量為total_1)，為了不出現無窮迴圈，我把buy=buy%rule，第二次兌換數量為(第一次+餘數)//rule

**Comment by hchbiggrass** [comment]
雖然你用的是while，但只要換2次就不會繼續換了

**Comment by zoee22** [comment]
我把break加上去但還是WA，想請問我把while後面的條件設buy>=rule，loop跑到後面若不符合條件，不是會自己停掉嗎?還是我搞錯了QQ謝謝!
(會用while是因為另一則提問的回覆說這題用while會比較好解)

**Comment by hchbiggrass** [comment]
while不符合條件就會停止，在符合條件時會一直跑下去。但是你的程式碼最開始的問題是"太快停止"，可能其實要換4次才換到底，但你只換2次就停了。

**Comment by TJ72** [comment]
可以參考一下助教們在 FB 社團 po 的 Hint 喔～看完之後如果還有問題歡迎再回 GitHub 一起討論～
