### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by john7777215** [coding-coworking-club/python-spring-2021#143]
## 程式碼

n = int(input())
m = int(input())
b=n%m
total = int(n)

while n//=m > 1 :
    n//=m
    total+=n
    n+=b
print(total)

## 錯誤訊息

time limit exceed

## 問題描述

n為購買數量
m為幾瓶空瓶可以換一瓶可樂
b為換完可樂後剩下的空瓶
total為初始的購買數量(N)
邏輯是先看可以換幾瓶可樂(n//=m)
加上原本的可樂數量(total+=n)
再看尚未換完的空瓶加上新換的可樂(n+=b)
到這邊跑完一次迴圈
n已經變成**尚未換完的空瓶加上新換的可樂**
再看n是否大於m
大於等於則再跑一次
若小於則代表沒辦法換了
print(total) 

嘗試不同變數都是正確
但還是一直出現time limit exceed
麻煩助教解答~謝謝~

**Comment by TJ72** [comment]
請修正程式碼與提交連結，細節請參考[GitHub 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)
