### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by yiyilin250** [coding-coworking-club/python-spring-2021#144]
## 提交連結
https://judge.ccclub.io/status/766df68bac85d343d8325ea59ac986e5

## 程式碼
a = int(input())
b = int(input())

reward = int(a / b)
reward2 = int(reward / b)

total = a + reward + reward2

print(total)

```python

```

## 問題描述

在jupter跑是正常的，但放到judge一直給我wrong answer。我看其他同學好像都用if和while解題。懷疑是不是自己解題方向錯誤。

**Comment by TJ72** [comment]
在可樂兌換的情境中，因為我們沒辦法確定是不在兌換兩輪後就沒辦法繼續兌換了，所以我們需要用迴圈幫我們重複執行一樣的兌換程序；然而又因為我們沒辦法確定兌換的次數，只能知道如果"空瓶的數目 < 兌換一瓶可樂需要的空瓶數"的話，就結束小葉的兌換程序，所以用 while-loop 會容易一些喔～
