### ISSUE TITLE
[Week 3 ] 小明採蘋果

### ISSUE THREAD

**Issue by Isa-ko** [coding-coworking-club/python-spring-2021#145]
## 提交連結
https://judge.ccclub.io/status/52db5ce40d887fb686f5067ea12f0e85

## 程式碼

```python
n= input().split(",")
n_list=[int(i) for i in n]


apple_num= []
for i in range(len(n_list)):
    if i== 0 :
        a= n_list[i]+ n_list[i+1]
        apple_num.append(a)
        
    elif i== len(n_list)-1:
        c=n_list[i]+ n_list[i-1]
        apple_num.append(c)
    elif i> 0:
        b= n_list[i-1]+ n_list[i]+ n_list[i+1]
        apple_num.append(b) 

print(apple_num.index(max(apple_num)))

```

## 錯誤訊息
![image](https://user-images.githubusercontent.com/69064353/111156904-38a61680-85d1-11eb-8372-a2a29a4b5257.png)

## 問題描述
在jupyter notebook上跑都OK,可是放到系統裡就show runtime error,
如果程式打錯不是應該jupyter notebook也跑不出來嗎? 謝謝指教

**Comment by chianshianli** [comment]
(非助教，僅供參考)
我在想可能是只有部分測資會跑不出來?

另外你 '''elif i > 0''' 那邊會把 '''elif == len(n_list) - 1'''狀況重算一遍喔! 不過就算改了這個也是 runtime error，不知道哪裡沒考慮到抱歉幫不上忙@@祝你早日ＡＣ囉！

**Comment by TJ72** [comment]
因為沒有考慮到 "只有一顆蘋果樹" 的情況喔～

**Comment by Isa-ko** [comment]
> (非助教，僅供參考)
> 我在想可能是只有部分測資會跑不出來?
> 
> 另外你 '''elif i > 0''' 那邊會把 '''elif == len(n_list) - 1'''狀況重算一遍喔! 不過就算改了這個也是 runtime error，不知道哪裡沒考慮到抱歉幫不上忙@@祝你早日ＡＣ囉！
>> 謝謝回覆~~~

**Comment by Isa-ko** [comment]
> 因為沒有考慮到 "只有一顆蘋果樹" 的情況喔～

>> 沒錯!謝謝回覆!成功AC了~~開心
