### ISSUE TITLE
[Week 3] 小明採蘋果

### ISSUE THREAD

**Issue by j84022814** [coding-coworking-club/python-spring-2021#146]
## 提交連結

https://judge.ccclub.io/status/d051507b6c629fd18aab06fe416350f0
## 程式碼

```python
s=[int(i) for i in input().split(',')]
newlist=[]
for n in range(len(s)):
    if n==0:
        newlist.append(s[0]+s[1])
    if n==(len(s)-1) and (len(s)-1)!=0:
        newlist.append(s[n-1]+s[n])
    else:
        newlist.append(s[n]+s[n-1]+s[n+1])
newlist.remove(newlist[1])
a=newlist.index(max(newlist))
print(a)
```

## 問題描述

首先想先請問，第一個newlist的部分，不知道為何newlist[1]都還是會跑出一個s[n]+s[n-1]+s[n+1]的數字，也就是s[0]+s[-1]+s[2]，但我明明已經用else，不是理論上不會用到n==0的這個條件了嗎? (所以我才把newlist的[1]remove掉)，再來就是我這樣寫，我發現jupyter notebook的答案都是對的也可以跑(包括若採收複數個位置收穫相同數量的蘋果，取編號較小者)，但不知道為何judge都會顯示runtime error??

**Comment by TJ72** [comment]
問題同 #145 ～

**Comment by j84022814** [comment]
那我想請教為何我還需要remove newlist[1]
我原本那樣寫錯在哪裡呢???

**Comment by TJ72** [comment]
抱歉～剛看太快了沒看到第一個問題。
是因為 for-loop 裡面的兩個 if 是平行的，當 n = 0 時，第一個 if 會成立，雖然在第二個 if 不會成立，但是會跑進 else 裡面喔！所以當 s = [4, 5, 6, 7, 8] 時，newlist 會在第一個 if 加入 9，然後會在第二個 if/else 裡加入 17 (s[0] + s[1] + s[-1])。所以你才會要在上面的 code 加入`newlist.remove(newlist[1])`

**Comment by j84022814** [comment]
感謝您！那我懂了，但如果是這樣，我該怎麼避免？

**Comment by TJ72** [comment]
我覺得應該就是在寫 if/elif/else 的時候，要特別注意條件的分割：什麼情況下你想執行什麼運算。然後慢慢練習、跟別人討論或看別人的 code 就會避免啦
