### ISSUE TITLE
[Week 3] 比賽排名

### ISSUE THREAD

**Issue by j84022814** [coding-coworking-club/python-spring-2021#147]
## 提交連結

https://judge.ccclub.io/status/98ed6417bd8a19979eac548e26f616ce
## 程式碼

```python
input_lst = input().split()
lst = []
for num in input_lst:
    lst.append(int(num))

ans = []
while min(lst) != float('inf'):
    ans.append(lst.index(min(lst)))
    lst[ans[-1]] = float('inf')

for i in range(len(ans)):
    if i != len(ans) - 1:
        print(f'{ans[i]} ', end='')
    else:
        print(ans[i], end='')
```

## 問題描述

我參考了demo程式碼，我想請問f'{}'是不是還沒教到，我後來去查了一下好像是字典的用法，只是我不太懂，為何不能直接print(ans[i], end='')，還需要納入if i != len(ans) - 1這個考量

**Comment by TJ72** [comment]
A1：關於 f-string 的用法，請參考 3/11 課程投影片的第18頁。
A2：需要納入`if i != len(ans) - 1:`與`else:`分開輸出是因為輸出的 index 間要以空格為間隔，而最後一個後面是不能有空格的，所以才分開輸出。

**Comment by j84022814** [comment]
喔喔我懂了 感謝您
