### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by stan4569807** [coding-coworking-club/python-spring-2021#15]
## 提交連結

https://judge.ccclub.io/status/6cc647dc47dcae32db6ff5c66068bd9a

## 程式碼

```python
a=int(input())
b=int(input())
print(int(a+a//b+a//b**2))
```

## 問題描述

我已兩個例子發現最後的可以喝到的可樂數應該是：
一開始購買的可樂數(a)＋
一開始購買的可樂數(a)除以賣場規定需集滿的空瓶數量(b)取整數＋
一開始購買的可樂數(a)除以賣場規定需集滿的空瓶數量平方(b**2)取整數
在jupyter note試驗兩個例子都對但放到批改系統就有錯誤，求解決方法，謝謝！

<img width="226" alt="截圖 2021-03-05 10 41 04" src="https://user-images.githubusercontent.com/37691539/110059642-951e6000-7d9f-11eb-9c71-25dd541473f0.png">
<img width="188" alt="截圖 2021-03-05 10 41 17" src="https://user-images.githubusercontent.com/37691539/110059647-964f8d00-7d9f-11eb-8a5a-e29381c583c1.png">

**Comment by alvisyjchen** [comment]
嗨同學，請先參照 Notion 中的學員須知 / GitHub Issue 使用教學，提交正確的連結，這樣助教才能確認問題哦

**Comment by stan4569807** [comment]
@alvisyjchen 您好，已更新，再麻煩您解答

**Comment by cyhsieh264** [comment]
兩個範例的情境都是，在第一次換完免費可樂以後，喝完的免費空瓶剛好還可以再換一瓶，然後就不能再換了。只觀察這兩個範例的話，可能會有其他情境沒有考慮到，例如：一開始買了 10 瓶可樂，每 2 個空瓶就可以再換 1 瓶可樂。

可以再想想是否有其他解法，並自行給定不同的情境進行測試～
