### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by yozzzzzz** [coding-coworking-club/python-spring-2021#150]
## 程式碼

```python
buy = int(input())
rule = int(input())
num = buy
res = 0
while (buy + res) >= rule:
    num += ((buy + res)// rule)
    buy //= rule
    res += (buy % rule)
else: 
    print(num)
```

## 錯誤訊息

Time Limit Exceeded
## 問題描述

程式的邏輯是 buy 是一開始買的數量 之後會被送的數量覆蓋掉
res 則是每次兌換剩下的餘數
只要buy加res大於兌換的門檻rule 迴圈就會一直跑下去
最後才會將答案print 出來
雖然在 jupyter notebook 都可以順利跑出來
但放到批改系統會顯示 time limit exceeded
想請問程式的哪裡出了問題？

**Comment by TJ72** [comment]
因為程式碼中`res`變數的運算那邊好像沒有寫好，很有可能累積的餘數可以超過兌換的門檻導致 TLE ，像是 buy = 26, rule = 3 這組測資。可以參考一下助教們 po 在 FB 社團裡面的 Hint喔～
