### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by taiwansui** [coding-coworking-club/python-spring-2021#153]
## 提交連結
https://judge.ccclub.io/contest/25/problem/0101

## 程式碼

```python
x = int(input())
y = int(input())
z = x//y

n = z
while z >=1:
    z = z//y
    n = n+z
    if z <1:
        break

cola = n+x
print(cola)
```

## 錯誤訊息

無（但judge顯示wrong answer)
## 問題描述
設X為購買數量
設Y為多少瓶可在兌換一瓶
設Z為可兌換的瓶數
設定迴圈，當Z>=1時，迴圈就會持續下去
當Z<1時，迴圈就會結束
最後取Cola=X+N(購買數量＋可以兌換數量）

**Comment by TJ72** [comment]
請修正提交連結與程式碼，細節請參考[GitHub 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)

**Comment by cyhsieh264** [comment]
@taiwansui 你給的是題目本身的連結，而不是你提交答案的連結，請參考 [GitHub 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036) 做修改
