### ISSUE TITLE
[Homework 1] 吉吉印方形 

### ISSUE THREAD

**Issue by achiachia** [coding-coworking-club/python-spring-2021#160]
## 程式碼

```python

```
s_input = int(input())
s_output = " "
for num in range(1,s_input+2):
    if num == 1 or num == (s_input+1):
        s_output += ("*" * (s_input))
    else:
        s_output += ("*" + " "*(s_input-2) + "*")
        
print(s_output)

## 錯誤訊息

Wrong Answer。

## 問題描述

求救！該如何讓每一列都換行？

**Comment by TJ72** [comment]
可以放兩個以上的 print ，不一定只能放一個 print～如果在每一輪的 for-loop 迴圈都有放 print 輸出的話，就可以輕鬆解決每一列換行的問題囉～

**Comment by TJ72** [comment]
另外，下次發 GitHub Issue 請附上提交連結並注意程式碼的格式，細節請參考[GitHub 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)
