### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by alonso1331** [coding-coworking-club/python-spring-2021#161]
## 提交連結

https://judge.ccclub.io/contest/25/problem/0101

## 程式碼

```python
cola = int(input())
exchange = int(input())
empty = cola//exchange

while empty >= exchange:
    empty += empty//exchange
    break
    
print(cola + empty)
```

## 錯誤訊息

Wrong Answer

## 問題描述

cola 是小葉買的數量
exchange 是廠商空瓶兌換的規定數量
empty 是 cola // exchange 新增的空瓶數量
當empty >= exchange進入迴圈
將cola小葉買的數量加上新增的空瓶數量，就是小葉要喝的可樂總數

在jupyter測試是成功的，但是上傳系統顯示錯誤，請指教。

**Comment by TJ72** [comment]
這樣的算法，雖然有把下一次可以換到的可樂加進空瓶的數量，但沒換到的空瓶在這算法中好像就直接丟掉了。但事實上我們仍然可以持續存之前沒換的空瓶，期待可以累積到兌換的空瓶數，具體的想法可以參考助教們提供的[HW1-Hint](https://www.notion.so/ccclub/HW1-Hint-6613ab7ba9c243e6a6b2e65e0b0afc3e)

**Comment by TJ72** [comment]
另外，下次發 GitHub Issue 請注意提交連結與程式碼格式，細節請參考[GitHub 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)

**Comment by alonso1331** [comment]
下次會注意，格式有修正了。

**Comment by TJ72** [comment]
> 下次會注意，格式有修正了。

還有提交連結也要記得喔～

**Comment by alonso1331** [comment]
```python
cola = int(input())
exchange = int(input())
empty = cola // exchange

while empty >= exchange:
    cola += cola // exchange
    empty = (empty % exchange) + (empty // exchange)
    break
    
print(cola + empty)
```
修改成這樣，雖然運算正確，但是上傳還是錯誤，請教哪裡出錯呢？

**Comment by TJ72** [comment]
這樣的運算不會是正確的，`cola`變數的運算不符合題意，建議使用[Trace Code](http://pythontutor.com/visualize.html#mode=edit)檢查一下程式碼的邏輯，可以試試`cola = 7, exchange = 4`這組測資。

**Comment by alonso1331** [comment]
```python
cola = int(input())
exchange = int(input())
empty = cola // exchange

while cola >= exchange:
    cola += cola // exchange
    empty = (empty % exchange) + (empty // exchange)
    break
    
print(cola + empty)
```
這次有解出 cola = 7，exchange = 4，但是系統還是 Wrong Answer。

**Comment by TJ72** [comment]
請問你有用 [Trace Code](http://pythontutor.com/visualize.html#mode=edit) 檢查程式碼運算的邏輯了嗎？如果有你應該會發現在這個情境中的 while-loop 裡面是不用加 break 的，你加了 break 會在執行 while-loop 的時候只執行裡面的運算步驟一次就會跳出來了，應該不太是你想做的事。可以試試`cola = 11, exchange = 3`這組測資。

**Comment by alonso1331** [comment]
感謝，我再試試。

**Comment by alonso1331** [comment]
感謝，雖然解出來了，但是有個步驟跟HW1-Hint解說不同。
