### ISSUE TITLE
[General] 8-3：及格門檻

### ISSUE THREAD

**Issue by yolingyang** [coding-coworking-club/python-spring-2021#164]
## 提交連結

    
https://judge.ccclub.io/status/15ba2211723f1d1d407f25d27d235996  

## 程式碼  

```  
def threshold(l, t):
    result = []
    for grade in l:
        if int(grade) >= int(t):
            result.append(True)
        else:
            result.append(False)
    return result

l = input().split()
t = input()
threshold(l, t)

```

## 錯誤訊息  

Wrong Answer  

## 問題描述
寫法是在 threshold function 裡面加入兩個參數 l, t  
l, t 都各自有處理成 int，拿了幾個測試也都 ok  
不知道為什麼 wrong answer     
再麻煩助教看看了～謝謝！

**Comment by TJ72** [comment]
最後要用`print()`函式輸出 threshold function 回傳的串列喔

**Comment by yolingyang** [comment]
原來如此！謝謝 🙏
