### ISSUE TITLE
[General] 6-4 : 數字和

### ISSUE THREAD

**Issue by yutingchen526** [coding-coworking-club/python-spring-2021#165]
## 提交連結

http://localhost:8888/notebooks/Untitled9.ipynb?kernel_name=python3
## 程式碼

```python
num = input()
list1 = num.split()
list_num = [int(i) for i in list1]

print(sum(list_num))
```

## 問題描述

想法是先將input(字串)先切割成串列，再用list comprehension把str型態變成int型態，最後再加總這個串列。
輸入123結果得到123...請問是型態沒轉變成功嗎？
查了一下type( i in list_num)，居然說型態是Bool!!!

**Comment by TJ72** [comment]
請先修正提交連結，細節請參考[GitHub 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)
