### ISSUE TITLE
[General] 6-4 : 數字和

### ISSUE THREAD

**Issue by yutingchen526** [coding-coworking-club/python-spring-2021#166]
## 提交連結

https://judge.ccclub.io/status/a25541de74ae26591e2dde7c45b97c2c
## 程式碼

```python
num = input()
list1 = num.split()
list_num = [int(i) for i in list1]

print(sum(list_num))
```

## 問題描述

想說先轉換字串成串列，然後用list comprehension將串列裡的str轉成int，最後再加總串列裡的數。
結果輸入123得到123，請問是否型態沒轉換成功？

**Comment by TJ72** [comment]
因為`num.split()`是對 num 這個字串型態的變數以空白切割後存進串列中，但數字和這題輸入的 num 數字間是沒有空白間隔的，所list1 串列會是['123']，不會是每個數字分開後組成的串列。你的想法應該用`list_num = [int(i) for i in num]`就可以囉

**Comment by yutingchen526** [comment]
原來如此！反而想複雜了，謝謝助教提點！
