### ISSUE TITLE
[Week 3] 小明採蘋果

### ISSUE THREAD

**Issue by NTNU-CYY** [coding-coworking-club/python-spring-2021#168]
## 程式碼

```
input_lst = input().split(",")    #把輸入資料分割成串列，格式是str

int_lst = [int(i) for i in input_lst]   #把串列的str轉成int

n = len(int_lst)

if n == 1 or n == 2 :
    print (0)

else:
    total = int_lst[0] + int_lst[1]  #計算第一個的apple數
    apple_num = [total]              #放到串列裡面

    for j in range(1, n-1):
        total = int_lst[j-1] + int_lst[j] + int_lst[j+1] 
        apple_num.append(total)

    total = int_lst[n-2] + int_lst[n-1]   #計算最後一個的apple數
    apple_num.append(total)

    max_apple = max(apple_num)                 #找最大的apple數
    print(apple_num.index(max_apple))        


```

## 錯誤訊息

**![image](https://user-images.githubusercontent.com/80100772/111410635-136df100-8714-11eb-9ba1-dd493efa4124.png)**
## 問題描述

在Python Tutor 一步一步運作，可以成功。
但在 jupyter 試行，會卡在最後兩行程式，就是當我要用max這個函數去取最大的apple數時，
會跳出 'int' object is not callable 的訊息。

網路爬文是說，可能我用的變數名稱與python系統內建相同，但修改後仍然出現相同訊息。
只好來跟助教們求教了~~謝謝。

**Comment by TJ72** [comment]
程式執行上應該是沒有什麼問題，建議可以 restart kernel 重新跑看看

**Comment by TJ72** [comment]
btw 下次請注意貼程式碼的位置，細節請參考[GitHub 發文須知](https://www.notion.so/ccclub/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)

**Comment by NTNU-CYY** [comment]
謝謝助教提醒，因為預覽看起來差不多，以為貼文格式正確。剛剛已經又看過發文須知，之後會注意，謝謝。
