### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by jimmy97332** [coding-coworking-club/python-spring-2021#17]
## 提交連結

https://judge.ccclub.io/status/65cd40fdf50fcfde4df948e22c0d5830
## 程式碼

```python
a=input()
b=input()
c=int(a)//int(b)
x=0
rest=int(a)%int(b)
restc=rest+int(c)
nb=int(b)
for i in range(100) :

        d=int(restc)//int(b)
        x+=d
        restc=restc-int(b)*d+d
        if restc < nb:
          break

y=int(a)+int(c)+int(x)
print(y)
```

## 問題描述

a為起始可樂數，b為賣場規定兌換。
先算出c為第一次換到的可樂，
再將換完後剩下不足的空瓶，加上換到的c，等於restc，
用了一個回圈讓他算，剩下的與換到的瓶數總和小於b時就跳出迴圈，
最後再加總。

用迴圈是為了確保是否還能再換可樂，想請問是否有不用迴圈解決方法，謝謝！

**Comment by andykuo0956** [comment]
(我是學員所以只是盡我所能看看)
1.如果小葉買超多可樂讓你的迴圈跑超過100次好像就不能正確執行了
2.我沒有看ㄉ非常懂，但是如果今天小葉買2瓶但是賣場規定兌換是3瓶不知道可不可以正確執行
3.以我所看restc似乎就是a（整除加餘數），所以我猜想可能數字會過大
建議可以在比較關鍵的步驟print出來，方便檢查問題在哪裡～～
我自己這題也還沒解出來，數字io都是對的但是繳交都是wa，不過希望上面三點有稍微幫到ㄋ

**Comment by cyhsieh264** [comment]
按照這樣的思路，似乎比較適合用迴圈來解。
不過如果考量運算效率而要找其他解法的話，可能就要再看看有沒有相關的數學證明了。

另外以目前的程式碼來看，也許可以考慮用while迴圈，這樣後面不用再寫一次判斷式；
以及在一開始賦值的時候，若先把 input 轉成整數型態，就不用每一次運算都用 int() 再做型別轉換；
這樣應該也可以寫起來再簡潔一些。
