### ISSUE TITLE
[Week 3] 比賽排名

### ISSUE THREAD

**Issue by DAZandy** [coding-coworking-club/python-spring-2021#171]
## 程式碼

lst = [int(s) for s in input().split(" ")]
sorted_lst = sorted(lst)
ind = [sorted_lst.index(i) for i in lst] 
for j in ind:
    print(f"{j}", end = " ")

## 錯誤訊息
wrong answer

## 問題描述

這個做法跟demo的有點不一樣，例如輸入 2 4 4 3 會回傳 0 2 2 1，想問問用我的作法有什麼辦法可以解決會重複算到index的問題？謝謝

**Comment by TJ72** [comment]
我想到可以解決 index 問題的方法有 2 個：
1. 用二維的串列存`[[選手1秒數, 選手1's index(0)], [選手2秒數, 選手2's index(1), ...]`，然後用選手的成績做sorting，最後按照 sorting 的結果輸出選手的 index
2. 可以參考凱文課堂上 demo 的做法，在用 sorted_lst 對回去原本的 lst 查選手的 index 時，選到之後做個記號，下次選的時候碰到做過記號的就跳過尋找下一個，但這個方法就比較不適合用 list comprehension
