### ISSUE TITLE
[General] 8-2：最長字串

### ISSUE THREAD

**Issue by Lienwuuu** [coding-coworking-club/python-spring-2021#172]
## 提交連結

https://judge.ccclub.io/status/c018d2732c0389b90eda66adc0391650

## 程式碼

```python
def longest_str(l):
    print(max(l))
   
lst = input().split(" ")
longest_str(lst)
```

## 問題描述

在jupyter上測試都ok
但在judge是wrong answer
我的想法就是印出串列中最長的字串
所以直接print(max(l))
不曉得是哪裡沒考慮到嗎?
謝謝!

**Comment by chianshianli** [comment]
(非助教，僅供參考)

max() 函數裡面如果放 str 的話會回傳字串裡字元的 ASCII 碼最大值喔，可以試試 zzz aaaa 這筆測資。
可以再想想看有沒有其他辦法可以只用字數多寡來排序~

**Comment by Lienwuuu** [comment]
原來如此! 感謝你提供的資訊~
修改後已經過關了(灑花
