### ISSUE TITLE
[General] 7-2：加減長方形

### ISSUE THREAD

**Issue by cys939** [coding-coworking-club/python-spring-2021#173]
## 提交連結

https://judge.ccclub.io/status/f83f225c6422612407b2334cd6677533
## 程式碼

```python
l = input()
w = input()

for i in range(1, int(w)+1):
    if int(l)==1 and int(w)==1: #如果長寬都是1，直接print出一個+，即結束
        print("+")
        break
     
    if int(l) % 2 == 0: 
        if i % 2 == 0: #雙行以-+開頭；單行則以+-開頭；
            print("-+" * (int(l)//2)) #以+-或-+為一組，再乘上（長/2取整數）
        else :
            print("+-" * (int(l)//2))
            
    else:
        if i % 2 == 0:
            print("-+" * (int(l)//2) + "-") #若長度為單數，被無條件捨去會少一個，最後再補上少掉的+或-
        else :
            print("+-" * (int(l)//2) + "+")
```

## 錯誤訊息

<img width="1127" alt="截圖 2021-03-17 下午5 00 47" src="https://user-images.githubusercontent.com/62044243/111441559-6494d980-8742-11eb-863a-148a45f56630.png">

## 問題描述

問題：
在 Jupyter Notebook 上測過多組數字都沒問題，但在 Judge 系統上都是 WA
想請問是否哪裡沒考慮到？

解題思路為下：
分為單行雙行處理
並以+-或-+為一組，再乘上（長/2取整數）
（常為雙數則沒問題；為單數最後會少一個）
因此若長度為單數，最後再補上少掉的+或-
雙行以-+開頭；單行則以+-開頭

**Comment by TJ72** [comment]
題目理解錯囉～題目的意思應該是要在換行之後排列的順序還是要延續上一行末的符號接續排下去。可以試試 Judge系統上的 Sample Input 2

**Comment by cys939** [comment]
喔喔喔喔！抱歉一直沒看清楚，我再試試看，謝謝助教！
