### ISSUE TITLE
[General] 8-4:最大公因數

### ISSUE THREAD

**Issue by emilyjenjen** [coding-coworking-club/python-spring-2021#174]
## 提交連結

https://judge.ccclub.io/status/bcef0a9c3f426e8ecd0961bc2f6fde58
## 程式碼

```python
def gcd(l1, l2):
    str_l1 = l1.split()
    str_l2 = l2.split()
    int_l1 = [int(a) for a in str_l1]
    int_l2 = [int(b) for b in str_l2]
    result = []
    for i in range(len(int_l1)):
        factor_l1 = []
        factor_l2 = []
        for j in range(int_l1[i]):
            if int_l1[i]%j == 0: 
                factor_l1.append(j)
        for k in range(int_l2[k]):
            if int_l2[i]%k == 0: 
                factor_l2.append(k)
        same = []
        for m in range(len(factor_l1)):
            for p in range(len(factor_l2)):
                if factor_l1[m] == factor_l2[p]:
                    same.append(factor_l1[m])
        result.append(max(same))
    print(result)
first = input()
second = input()
gcd(first, second)

```

## 問題描述

我的想法是用巢狀迴圈，
先將index從0到-1一個一個找出l1和l2分別的所有因數（命名為factor_l1及factor_l2）
找出他們分別的所有因數之後，再用一個迴圈找出他們的公因數（命名為same的list）
找出所有的公因數之後再找裡面最大的，append到最終要印出來的結果result這個list裡面
因此我最外面的迴圈跑完一次就代表找完一個index的最大公因數也把它append到result裡面
-
結果在jupyter跑第一個測值就出現integer division or modulo by zero這段話 不太懂是什麼意思
放到judge系統則是寫說runtime error
我知道我的邏輯好像利用了太多迴圈，似乎很沒有效率，不過我想不到其他更好的方法，能否麻煩助教提示或是指正？

**Comment by TJ72** [comment]
A1：會造成 integer division or modulo by zero 這個錯誤訊息，是因為 `for j in range(num):`的 j 是從 0 跑到 num-1喔。平常在用這種 for-loop 的寫法時要特別注意起始值與終值喔。
A2：有蠻多種寫法可以增進效率，像是兩個 list 對應 index 的元素一起跑 for-loop 找最大公因數，更進一步也可以用輾轉相除法替換跑一個 for-loop 找最大公因數。
另外一個小建議：函式通常是用於處理一個固定執行的程序，所以在這個情境中，在函式中應該只適合處理計算最大公因數，然後在函式外的主程式再執行輸入轉串列、拿串列中對應的元素用 `gcd函式` 計算…。可以參考 #162 這篇的討論喔
