### ISSUE TITLE
[General] 綜合1-2：一奇多偶

### ISSUE THREAD

**Issue by siddwang827** [coding-coworking-club/python-spring-2021#176]
## 提交連結
https://judge.ccclub.io/status/f20e3596277bac46d189fdaa06d015b2

## 程式碼

```python
num_str = input()
num_str_lst = num_str.split(' ')
num_int_lst = [n for n in num_str_lst]
for num in set(num_int_lst):
    num_count = num_str.count(num)
    if num_count % 2 == 1:
        print(int(num))
```

## 錯誤訊息
![圖片](https://user-images.githubusercontent.com/69707312/111469481-b6009100-8761-11eb-8031-3f219410b19c.png)

## 問題描述
用jupyter跟pythontutor一步一步檢查，邏輯上應該都沒有問題，
範例也能夠達成，另外也自己試了一些測資都可以順利print出，
原本有在想最後到底要print的資料型態是int還是str，兩種都有測試過，
在judge系統上print(num)是WA, print(int(num))是RE，
請問還有什麼地方沒考慮清楚嗎，或是因為我使用了set這個資料型態呢?還請協助提點~

**Comment by TJ72** [comment]
第五行的`num_count = num_str.count(num)`我感覺應該是你不小心打錯，原本應該是要打`num_str_lst.count(num)`(?
因為假如是原本的`num_str.count(num)`， num 是一開始輸入的字串，`.count()`之後可能會蒐集一些不能轉換成整數的字串(e.g. "1 10 100"之類的)。所以`print(num)`會WA，`print(int(num))`會RE

**Comment by siddwang827** [comment]
原以為count是string才可以用的方法，沒想到list也可以用，謝謝!

**Comment by siddwang827** [comment]
剛想到之前會錯的原因應該是如果是count原字串的話有可能 num = 1, 字串含 "1 1 10 100 100 1"的話，會被計算為6個而不是3個
但是修改之後還是一樣的結果，如下圖，還有什麼情況會造成錯誤呢?
![圖片](https://user-images.githubusercontent.com/69707312/111595747-67a5cd80-8807-11eb-8726-5ff6c59509cb.png)

**Comment by TJ72** [comment]
建議`num_str`做split的時候用`num_str.split()`就可以了，如果用`num_str.split(' ')`的話，會限制只能用一個空白來切割，可以避免一些測資最後留了一堆空白的情況。這樣應該可以解決 Runtime Error 的問題

**Comment by siddwang827** [comment]
照建議修改後，變成跑出time limit exceeded....崩潰
![圖片](https://user-images.githubusercontent.com/69707312/111727872-b0f92a00-88a6-11eb-87dd-6bd58752b700.png)

**Comment by TJ72** [comment]
因為題目說只會有一個奇數，所以如果已經找到奇數的話就 break 出 for-loop 應該可以稍微減少執行的時間，說不定就可以解決 TLE 的問題了。另外 for-loop 的元素用 set 來取是個好方法，但`lst.count()`來計算 set 中每個數字出現次數效率有點慢，用要不要試著用 dictionary 來存數字出現次數的結果，最後再取 dictionary 的 key, value 來判斷出現次數的奇偶，我猜效率應該會比`lst.count()`快一些
