### ISSUE TITLE
[General] 181103 字串加密II

### ISSUE THREAD

**Issue by cy-hsu-md** [coding-coworking-club/python-spring-2021#177]
## 提交連結

https://judge.ccclub.io/status/eadc85fa2f911327d2023c643749b596

## 程式碼

```python
a=input()
b=int(input())
b=str(b)
lst1=[]

if len(a)==len(b) or len(a)<len(b): 
    for i in range(0,len(a)):
        lst1.append(chr(ord(a[i])+int(b[i])))
        continue
elif len(a)>len(b):
    for i in range(0,len(a)):
        if 0<=i<len(b):
            lst1.append(chr(ord(a[i])+int(b[i])))
            continue
        elif i>=len(b):
            lst1.append(chr(ord(a[i])+(i+1)))
            continue
stranswer=''.join(lst1)
print(stranswer)
```

## 問題描述

用批改系統上提供的兩組測資在我自己的電腦上跑都是對的，不過丟到批改系統就變成 wrong answer了。

我是先用英文字串與數字的長度來判斷：

如果兩者長度相同或是數字比較長，那麼就不會有補數字的問題，直接用英文字串的 ASCII code 加上數字中相對應的位置的數字再轉換回英文字母，加到新的串列lst1中。

如果英文字串比較長，那麼在使用for回圈中到數字的長度以前，都是直接用英文字串的 ASCII code 加上數字中相對應的位置的數字再轉換回英文字母，加到新的串列lst1中；但使用到數字的長度以後，因為要補齊，所以用英文字串的 ASCII code 加上該位置的index數字+1來轉換回英文字幕，再加到新的串列lst1中。

最後將串列轉換為字串輸出。

不知道我的寫法與邏輯哪裡有問題呢？再麻煩您們回答了，謝謝！

**Comment by TJ72** [comment]
請先修正提交連結與程式碼格式，細節請參考[GitHub 發文須知](https://www.notion.so/ccclub/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)

**Comment by cy-hsu-md** [comment]
謝謝提醒，不好意思沒注意到。麻煩您了！

**Comment by TJ72** [comment]
問題會出在字串長度比數字長度長的情況喔

**Comment by cy-hsu-md** [comment]
請問問題是出在字串長度>數字長度的程式的哪邊呢？我用測資上的 ccClub 以及 61743 去跑，output 是批改系統上的 idJpxh ，最後一個b 以及output 的最後一個h 的ASCII code 相差6，所以我的理解是如果字串長度比數字長的話，就是 ASCII code 補 index+1來轉換，請問這個邏輯是哪裡出了問題呢？

謝謝您！

**Comment by TJ72** [comment]
題目說"如果字串長度較長要把數字補齊"，意思應該是要用輸入的數字字串，拼成跟字串長度一樣吧！
e.g. s = 'ccClub2021', num = '61743' 那加密的數字應該要補齊成 num = '6174361743' 跟字串 s 的長度一樣進行加密

**Comment by cy-hsu-md** [comment]
原來如此，那是我誤會意思了。更改以後程式就被系統accept了，謝謝您的解答！
