### ISSUE TITLE
[Week 2] 小仔填志願

### ISSUE THREAD

**Issue by hadao02** [coding-coworking-club/python-spring-2021#18]
## 程式碼

```python
a = input()
b = input()
if b == "會計系"：
    if a[0]+a[1]+a[2]+a[3] >= 57 and a[0]>=15:
        print('1')
    else:
        print('0')
if b == "公衛系"：
    if a[1]+a[2]+a[4]>=38:
        print('1')
    else:
        print('0')
if b == "經濟系"：
    if a[3]+a[4]>=26 and a[2]>=15:
        print('1')
    else:
        print('0')
if b == "資工系"：
    if a[1]+a[4]>=27 and a[2]>=15:
        print('1')
    else:
        print('0')
```
## 問題描述

Since I am not Taiwanese so I do not know exactly how this regulation works. Base on what I have researched, I wrote this but still I cannot figure out what is going wrong.

**Comment by TJ72** [comment]
Since the grade of each subject is not a single character in this case, you should try "String slicing" to catch each score you need in the conditions.

**Comment by TJ72** [comment]
And the minor reminder, please follow the rules of asking questions in GitHub Issues:
https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e
