### ISSUE TITLE
[Week #4] 字母拼圖

### ISSUE THREAD

**Issue by nick30924** [coding-coworking-club/python-spring-2021#183]
## 程式碼

```python

```

## 問題描述

不好意思因為只是題目的意思不太明白所以沒有填寫上述問題，想問題目的意思是輸入char_puzzle(["apple", "bird", "apple"])之後，我要先在define的函式定義裡擷取輸入內容中的list部分來進行運算嗎？還是在輸入中打入上列字串他就會直接運算define的意思？相較於先前只要輸入define f(lst)中的lst部分，我不太清楚是否有差異

**Comment by hchbiggrass** [comment]
我看不太懂你的描述，不過這一題不用寫input和output，只要把一個完整的函式貼上去就好。當然你在自己的jupyter notebook上面測試的時候還是要設一下input和output，不然會不太知道自己在幹嘛。

**Comment by nick30924** [comment]
喔喔！原來是答案只要貼一個函式的意思，而下面的例子只是供我檢查使用的囉？把題目的意思想的太複雜了ＸＤ
謝謝你的回答
