### ISSUE TITLE
[Week #] 秘密紙條

### ISSUE THREAD

**Issue by jennifer090** [coding-coworking-club/python-spring-2021#186]
## 程式碼

```python
list1=[]
n=input()
while n!="end":   #如果沒有輸入end迴圈不會停止
    list1.append(n)  #將輸入的每個句子存到list1裡
    n=input()
for i in range(0,len(list1)): #一行一行句子的取
    k=list1[i]    
    for t in range(0,len(k)): #取其中一個字
        print((ord(k[t])+219)*2,end=" ")  #丟入凱薩密碼裡加密
        if k[t]==" ":   #如果是英文句子中間空格的index值去掉不取
            continue
        print() 

```

## 問題描述
試過兩個sample系統還是回復wrong answer, 我想請問一下是不是出在英文字掠過空格的取法(但我刪除if 那行用sample測的答案還是根sample answer一樣)，想請助教幫忙看一下，謝謝

**Comment by MrConnor0225** [comment]
我不是助教，
但這題不用input，
而是直接將sample的input " char_puzzle(["apple", "bird", "apple"]) "直接放到程式碼裡

**Comment by jennifer090** [comment]
但你說的那題跟我的好像是不同題欸，你講的好像是字母拼圖，我這題是祕密紙條，還是說這題也是??

**Comment by jennifer090** [comment]
> 我不是助教，
> 但這題不用input，
> 而是直接將sample的input " char_puzzle(["apple", "bird", "apple"]) "直接放到程式碼裡
