### ISSUE TITLE
[Week 4] 秘密紙條

### ISSUE THREAD

**Issue by jl60710** [coding-coworking-club/python-spring-2021#189]
## 提交連結

https://judge.ccclub.io/status/8bb0ad8a68bb3b512bdeb8e0535810cd

## 程式碼

code = input()
output = []
while code != "end":                               #沒輸入"end"就繼續跑
    output = [(ord(j) + 219) * 2 for j in code]    #用上課補充的方式將結果存在output這個list
    for j in range(len(output)):                   #將output裡面每一個元素印出來，中間用空格分開
        print(output[j], end = " ")
    print("")                                      #每次輸入前要換行，前面因為同一行間用了空格分開，因此這裡插入一個空字元
    code = input()                                 #再次輸入，直到"end"被輸入
    output = []                                    #把output歸零

## 問題描述

測資的結果正確
自己覺得是排版(換行)的問題
因為不太熟join所以用比較簡單的print(   , end = " ")
但還要再換行所以再輸出一個空字元
應該是錯在這，但又想不到為何會出錯
要再麻煩助教抽空幫忙解惑了
感恩！

**Comment by TJ72** [comment]
輸出的數字間以空白分隔，但最後一個數字後面不能有空白喔～

**Comment by TJ72** [comment]
另外，下次發 GitHub Issue 請注意程式碼格式，細節請參考[GitHub 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)

**Comment by jl60710** [comment]
感謝助教！AC了，沒問題下次會注意！
