### ISSUE TITLE
[Homework 1] 吉吉當老師

### ISSUE THREAD

**Issue by Yueh-H** [coding-coworking-club/python-spring-2021#19]
## 提交連結
https://judge.ccclub.io/status/eac62127333a8058a0a6e92a51d8ac9c

## 程式碼

```python
input1=input()
input2=input()
input3=input()
  
a = float(input1) #係數a
b = float(input2) #係數b
c = float(input3) #係數c

diff = b ** 2 - 4 * a * c #計算判別式

if a == 0: #若a==0,則不為一元二次方程式，不帶入公式解
    if b == 0:
        if c == 0:
            print(-1) #無限多組解
        else:
            print(0) #無實數解，等式不成立？
    else:
        if c == 0:
            print(1) #一個解
            print(0) #該解的解答
        else:
            print(1) #一個解
            print(-c / b) #該解的解答

else: #若二次項係數不等於0，則有方程式公式解
    solve_1 = (-b / (2 * a)) + (diff ** (1 / 2)) * (1 / (2 * a)) #公式解1
    solve_2 = (-b / (2 * a)) - (diff ** (1 / 2)) * (1 / (2 * a)) #公式解2
    if diff > 0: #若判別式大於零
        print(2) #兩個解
        if float(solve_1) > float(solve_2): #考慮兩種不同解的大小排序關係，因題目要求要由小至大排序
            if solve_1 == 0: #考慮若a!=0 ,b!=0 c=0的情況可能會出現-0的情況，雖然(if bool(0=-0) 是True還是加入
                print(solve_2)
                print(0)
            elif solve_2 == 0: #同上的考慮
                print(0)
                print(solve_1)
            else:            #若 a!=0,b!=0 c!=0,的情況就會出現非零的兩個解若下
                print(solve_2)
                print(solve_1)
        else:        #考慮兩種不同解的大小排序關係，因題目要求要由小至大排序
            if solve_1 == 0:
                print(0)
                print(solve_2)
            elif solve_2 == 0:
                print(solve_1)
                print(0)
            else:
                print(solve_1)
                print(solve_2)

    elif diff == 0:
        if b == 0:   #若a !=0,b==0,c==0會出現-0,如上所是修正為0
            print(1) #一個解
            print(0) # 該解的解答
        else:       #若a !=0,b!=0,且判別式為零會出現單一解
            print(1) #一個解
            print(-b/2*a) #該解的解答

    elif diff < 0: # a!=0 且判別式小於零為無實數解
        print(0) #結果為無實數解

```

## 問題描述
在解一元二次題目
透過變數a、b、c 透過去承接 input()的三個值
因input()的值可能為小數點或是負數，故用float去轉換格式

if a==0:
首先透過if 進行係數a的判斷，因a==0的話就不會是一元二次方程式
降維成一次式
針對a==0再次進行分解，若b==0，且c==0就會出現題目中的無限多組解
所以print(-1）作為回應

但是這邊有個問題，若輸入b==0但c！=0，不知道該print什麼東西？ 
若a=0 b=0 c=5 ,此等式不應該成立，但題目沒說明a、b、c input的範圍為何

if a!=0:
接下來就是標準一元二次方程式的解法
然後進行判別式的判斷
若判別式大於零
   帶入公式解得到兩個解
     solve_1 
     solve_2
    判別式等於零
    print( -b/2a)作為回應
   判別式小於零 
   print(0)作為回應

以上是我程式的思路，我在code中也有做註記！！謝謝～～

> 我透過測試各種數據，對於係數大小大於零 小於零和等於零 都進行測試
，而在一些不同組合之中，有些會有不類型的解也都進行測試
下面只列出了一些測試出來的結果~

> 

EX：a>0  b>0  c>0 
1.無實數解  a=1 b=1 c=1
[out]
0
-----------------
2.單一解a=1 b=2 c=1 
[out]
1
-1.0
---------------
3.雙解
[out]
2
-3.0
-1.0
--------------
EX：a>0 b>0 c=0 
a=2 b=4 c=0
[out]
2
-2.0
0
---------------
EX：a>0 b>0 c<0
a=2 b=4 c=-4
[out]
2
-2.0
1.0
----------------
不過貼到批改系統上還是wrong answer 不知道是哪裡眼殘看錯或是哪個邏輯想錯了，感謝回覆～～～

**Comment by etethanchen** [comment]
我也遇到一樣的問題ㄟ！

**Comment by GailJiang** [comment]
有發現像#x^2-x=0 的解會出現 
2(兩個解)
-0.0
1.0
這種答案，但不知道是不是因為出現-0是錯誤的關係
(我自己把-0排除掉之後答案還是錯的QQ)

**Comment by Yueh-H** [comment]
恩恩我也有都有嘗試過，不知道卡的點在哪裏？
我也有嘗試過，因為題目的測試答案有浮點數個數的問題，我也嘗試把答案都修成只能有一個浮點數，也是不行
我也測試了a==0 b==0 c!=0 這樣的情況帶入無限多組解或是無實數解
然後一般有時後會重根，一般數學上算是兩個解或是一個解看怎麼看待 我都帶入試過了
按照題目的情境國中生重根應該算是單一解吧

有沒有助教或是其他人可以幫忙看一下 ＱＱ

**Comment by TJ72** [comment]
程式好像沒什麼問題，但在第54行的註解`＃該解的解答`的井字號好像有問題，可以請妳改一下重新貼 Judge嗎？

**Comment by TJ72** [comment]
這題會有浮點數運算的問題，所以後來都建議大家答案如果是小數的話，就無條件捨去到小數點後第三位。抱歉比較晚看到這篇討論！另外測資不會出現 a = 0, b = 0 但 c != 0的情況喔！
