### ISSUE TITLE
[Week 4] 秘密紙條

### ISSUE THREAD

**Issue by jasonluo07** [coding-coworking-club/python-spring-2021#191]
## 提交連結

https://judge.ccclub.io/status/8bb0ad8a68bb3b512bdeb8e0535810cd

## 程式碼

```python
# 多行輸入，輸入"end"就跳出
# text 為所有文字，其中 text[0] 表示第一行輸入的，text[1] 表示第二行輸入的，以此類推
text = []
while True:
    raw = input()
    if raw == "end":
        break
    text.append(raw)

# 建立密碼的 list
cipher = []
for i in range(len(text)):
    cipher.append([]) # 建立 cipher[i] = []
    for j in range(len(text[i])):
        cipher[i].append(str((ord(text[i][j]) + 219) * 2))

# 印出密碼的 list
for i in range(len(cipher)):
    print(" ".join([num for num in cipher[i]]))
```

## 問題描述

請問能在「多行輸入」的情況下，我的程式碼有更簡潔的寫法嗎？
註：這程式碼能 Accepted，我原本以為是「多行輸入，直到輸入"end"停止，再一次輸出全部」，但 demo 的程式碼是輸入一句，輸出一句。

**Comment by TJ72** [comment]
多行輸入的情況，這樣的寫法我認為應該已經是最好的了。因為只要輸出的結果跟 Judge 預設一樣，所以不論是「多行輸入，輸入結束後，再一次輸出全部」，或是像 demo 一樣「輸入一句，運算完後輸出一句」，都是可以被接受的喔！

**Comment by yulaie1012** [comment]
> 多行輸入的情況，這樣的寫法我認為應該已經是最好的了。因為只要輸出的結果跟 Judge 預設一樣，所以不論是「多行輸入，輸入結束後，再一次輸出全部」，或是像 demo 一樣「輸入一句，運算完後輸出一句」，都是可以被接受的喔！
