### ISSUE TITLE
[Week 4] 打字機

### ISSUE THREAD

**Issue by Lienwuuu** [coding-coworking-club/python-spring-2021#192]
## 提交連結

https://judge.ccclub.io/status/daaa789dd027e04ad00e1d789256c709

## 程式碼

```python
s = input()

for c in s:
    i = s.index(c)
    if c == "+":
        if i == 0:
            s = s[1:]
        else:
            s = s[:i] + s[i-1] + s[i+1:]
    
    elif c == "-":
        if i == 0:
            s = s[1:]
        else:
            s = s[:i-1] + s[i+1:]
    
    elif c == "*":
        if i == 0:
            s = s[1:]
        else:
            s = s[:i] + s[:i]
    
    else:
        s = s[:]
        
print(s)
```

## 問題描述

想法是用迴圈把字串中的字母一個個挑出來, 
若字母有與 + , - , * 其一相同, 則執行該符號對應功能
i 是該次字母在字串中的index

在jupyter上測試可以
但是judge過不了
不曉得是哪邊有問題呢?

**Comment by TJ72** [comment]
Runtime Error 是因為在執行 '*' 的運算時，改變字串後有可能造成下一輪的迴圈找不到 c 對應的 index。 e.g. s = 'abc\*d'。另外除了 '*' 運算上的問題之外，取`i = s.index(c)`在這邊是很危險的事，因為` .index()`只會回傳在字串中**第一個**找到字元對應的位置，如果你想做的是跑一次 for-loop 抓出字串每個 index 的字元的話，建議可以用這種寫法：
```python
for i in range(len(s)):
    c = s[i]
```

**Comment by Lienwuuu** [comment]
感謝點出 .index()只會回傳在字串中第一個找到字元對應的位置這件事
雖然最後不是採用for i in range(len(s))的寫法
不過多試幾次後問題已解決了~
