### ISSUE TITLE
[Week 4] 打字機

### ISSUE THREAD

**Issue by zoee22** [coding-coworking-club/python-spring-2021#193]
## 程式碼

```python
def type_function(l):
    for m in range(len(l)):
        if "+" in l:
            l_list=l.split()
            l_list.pop()
            result=l_list.append(l[-1])
            return result
        if "-" in l:
            l_list=l.split()
            result=l_list.pop()
            return result
        if "*" in l:
            l_list=l.split()
            result=l_list+l_list
            return result
str=input()
print(type_function(str))
```

## 問題描述
單純想針對demo的程式碼提問

Q1.為甚麼要另外建立一個"ans=[]"?建立空串列有甚麼用途?還能應用在哪裡?
Q2.為甚麼能夠讓print(c)是print出符號?是指定的特別用法嗎?
Q3.按照學過的指令，ans串列中同時有數字/字母和指定功能+-*的話，為甚麼可以不用先移除+-*再開始寫指定指令?
Q4.ans明明是空串列，也沒看見將typer(input)轉為或加入ans(list)的步驟，為何能夠直接在if-else執行指定指令?

我的想法:把input轉list，去除+-*，再另外執行+(複製最後一個字)、-(移除最後一個字)、*(複製全部字元)
會有這些問題是因為我原本的想法跟demo的差非常多，覺得自己太不足，沒有搞清楚原因的話擔心以後沒辦法回到指令的定義並變通 問題比較多 真的很抱歉!

**Comment by TJ72** [comment]
A1：一開始建立一個`ans = []`的空串列是想用來存最後呈現的結果喔～因為串列裡的元素具有順序性，常常用來存運算後的結果
A2：因為我在上面的程式碼和 demo 的程式碼都沒有看到`print(c)`，所以我假設妳問的問題是為什麼可以讀到變數 s裡面的每一個字元 c，並且可以印出來。關於這一種 for-loop 的寫法可以參考 3/11 的上課投影片 p.15，
```python
# s 是一個字串
for c in s:
 # 程式碼
```
這種寫法的 for-loop 可以讀進字串裡的每一個字元，然後在程式碼中針對剛剛讀進來的字元執行運算，投影片中的串列也是差不多的用法喔～
A3：因為在這一題的情境中，比較適合逐一讀進字元(包括'+-*')進行判斷，照著字元的順序讀進來，遇到特殊字元時才能做出相對應的運算，最後再把運算的結果用`.append()`裝進串列 ans
A4：在 demo code 中，要用 if/elif/else 的判斷式中加入 ans 串列的判斷，是因為要確保 ans 串列中是已經有元素的，如果 ans 串列中沒有元素的話(在'+-*符號以前沒有任何字元')，那就不用執行相對應的指令。關於這方面的解釋，可以參考 Judge 上已經更新過的題目資訊喔～

真的不用覺得自己不足，每個題目、每個情境適合切入的角度都不太一樣，我覺得只要多練習，慢慢地可以掌握一些解決問題思考的方向。如果還有問題歡迎再提出來喔～

**Comment by zoee22** [comment]
原來是這樣~有比較理解了 謝謝你這麼用心!!

**Comment by Viggochang** [comment]
@zoee22 若問提已被回答，請關閉問題
（使用方法參考學員須知中的[使用教學](https://www.notion.so/ccclub/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)）
