### ISSUE TITLE
[Week 4] 秘密紙條

### ISSUE THREAD

**Issue by Din0-3** [coding-coworking-club/python-spring-2021#195]
## 提交連結
https://judge.ccclub.io/status/a3e9efd264ab294a85837d5d2d38e5de

## 程式碼

```python

def ces(n):
    return (ord(n)+219)*2

cont = True 
while cont:
    in_s = input()
    if in_s == "end":
        cont = False
    else:
        for i in in_s:
            if i != in_s[-1]:
                print(str(ces(i)), end = " ")
            else:
                print(str(ces(i)))
```

## 錯誤訊息
WA

## 問題描述
先寫了一個小function  ces()來定義轉換密碼的過程
然後設定一個while loop，每一輪都會有input讓測資能夠持續輸入，如果是end則終止
然後把input的string用for loop一個一個提出來轉成密碼，中間用`" "`隔開，如果是該行的最後一位`s[-1]`就不用隔開直接換行
不過還是WA，找不到問題請指點
感謝！

**Comment by TJ72** [comment]
如果 for 迴圈中執行到，剛好遇到中間的字元和最後一個字元相等，那麼 `i == in_s[-1]`就成立了，這樣加密過的數字後面就不會被上空白了

**Comment by Din0-3** [comment]
原來是沒考慮到這點，感謝～
