### ISSUE TITLE
[General] 字串加密II

### ISSUE THREAD

**Issue by nalajhu** [coding-coworking-club/python-spring-2021#196]
## 提交連結

https://judge.ccclub.io/status/6339223b28f58c65fe8f321b71fb0ed8
## 程式碼

```python
alpha = input()
num = input()
if len(alpha) > len(num):
    num = num + num
k = ''
for j in range(len(alpha)):
    k = k + chr(ord(alpha[j])+int(num[j]))
print(k)
```

## 問題描述

驗證兩個範例都對，出現Runtime Error，我覺得自己程式碼寫得很短

**Comment by TJ72** [comment]
這種情況會出現 Runtime Error 有很大的可能是兩倍的`num`字串長度仍然比`alpha`字串還短，所以在 for-loop 中取`num[j]`的時候娶不到對應的字元

**Comment by nalajhu** [comment]
謝謝，把if 改為 while就出現AC
