### ISSUE TITLE
[Week 4] 打字機

### ISSUE THREAD

**Issue by jingyutsao** [coding-coworking-club/python-spring-2021#197]
## 提交連結
https://judge.ccclub.io/status/6abb17a64592cbda7e961f1dec7f3c00

## 程式碼

```python
#打字機

order = input()
lst = []
wordlst = []


for i in order:
    if i == "+":
        for j in order:
            if j != "+" and j != "-" and j != "*":
                last = j
        lst.append(last)
    elif i == "-":
        if lst != []:
            lst.pop()
        else:
            lst = lst
    elif i == "*":
        lst *= 2
    else:
        lst.append(i)
    
print("".join(lst))

```

## 問題描述
1.遇到+把字串中最後一個字母append進新的list，如果前面沒有東西就不動
2.遇到-把list中最後一個東西丟掉，如果前面沒有東西就不動
3.遇到*把list乘二
4.遇到一般字母直接加進list
5.最後print出來
問題:系統顯示wrong answer，但我輸入的東西跑出來都是對的...?我應該漏想了一些狀況...但我找不到...

**Comment by TJ72** [comment]
請附上正確的提交連結，細節請參考[ GitHub 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)

**Comment by jingyutsao** [comment]
抱歉我去看了之後找不到提交連結...所以直接先把提交連結刪掉了可以嗎?

**Comment by TJ72** [comment]
因為你的問題描述裡沒有提到這一段，可以請你幫我解釋一下嗎？
```python
  if i == "+":
      for j in order:
          if j != "+" and j != "-" and j != "*":
              last = j
      lst.append(last)
```
其他部分看起來應該沒什麼問題

**Comment by jingyutsao** [comment]
遇到+的時候，因為不知道前面是字母還是符號，所以找出字串裡面最後一個字母，然後把它加進答案的字串list裡面
提交連結補上了但我不確定是不是對的...?

**Comment by jingyutsao** [comment]
我發現我錯哪裡了但是我修改之後遇到別的問題...我應該重新提一個問題還是直接在這裡貼新的程式碼...?

**Comment by TJ72** [comment]
看你方便，都可以喔
不然也可以直接附上新的提交連結～

**Comment by jingyutsao** [comment]
提交連結:
https://judge.ccclub.io/status/8f4a3654490cc11bf9f054f94a46d004

我改成取(0, +號前面)的最後一個字母
放jupyter是可以的...但系統顯示runtime error

**Comment by TJ72** [comment]
Runtime Error 的原因是 last 不一定可以取到值，e.g. order = '----+'。要不要試試看讓 '+' 的運算跟 '-'、 '*' 的運算一樣，都針對存結果的串列 lst 去做就好

**Comment by jingyutsao** [comment]
完成了!
非常感謝您!!!
