### ISSUE TITLE
[Week 3] 比賽排名

### ISSUE THREAD

**Issue by zoee22** [coding-coworking-club/python-spring-2021#198]
## 提交連結
https://judge.ccclub.io/status/cc23d783b7bedb835178c95972afe645

## 程式碼

```python
lst=input().split()
second_rank=sorted(lst)
index_rank=[]

for sec in lst:
    i=second_rank.index(sec)
    index_rank.append(i)
    
print(index_rank)
```

## 錯誤訊息
![123](https://user-images.githubusercontent.com/80198686/111860426-592ff100-8982-11eb-9e39-bbccaa0c335d.png)

## 問題描述
我的想法：將排序後的秒數排名的index，加到新的list並print出結果
問題：不知道為什麼 遇到相同的秒數就會print出一樣的index，想請問是哪裡出錯了嗎~?謝謝!

**Comment by TJ72** [comment]
因為`i = second_rank.index(sec)`會取出串列中第一次出現 sec 元素的 index，所以如果串列中有兩個 sec 元素的話，用`.index(sec)`就永遠都只能取道前面的 index。

**Comment by Viggochang** [comment]
@zoee22 若問題已被回答，請關閉問題
（使用方法參考學員須知中的[使用教學](https://www.notion.so/ccclub/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)）
