### ISSUE TITLE
[Week 4]字母拼圖

### ISSUE THREAD

**Issue by jimmy97332** [coding-coworking-club/python-spring-2021#199]
## 程式碼

```python
def char_puzzle(lst):
    puzzle = [False for i in range(26)]
    for word in lst:
        for c in word:
            puzzle[ord(c) - ord('a')] = True
    return ''.join([
        chr(ord('a') + index)
        for index, used in enumerate(puzzle)
        if used
    ])

char_puzzle(["apple", "bird", "apple"])
```

## 問題描述

請問一下 join裡面，index,後方的 used in enumerate(puzzle)  if used
used 是一種功能嗎
不太懂這段，試指enumerate(puzzle)中有用到的index嗎?

**Comment by TJ72** [comment]
used 是指`enumerate(puzzle)`中的 value 喔～這段 demo 程式碼中，凱文先用存著 26 個 False的串列 puzzle，然後用 for-loop 把出現字元對應位置的串列 puzzle 的元素存 True。最後回傳時用`enumerate(puzzle)`同時讀取串列的 index, value，如果 value 是 True 的話，就將 index 對應的英文字母放進`''.join([ ])`裡的串列中。程式碼中的 used 不是新的功能喔，只是凱文用來接 value(True/False) 的變數

**Comment by jimmy97332** [comment]
了解了，謝謝!
