### ISSUE TITLE
[Week 2] 小仔填志願

### ISSUE THREAD

**Issue by GingerSmolNeko** [coding-coworking-club/python-spring-2021#20]
## 提交連結

https://judge.ccclub.io/status/ffe4cc20c4d78c863c8ffb3032ba499c

## 程式碼

```python
a=input()  
b=input()

if b=="會計系" and int(a[0:2])+int(a[3:5])+int(a[6:8])+int(a[-5:-3])>=57 and int(a[0:2])==15:
    print(1)
elif b=="會計系":
    print(0)
    
if b=="公衛系" and int(a[3:5])+int(a[6:8])+int(a[-2:])>=38:
    print(1)
elif b=="公衛系":
    print(0)

if b=="經濟系" and int(a[-5:-3])+int(a[-2:])>=26 and int(a[6:8])==15:
    print(1)
elif b=="經濟系":
    print(0)
    
if b=="資工系" and int(a[3:5])+int(a[-2:])>=27 and int(a[6:8])==15:
    print(1)
elif b=="資工系":
    print(0)
```

## 錯誤訊息

<img width="357" alt="截圖 2021-03-05 下午12 11 49" src="https://user-images.githubusercontent.com/79833970/110066276-05cb7980-7dac-11eb-9d9c-63eea3dfa196.png">

## 問題描述

點選submit後出現Runtime error訊息，請問這指的是什麼地方出問題？
另外，丟去Jupyter Notebook跑是正常的。謝謝！

**Comment by hchbiggrass** [comment]
想想看，萬一輸入分數的時候不小心按了一些空格，會發生什麼事情?

**Comment by hadao02** [comment]
> 想想看，萬一輸入分數的時候不小心按了一些空格，會發生什麼事情?

Basically my code is same as above but it is always wrong with Chinese character like "SyntaxError: invalid character in identifier". How to deal with this problem?

**Comment by alvisyjchen** [comment]
@hadao02 發問可以另開 issue 提交必要資訊哦
