### ISSUE TITLE
[Homework 2] 小仔選配飼料

### ISSUE THREAD

**Issue by MichaelChou0806** [coding-coworking-club/python-spring-2021#203]
## 提交連結

https://judge.ccclub.io/status/88d4da25b22e6b48f5c5f6030e39cb3f
## 程式碼

```python
buy = [int(sum) for sum in input().split(" ")]
u = [int(sum) for sum in input().split(" ")]
v = [int(sum) for sum in input().split(" ")]

#buy [0: u和v至多量, 1: Protein含量須達, 2: Fat含量須達]
  #u [0: Protein量, 1: Fat量, 2: 價格]
  #v [0: Protein量, 1: Fat量, 2: 價格]


count_list = [0,0,0,0,0] #[0: P總量, 1: F總量, 2: u量, 3: v量, 4: 價格]


#把所有組合和計算結果列出, 放入 total 中 
total = []
for i in range(buy[0]):
    for j in range(buy[0]):
        count_list[0] = j*u[0] + i*v[0]    #此列第0格放: u 和 v 的 protein 量
        count_list[1] = j*u[1] + i*v[1]    #此列第1格放: u 和 v 的 fat 量
        count_list[2] = j                  #計算此列有多少 u
        count_list[3] = i                  #計算此列有多少 v
        count_list[4] = j*u[2] + i*v[2]    #計算此列總價
        total.append(count_list)           #將此列送至 total 的 list (之後來比較)
        count_list = [0,0,0,0,0]          #歸零，以利下一迴圈統計
#print(f"total1: {total}") #檢測用

#找 total 中，Protein 和 Fat 出量足夠者, 放入 total 2 中
total2 = []
for ii in range(len(total)):
    if total[ii][0] >= buy[1] and total[ii][1] >= buy[2]: 
        #找出Protein[0] 及 Fat[1] 大於購買條件 buy[1] 及 buy[2] 的子串
        total2.append(total[ii])
#print(f"total2: {total2}") #檢測用

#把 total2 的價格放到 price 中，並找最低價
price = []
for iii in range(len(total2)):
    price.append(total2[iii][4])
    price.sort()
#print(f"price: {price}") #檢測用

#找出 total 最低的價格的組合，放到ans裡面
ans =[]
for iiii in range(len(total2)):
    if total2[iiii][4] == price[0]:
        ans.append(total2[iiii])
#print(f"ans: {ans}") #檢測用

#最後答案
print(f"{ans[0][2]},{ans[0][3]}")
print(ans[0][4])
```

## 問題描述

QQ 心好累
一樣使用範例輸入/輸出都OK
但是 Runtime Error

我的解題思路是...

因題目有限制購買數量
所以可以先找出所有的排列組合  (i, j 迴圈)
找出所有排列組合的 Protein量/Fat量/價格 ...等資訊的組合

然後找出符合 protein / fat 所需量的組合 (ii 迴圈)

然後找出這些組合的價格 (iii 迴圈)

然後用最低價格找出 protein / fat 所需量的組合 (iiii迴圈) 

最後 print 出所需格式的答案

**Comment by kuolianyoyo** [comment]
我也是！
但有爬到別的同學問這樣的問題
然後助教回應是把split裡面的" "取消掉
改成只有split()就好
我改成這樣就AC了
可以試試看

**Comment by MichaelChou0806** [comment]
> 我也是！
> 但有爬到別的同學問這樣的問題
> 然後助教回應是把split裡面的" "取消掉
> 改成只有split()就好
> 我改成這樣就AC了
> 可以試試看

哈哈
改了變成 Wrong Answer
沒改是  Runtime Error

其實應該要加 " "
不然程式要怎麼知道怎麼切割 input 的值@@
我再研究看看，謝謝 :)

**Comment by TJ72** [comment]
嗯....不是這樣的
我建議還是用`input().split()`的方法，不要用`split(' ')`。如果是`split(' ')`只能針對一個空格進行字串的切割；但`split()`可以不限幾個空格，只要有出現空格就可以切割。具體的例子可以拿底下範例測資丟進程式跑一下就可以發現：
```
# 這三行數字後面都是有空格的
10 7 8    
2 3 10    
5 1 7     
```
如果用`split()`可以解決 Runtime Error 的問題， WA 可能就是程式其他部分運算上的問題了，加油～

**Comment by MichaelChou0806** [comment]
最後把第一組迴圈 (i, j 迴圈)
的 i 和 j 全部對調就 ok 了....
外層作 u 的計算
內層作 v 的計算
原來這樣會有差哦? (範例沒差QQ)
感覺蝦矇到的答案，有點不踏實 QQ

**Comment by TJ72** [comment]
> 最後把第一組迴圈 (i, j 迴圈)
> 的 i 和 j 全部對調就 ok 了....
> 外層作 u 的計算
> 內層作 v 的計算
> 原來這樣會有差哦? (範例沒差QQ)
> 感覺蝦矇到的答案，有點不踏實 QQ

我猜....可能跟題目要求比較的順序有關(最小化購買金額→(u + v大的)→u 較小的)，不過我沒有全部看 code 運算的過程所以我也不知道會差在哪，不過總之恭喜啦
