### ISSUE TITLE
[Homework 2] 小仔選配飼料

### ISSUE THREAD

**Issue by jimmy97332** [coding-coworking-club/python-spring-2021#207]
## 提交連結

https://judge.ccclub.io/status/dbf6ccbb8884c87726b66c01f4cba5f9
## 程式碼

```python
#配飼料
X, A, B = map(int, input().split())
a1, b1, m1 = map(int, input().split())
a2, b2, m2 = map(int, input().split())
cost=[]
cost1=[]
money = X*m1  #紀錄所有滿足營養標準及不超過X的u,v解及所需成本
amount = 0    #紀錄u+v總量
uvariable = X
vvariable = 0
for u in range(X+1):
  for v in range(X+1-u):  #range這樣設的話u+v就不會超過X
    #cost.append(u*m1 + v*m2)#檢查
    if (u*a1 + v*a2 >= A) and (u*b1 + v*b2 >= B):
      #cost1.append(int(u*m1 + v*m2))##檢查    
      if (u*m1 + v*m2) < money:#只放最佳解，找總金額最小
        uvariable = u
        vvariable = v
        money = u*m1 + v*m2
        amount = u+v
        
      elif (u*m1 + v*m2) == money:   
        if (u+v) > amount:      #找總數量最大
          uvariable = u
          vvariable = v
          money = u*m1 + v*m2
          amount = u+v
        elif (u+v) == amount:  
          if u < uvariable:  
            uvariable = u
            vvariable = v
            money = u*m1 + v*m2
            amount = u+v
          else:
            continue
        else:
          continue
      else:
        continue       
#print(cost)#檢查  
#print(cost1)#檢查 

print(f"{uvariable},{vvariable}")
print(int(money))  
```

## 錯誤訊息

Wrong Answer
## 問題描述

跑出來是對的輸出，
uvariable = u
vvariable = v
money = u*m1 + v*m2
amount = u+v
若有更小的money就取代
用if-elif向下若money相同，比amount大的，向下若amount相同，比u較小的
想不到錯誤
麻煩大家幫我解惑了~

**Comment by jeffery12697** [comment]
要把程式碼貼好喔～

**Comment by jimmy97332** [comment]
> 要把程式碼貼好喔～

不好意思，已修正了~

**Comment by jeffery12697** [comment]
u+v 還是有可能相同，你沒有比到 u 較小的部分
這個題目只要找最優解，所以其實不用把每個符合的數據都存起來
寫個 pseudocode 給你，可以改改看～
```
目前最優情況的變數
for u in range(x+1):
    for v in range(x+1-u):
       如果 u v 符合條件
           如果有比目前最優情況的變數
               更換目前最優情況的變數成u v

輸出目前最優情況的變數
```

**Comment by jimmy97332** [comment]
> u+v 還是有可能相同，你沒有比到 u 較小的部分
> 這個題目只要找最優解，所以其實不用把每個符合的數據都存起來
> 寫個 pseudocode 給你，可以改改看～
> 
> ```
> 目前最優情況的變數
> for u in range(x+1):
>     for v in range(x+1-u):
>        如果 u v 符合條件
>            如果有比目前最優情況的變數
>                更換目前最優情況的變數成u v
> 
> 輸出目前最優情況的變數
> ```

謝謝助教!，我已改成只放最佳解了，並考慮u，但還是有WA，不知道哪裡出錯了

**Comment by jeffery12697** [comment]
你的money的初始值設太小ㄌ，如果所有組合都超過那個價錢，過程中就不會被替換到

**Comment by jimmy97332** [comment]
> 你的money的初始值設太小ㄌ，如果所有組合都超過那個價錢，過程中就不會被替換到

謝謝助教，我改成99999就可以了，但我查了一下，'inf'是不是只能搭配float，不能用int??
用99999感覺不是一個好的寫法。

**Comment by jeffery12697** [comment]
應該沒關係 int 跟 float 還是可以比較，所以寫成無限大也是可

**Comment by Viggochang** [comment]
@jimmy97332 若問題已被回答，請關閉此問題喔
（使用方法參考學員須知中的[使用教學](https://www.notion.so/ccclub/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)）
