### ISSUE TITLE
[Homework 2] 小仔養蛋雞I

### ISSUE THREAD

**Issue by nelly0421** [coding-coworking-club/python-spring-2021#208]
## 提交連結
https://judge.ccclub.io/status/947569d68f5ba1212b9cceef246dca74

## 程式碼

```python
i,x0,T,L=[int(i) for i in input().split()]
if (x0-1.5*0.01)<(L*0.01):
    t=L
else:
    t=1.5    
rr=i*(x0-t)*0.01
if int(rr)!=rr:
    rr=int(rr)+1    
count=rr
v=x0-t
for f in range(2,T+1):
    v=v-(1+0.5*f)
    if v*0.01<L*0.01:
        v=L
    else:
        v=v
    s=i*v*0.01
    if int(s)!=s:
        s=int(s)+1
    count=count+s
print(int(count))
```

## 問題描述

我測試了所有範例都得到正確的數值，想請問我是哪個部分出現問題呢?

**Comment by hchbiggrass** [comment]
其實你的第2行並沒有作用喔

**Comment by nelly0421** [comment]
> 其實你的第2行並沒有作用喔

所以是因為第二行的關係影響到下面整個程式嗎?還是只是第二行是多寫的

**Comment by hchbiggrass** [comment]
你寫的邏輯是對的，但是第二行的語法錯了

**Comment by nelly0421** [comment]
[](url)https://judge.ccclub.io/status/38aa202f1fa4347d7702782f227d3a3b
我將變數X0改成X，然後If那行稍作修改還是顯示錯誤，想請問其他地方還有什麼我沒有致意到的問題嗎?
還請助教幫忙解答，謝謝~

**Comment by hchbiggrass** [comment]
舊的程式碼和新的程式碼的效果完全一樣，但舊的比較精簡，所以舊的比較好。雖然你改了很多，但問題還是出在第二行喔，跟四則運算有關。
