### ISSUE TITLE
[General] 檢查日期

### ISSUE THREAD

**Issue by j84022814** [coding-coworking-club/python-spring-2021#209]
## 提交連結

https://judge.ccclub.io/status/6ee61fd6e55d37ca50da809b66d4ea8f
## 程式碼

```python
while True:
    s=input().split(', ')
    big=[1,3,5,7,8,10,12]
    small=[4,6,9,11]
    if s=="end":
        break
    else:
        if int(s[0])<=0 or int(s[1])<=0 or int(s[2])<=0:
            print("error")
        elif int(s[1])>12:
            print('error')
        elif int(s[1]) in big and int(s[2])>31:
            print('error')
        elif int(s[1]) in small and int(s[2])>30:
            print('error')
        elif int(s[1])==2 and int(s[2])>28:
            print('error')
        else:
            print('OK')
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/79981947/111900310-c28c2e80-8a6c-11eb-8748-e7ae9a7a3216.png)

## 問題描述

不知道為何已經符合break的條件了 他還是會繼續跑下去然後說我的end不符合int
請麻煩助教解惑 謝謝

**Comment by TJ72** [comment]
因為用`s.split()`的話，不管括號裡用什麼字元做切割，輸出的都會是一個串列。所以才不會達到 break 的條件。

**Comment by Viggochang** [comment]
@j84022814  若問提已被回答，請關閉問題
（使用方法參考學員須知中的[使用教學](https://www.notion.so/ccclub/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)）

**Comment by j84022814** [comment]
不好意思忘記close issue了
