### ISSUE TITLE
[General] 8-1: 乘積最大值

### ISSUE THREAD

**Issue by jennyliu12** [coding-coworking-club/python-spring-2021#210]
## 提交連結

https://judge.ccclub.io/status/a2c068a616d34145a1f696e42425d7ab

## 程式碼

```python
def max_mul(lst):
    if len(lst) == 1:
        return(lst[0])
        
    else:
        for i in range(len(lst) - 1):
            Sum = int(lst[i]) * int(lst[i+1])
            if int(lst[i]) * int(lst[i+1]) > Sum:
                Max = int(lst[i]) * int(lst[i+1])
            else:
                Max = Sum 
        
        return Max

lst = input().split(' ')
print(max_mul(lst))

```

## 問題描述

在Jupyter Notebook 上跑都能跑得出答案，但不知道為什麼在Judge裡面提交之後都一直顯示Wrong Answer，還請助教幫我解惑，謝謝！

**Comment by TJ72** [comment]
我感覺問題應該是出在迴圈裡面，比大小的過程好像錯了
```python
for i in range(len(lst) - 1):
    Sum = int(lst[i]) * int(lst[i+1])
    if int(lst[i]) * int(lst[i+1]) > Sum:
        Max = int(lst[i]) * int(lst[i+1])
    else:
        Max = Sum 
```

**Comment by Viggochang** [comment]
你的 `Sum` 要表示的是 `Max` 的起始值對吧
那你應該要把 `Sum = int(lst[i]) * int(lst[i+1])` 放到迴圈之外
如果在迴圈內，你先執行了 `Sum = int(lst[i]) * int(lst[i+1])`
則 ` int(lst[i]) * int(lst[i+1])` 會跟 `Sum` 一樣
因此你的條件 `int(lst[i]) * int(lst[i+1]) > Sum` 永遠無法成立
也就無法更新Max

另外，因為python會辨別大小寫，所以你的變數命名為 `Sum`雖然與特殊字 `sum` 不同
但使用上還是容易搞混，可以想想看有沒有別的命名方式
