### ISSUE TITLE
[Week 3] 比賽排名

### ISSUE THREAD

**Issue by Molly995** [coding-coworking-club/python-spring-2021#215]
## 提交連結

https://judge.ccclub.io/status/b744eedd2e102083444d007cfd1f8758

## 程式碼

```python
##把輸入的字串轉成整數化的lst
lst = [int(num) for num in input().split()]
lst_sorted = sorted(lst)  ##將排序過的list重新命名

##給指令印出順序
for i in range(len(lst)): ##在lst的每個i中
    order = lst_sorted.index(lst[i])  ##從lst_sorted中找排序
    print(order, end=" ")             ##把index輸出
    lst_sorted[order] = "a"           ##為避免重複輸出同一個index，把輸出過的改成a

```

## 問題描述

助教好～
我成功的避開重複輸出位置的問題了，但結果還是錯的。

我發現我好像不太懂問題想要問的東西，譬如範例2中：
輸入：9 8 3 3 5 4 1 5 6 0 7 5 0 5 0
輸出答案：9 12 14 6 2 3 5 4 7 11 13 8 10 1 0
以我對題目的理解，秒數排序後為：[0, 0, 0, 1, 3, 3, 4, 5, 5, 5, 5, 6, 7, 8, 9]
第一個"9"的排序為什麼在答案裡是"9"呢？秒數9不是應該是最後一名，排序應為14才對？

是我誤會題目的意思了嗎ˊˋ？

**Comment by hchbiggrass** [comment]
索引值為9、12、14的只需要0秒，因此輸出時排在最前面。你應該是累了，早點休息吧。

**Comment by Molly995** [comment]
助教好，謝謝助教的關心，但我人在國外有時差，所以現在是白天唷XD

我發現是我搞反了XD
改完之後已得到AC，感謝助教的解答
