### ISSUE TITLE
[Homework 1] 吉吉整理書

### ISSUE THREAD

**Issue by Lienwuuu** [coding-coworking-club/python-spring-2021#22]
## 提交連結

https://judge.ccclub.io/status/ad8b55bbc8ded5f4bbd33620ac5801b6

## 程式碼

```python
num = input()
num_list = num.split(' ')
num_list = [ int(i) for i in num_list ]
num_list.sort()
print(num_list)
```

## 問題描述

在jupyter上測試兩個sample可行
但提交judge卻不正確

我的想法是用.split()將input的字串切成list
再將list中的字串轉為整數
再用.sort()排列順序後輸出

請問有哪裡是錯誤的嗎?
感謝!

**Comment by andykuo0956** [comment]
（我不是助教，所以可能沒辦法幫到ㄋ
這樣的話print出是list，但系統要求的是int加上空格喔！希望可以幫到ㄋ

**Comment by Lienwuuu** [comment]
> （我不是助教，所以可能沒辦法幫到ㄋ
> 這樣的話print出是list，但系統要求的是int加上空格喔！希望可以幫到ㄋ

哈囉！感謝你的回答～
我把print那行改為:

```python
for i in num_list:
    print(i, end=" " )
```
的確在judge上就變成正確了
不過我不懂 "系統要求的是int加上空格" 這個部分要怎麼知道呢?
我又回去認真看了幾遍題目還是看不出來...

**Comment by TJ72** [comment]
因為輸出 list和輸出 int加上空格是不一樣的啊～可以試著在 Jupyter上試試看喔！

**Comment by Lienwuuu** [comment]
> 因為輸出 list和輸出 int加上空格是不一樣的啊～可以試著在 Jupyter上試試看喔！

眼睛業障重
居然沒發現他們長不一樣
剛恍然大悟了哈哈哈
感謝提醒！
