### ISSUE TITLE
[General] 小明去爬山

### ISSUE THREAD

**Issue by sherrylin-github** [coding-coworking-club/python-spring-2021#220]
## 提交連結

https://judge.ccclub.io/status/6a03f1d3eb572ee48446fa8abead4908
## 程式碼

```python
#192302 小明去爬山
route = int(input())
high_all = []
for i in range (route):
    seg = int(input())
    restlen = 0
    toiletlen = 0
    high = 0
    for j in range (seg):
        a = input()
        b = a.split(',')
        c = int(b[0])
        high += c
        restlen += 100
        toiletlen += 100
        if high != (float('inf')):
            if restlen > 300:
                high = (float('inf'))
            else:
                if b[1] == 'True':
                    restlen = 0
                    if toiletlen > 300:
                        high = (float('inf'))
                    else:
                        if b[2] == 'True':
                            toiletlen = 0
                else:
                    if toiletlen > 300:
                        high = (float('inf'))
                    else:
                        if b[2] == 'True':
                            toiletlen = 0
    high_all.append(high)
    
if min(high_all) == float('inf'):
    print('stay at home')
else:
    print(high_all.index(min(high_all)))
```

                
                
        
## 問題描述

使用judge上的sample input都有得到跟sample out一樣的答案，但提交judge系統卻得到wrong answer，想知道我有哪裡沒有考慮周全，非常感謝！

**Comment by TJ72** [comment]
感覺題目說 "距離不能超過 300 公尺" ，那如果累計 300 公尺時都沒有遇到下一個廁所(或是涼亭)的話，那兩個廁所(涼亭)間的距離就一定超過 300 公尺了。所以我覺得問題應該是在`if restlen > 300:` &` if toiletlen > 300:`兩個條件上

BTW 下次發 GitHub Issue 請注意程式碼格式，細節可以參[ GitHub 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)

**Comment by sherrylin-github** [comment]
> 感覺題目說 "距離不能超過 300 公尺" ，那如果累計 300 公尺時都沒有遇到下一個廁所(或是涼亭)的話，那兩個廁所(涼亭)間的距離就一定超過 300 公尺了。所以我覺得問題應該是在`if restlen > 300:` &` if toiletlen > 300:`兩個條件上
> 
> BTW 下次發 GitHub Issue 請注意程式碼格式，細節可以參[ GitHub 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)

感謝回答以及格式提醒，已經修正好格式，程式依據您的建議修改後也被judge接受了，真的非常感謝！
