### ISSUE TITLE
[Homework 2] 小仔養蛋雞II

### ISSUE THREAD

**Issue by GaryLu1994** [coding-coworking-club/python-spring-2021#221]
## 提交連結

https://judge.ccclub.io/status/eec90d11b6dccf7d52e22c6f05b6a68a

## 程式碼

lst = [int(i) for i in input().split()]
i = lst[0]
X0 = lst[1]
T = lst[2]
L = lst[3]
D = lst[4]

iXt=[]

for j in range(1,T+1):
    Xj = (-0.25)*(j**2) - 1.25*j + X0
    if(Xj<L):
        Xj = L
    
    iXj = i * Xj * 0.01
    
    if (iXj%1!=0):
        iXj = int(iXj)+1
    else:
        iXj = int(iXj)
    
    iXt.append(iXj)

total = 0
for j in range(len(iXt)):
    total += iXt[j]

Max = total

iXt_copy = []
index = -1
for k in range(len(iXt)-D):    
    iXt_copy = iXt[:]
    total = 0
    
    if (D==1):
        iXt_copy[k] = 0
        iXt_copy[k+1] = 90
        if(iXt_copy[k+1]<90):
            iXt_copy[k+1] = L
        for j in range(k+2, T):
            iXt_copy[j] = iXt_copy[j-1] - (1 + 0.5 * j)
            if(iXt_copy[j]<L):
                iXt_copy[j] = L
            iXt_copy[j] = iXt_copy[j] * i * 0.01
        iXt_copy[k+1] = iXt_copy[k+1] * i * 0.01
    
    elif(D==2):
        iXt_copy[k] = 0
        iXt_copy[k+1] = 0
        iXt_copy[k+2] = 90
        if(iXt_copy[k+2]<L):
            iXt_copy[k+2] = L
        for j in range(k+3, T):
            iXt_copy[j] = iXt_copy[j-1] - (1 + 0.5 * j)
            if(iXt_copy[j]<L):
                iXt_copy[j] = L
            iXt_copy[j] = iXt_copy[j] * i * 0.01
        iXt_copy[k+2] = iXt_copy[k+2] * i * 0.01
        
    elif(D==3):
        iXt_copy[k] = 0
        iXt_copy[k+1] = 0
        iXt_copy[k+2] = 0
        iXt_copy[k+3] = 90
        if(iXt_copy[k+3]<L):
            iXt_copy[k+3] = L
        for j in range(k+4, T):
            iXt_copy[j] = iXt_copy[j-1] - (1 + 0.5 * j)
            if(iXt_copy[j]<L):
                iXt_copy[j] = L
            iXt_copy[j] = iXt_copy[j] * i * 0.01
        iXt_copy[k+3] = iXt_copy[k+1] * i * 0.01
        
    elif(D==4):
        iXt_copy[k] = 0
        iXt_copy[k+1] = 0
        iXt_copy[k+2] = 0
        iXt_copy[k+3] = 0
        iXt_copy[k+4] = 90
        if(iXt_copy[k+4]<L):
            iXt_copy[k+4] = L
        for j in range(k+5, T):
            iXt_copy[j] = iXt_copy[j-1] - (1 + 0.5 * j)
            if(iXt_copy[j]<L):
                iXt_copy[j] = L
            iXt_copy[j] = iXt_copy[j] * i * 0.01
        iXt_copy[k+4] = iXt_copy[k+4] * i * 0.01
        
    elif(D==5):
        iXt_copy[k] = 0
        iXt_copy[k+1] = 0
        iXt_copy[k+2] = 0
        iXt_copy[k+3] = 0
        iXt_copy[k+4] = 0
        iXt_copy[k+5] = 90
        if(iXt_copy[k+5]<L):
            iXt_copy[k+5] = L
        for j in range(k+6, T):
            iXt_copy[j] = iXt_copy[j-1] - (1 + 0.5 * j)
            if(iXt_copy[j]<L):
                iXt_copy[j] = L
            iXt_copy[j] = iXt_copy[j] * i * 0.01
        iXt_copy[k+5] = iXt_copy[k+5] * i * 0.01

            
    for j in range(len(iXt_copy)):    
        if (iXt_copy[j]%1!=0):
            iXt_copy[j] = int(iXt_copy[j])+1
        else:
            iXt_copy[j] = int(iXt_copy[j])
    
    for j in range(len(iXt_copy)):
        total += iXt_copy[j]

    if (total>Max):
        index = k+1
        Max = total
    
print(str(index) + ',' + str(Max))

## 問題描述

我是先利用前一題的想法
把沒有換羽毛的產蛋量設為Max

然後依照給予換羽毛的日期長度做判斷

若D=1
則我用迴圈跑
去算出分別在不同日期換羽毛的話
所得到的產蛋量

若是產蛋量大於Max
則重新設定Max

我在這邊有幾點想問：
1. 題目中提到換羽毛時，Xi為0％，隔天的產蛋量為90%，若是90小於給定的L，那是否也需要重新指定為L？
（我在題目中有重新指定，但是仍然錯誤，不知道是不是有哪個地方沒有考慮到）
2. 在判斷的部分我目前想不到什麼比較好的寫法，不知道助教是否能提供一些想法

**Comment by hchbiggrass** [comment]
1. 如果當天的產蛋率低於L，就當作是L
2. 你目前的寫法有點太土法煉鋼了，如果D=10000的話要怎麼辦?建議你先用紙筆計算一次題目提供的測試資料，手算的過程中你會感覺到有某些東西會重複出現，這樣至少可以先解決跑不了超過5天的問題

**Comment by GaryLu1994** [comment]
> * 如果當天的產蛋率低於L，就當作是L
> * 你目前的寫法有點太土法煉鋼了，如果D=10000的話要怎麼辦?建議你先用紙筆計算一次題目提供的測試資料，手算的過程中你會感覺到有某些東西會重複出現，這樣至少可以先解決跑不了超過5天的問題

提交連結：
https://judge.ccclub.io/status/a784970cf24de4598525ae6edabe4742

程式碼：

lst = [int(i) for i in input().split()]
i = lst[0]
X0 = lst[1]
T = lst[2]
L = lst[3]
D = lst[4]

iXt=[]

for j in range(1,T+1):
    Xj = (-0.25)*(j**2) - 1.25*j + X0
    if(Xj<L):
        Xj = L
    
    iXj = i * Xj * 0.01
    
    if (iXj%1!=0):
        iXj = int(iXj)+1
    else:
        iXj = int(iXj)
    
    iXt.append(iXj)

total = 0
for j in range(len(iXt)):
    total += iXt[j]

Max = total

iXt_copy = []
index = -1
for k in range(len(iXt)-D):    
    iXt_copy = iXt[:]
    total = 0
    

    for j in range(D):
        iXt_copy[k+j] = 0
    iXt_copy[k+D] = 90
    if(iXt_copy[k+D]<90):
        iXt_copy[k+D] = L
    
    for j in range(k+D+1, T):
        iXt_copy[j] = iXt_copy[j-1] - (1 + 0.5 * j)
        if(iXt_copy[j]<L):
            iXt_copy[j] = L
        iXt_copy[j] = iXt_copy[j] * i * 0.01
    
    iXt_copy[k+D] = iXt_copy[k+D] * i * 0.01
            
    for j in range(len(iXt_copy)):    
        if (iXt_copy[j]%1!=0):
            iXt_copy[j] = int(iXt_copy[j])+1
        else:
            iXt_copy[j] = int(iXt_copy[j])
    
    for j in range(len(iXt_copy)):
        total += iXt_copy[j]

    if (total>Max):
        index = k+1
        Max = total
    
print(f'{index},{Max}')

問題描述：
我修正了土法煉鋼的部分
但是仍然得到WA
不知道自己是哪個地方沒有思考完全

**Comment by hchbiggrass** [comment]
建議自己配一些數字用手算並搭配[trace code](http://pythontutor.com/visualize.html#mode=display)檢查自己的步驟，尤其是要換羽的部分
