### ISSUE TITLE
[Week 4] 打字機

### ISSUE THREAD

**Issue by CKJK47** [coding-coworking-club/python-spring-2021#225]
## 提交連結

https://judge.ccclub.io/status/6395bf8d08528a7139c6764680063791
## 程式碼

```python
s = str(input())

while (s[0] == "+" or s[0] == "-" or s[0] == "*"):
    s = s[1:]
    if len(s) == 0:
        break

ans = []
for i in range(len(s)):
    if s[i] == "+":
        ans.append(ans[-1])
    elif s[i] == "-":
        ans.remove(ans[-1])
    elif s[i] == "*":
        ans = ans * 2
    else:
        ans.append(s[i])

print("".join(ans))
```

## 錯誤訊息

<img width="747" alt="截圖 2021-03-23 下午6 49 54" src="https://user-images.githubusercontent.com/79802408/112135269-93122900-8c08-11eb-9db7-3b79cfa5fc1e.png">

## 問題描述

1. 我先檢查第一個字母是不是+-*，如果是的話就捨棄，檢查到s的長度變為0就跳出回圈
2. 一樣對s跑回圈檢查每一個字，如果遇到"+"就用append、"-"就用remove、"*"就複製一次，最後一個else裡面包含所有不是+-*的狀況就append在ans的list裡面
3. 最後輸出轉回字串
4. 試過測資都對，卻回報Wrong answer，不知道問題是不是出在單純只有+-*的狀況下無法輸出對的答案？

**Comment by hchbiggrass** [comment]
確認一下remove的功能是否跟你想像的一樣喔
