### ISSUE TITLE
[General] 二進位

### ISSUE THREAD

**Issue by jennifer090** [coding-coworking-club/python-spring-2021#229]
## 提交連結
https://judge.ccclub.io/status/63d8cf6895deb976fc9efd9f840328c6

## 程式碼

```python
def to_binary(n):
    list1=[]
    while n!=1:
        s=n%2
        if len(list1)!=0:
            if s!=list1[-1]:
                list1.append(s)
            n=n//2
        else:
            list1.append(s)
            n=n//2
    if n==1:
        list1.append(1)
        ans=list1[::-1]    
    return ans

```

## 問題描述
我重新改過了!但是還使wrong answer,可是我自己多事了幾個sample並沒有問題，想請助教在幫忙看一看，謝謝!!

**Comment by TJ72** [comment]
這題也是只能交一個函數，外面不能有東西，`lst = list()`是要放在 `def to_binary(num)`裡面沒錯喔～這題應該不要用遞迴比較好做
btw 感覺你有一點沒弄清楚遞迴的正確用法，遞迴的精神是在函數裡面運算時有必要時 call 自己幫忙運算，所以函式名稱一定會是一樣的喔～像底下這個費波那契數列的例子，函式裡面在呼叫自己幫忙時一樣是呼叫 fibonacci ，不會是像妳上面的 code 裡面呼叫一個 f function
```python
def fibonacci(n):
    if n == 1:
        return 1
    elif n == 2:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)
```

**Comment by jennifer090** [comment]
[https://judge.ccclub.io/problem/193202](url)
def to_binary(n):
    list1=[]
    while n!=1:
        s=n%2
        if len(list1)!=0:
            if s!=list1[-1]:
                list1.append(s)
            n=n//2
        else:
            list1.append(s)
            n=n//2
    if n==1:
        list1.append(1)
        ans=list1[::-1]    
    return ans


> 這題也是只能交一個函數，外面不能有東西，`lst = list()`是要放在 `def to_binary(num)`裡面沒錯喔～這題應該不要用遞迴比較好做
> btw 感覺你有一點沒弄清楚遞迴的正確用法，遞迴的精神是在函數裡面運算時有必要時 call 自己幫忙運算，所以函式名稱一定會是一樣的喔～像底下這個費波那契數列的例子，函式裡面在呼叫自己幫忙時一樣是呼叫 fibonacci ，不會是像妳上面的 code 裡面呼叫一個 f function
> 
> ```python
> def fibonacci(n):
>     if n == 1:
>         return 1
>     elif n == 2:
>         return 1
>     else:
>         return fibonacci(n-1) + fibonacci(n-2)
> ```
喔喔這邊理解了!!謝謝助教!但是我改過之後好像有小地方有問題，還是wrong answer,想請助教幫忙看一下哪裡有問題，謝謝!

**Comment by TJ72** [comment]
因為不管最後 n 是不是剩 1，最後回傳的 ans 串列都要順序反轉吧

**Comment by jennifer090** [comment]
解決了感謝助教!
