### ISSUE TITLE
[General] 計程車費用

### ISSUE THREAD

**Issue by nick30924** [coding-coworking-club/python-spring-2021#230]
## 提交連結

https://judge.ccclub.io/status/5e486e0f24875361617bdfba2f228741

## 程式碼

```python
taxi_fare = [int(f) for f in input().split()]
position = [int(p) for p in input().split()]
p1 = int(position[0])
p2 = int(position[1])
E = [0]
W = [0]
N = [0]
S = [0]

while True:
    root = [r for r in input().split()]
    if "0" in root:
        break
    else:
        if root[0] == "E":
            E.append(int(root[1]))
            p1 += int(root[1])
        elif root[0] == "W":
            W.append(int(root[1]))
            p1 -= int(root[1])
        elif root[0] == "N":
            N.append(int(root[1]))
            p2 += int(root[1])
        elif root[0] == "S":
            S.append(int(root[1]))
            p2 -= int(root[1])

total = (sum(E) + sum(W) + sum(N) + sum(S)) * taxi_fare[0] + (max(E) + max(W) + max(N) + max(S)) * taxi_fare[1]
print(str(p1) + " " + str(p2))
print(total) 
```

## 問題描述

我經過測資得到了正確的答案，但貼到judge系統上卻是Wrong Answer，不知道自己哪裡沒有寫對...

**Comment by TJ72** [comment]
座標(p1, p2)變得方向跟題目的設定好像不太一樣喔～建議可以重看一次題目，確認東、南、西、北方向分別代表 p1, p2哪個方向的移動

**Comment by nick30924** [comment]
不好意思，我看了很久還是沒有發現甚麼端倪，p1為x軸移動(東+西-)，p2為y軸移動(南-北+)，如果有設定不對答案應該也會反應出來，還是我的符號哪邊寫錯了，可以再麻煩給我一點點提示嗎QQ

**Comment by TJ72** [comment]
> 不好意思，我看了很久還是沒有發現甚麼端倪，p1為x軸移動(東+西-)，p2為y軸移動(南-北+)，如果有設定不對答案應該也會反應出來，還是我的符號哪邊寫錯了，可以再麻煩給我一點點提示嗎QQ

抱歉～是我看錯題目 orz
因為沒辦法保證行駛紀錄不會有像是`'N 0'`或是 `'W 0'`之類的，如果用 `.split()`完之後的串列作`if "0" in root:`的條件檢查很有可能會誤算，所以我建議用`input()`判斷完之後，不是`'0'`再做 split

**Comment by nick30924** [comment]
喔喔!原來如此!完全忘記0出現的場合也有可能是 N 0這種可能了，虧我還為了E串列中沒有加入元素時取不出最大值而加入一個0到裡頭，我再修改一下，謝謝助教
