### ISSUE TITLE
[Homework 2] 小仔養蛋雞I

### ISSUE THREAD

**Issue by ycc70335** [coding-coworking-club/python-spring-2021#232]
## 提交連結

https://judge.ccclub.io/status/27141ce66f563c2ded2114f17f772a74

## 程式碼

```python
lst= [int(num) for num in input().split(" ")]

if 1000 >= lst[0] >= 100:
    i = lst[0]
if 100 >= lst[1] > 1:
    x0 = lst[1]
if 100 >= lst[2] >= 5:  #Hint裡面T=3，跟初始條件不符
    T = lst[2]
if x0 >= lst[3] >= 1:    
    L = lst[3]
cnt = 0
d_rate = 0 #sum of decrease rate

for t in range(1, T+1):
    d_rate += 1 + 0.5*t
    xt = x0 - d_rate
    if xt < L:
        xt = L
    cnt += i * xt * 0.01 
    if cnt % 1 != 0:
        cnt = cnt // 1 + 1
    
print(int(cnt))
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/40969975/112237994-c394aa00-8c7e-11eb-931c-7f9d7dbac025.png)

## 問題描述

測資都正確(不包含Hint裡面T=3，跟初始條件不符的部分)，
出現runtime error，想請問可能是哪裏出了問題~

**Comment by hchbiggrass** [comment]
先把Hint的測資弄對再說吧

**Comment by tcwang76** [comment]
其實你寫的程式邏輯都是對的，但是如果把對於題目的初始限制寫死了，
i、x0、T、L 就可能成為尚未定義的變數噢? 
試著把前面的限制拿掉看看吧，應該就會對囉!
