### ISSUE TITLE
[Week 4] 秘密紙條

### ISSUE THREAD

**Issue by ghFlo** [coding-coworking-club/python-spring-2021#233]
## 提交連結

https://judge.ccclub.io/status/b3fbab1ecb09e923cdff669bc5da754b
## 程式碼

```python
note=[]
while True:
    note.append(input())
    if note[-1]=="end":
        break

note.pop()

for i in note:
    for j in range(len(i)):
        print((ord(i[j])+219)*2, end=" ")
        if j== (len(i)-1):
            print()

```

## 錯誤訊息

測試無錯誤訊息
提交為WA

## 問題描述

有實際測試過，也有跟課堂上分享的寫法做過比較，
不確定是否跟最後的換行有關？
還是要寫成一行的最後一個字 print((ord(i[j])+219)*2) 這樣比較好？

**Comment by hchbiggrass** [comment]
連結要貼submit的，而不是題目本身的

**Comment by ghFlo** [comment]
已修正 謝謝提醒

**Comment by TJ72** [comment]
是輸出格式的問題喔～可以參考 #189 ～
btw 修正後的提交連結還是不對，下次po GitHub Issue 請注意。細節請參考[ GitHub 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)。

**Comment by ghFlo** [comment]
了解了！ 我沒有找到closed section，抱歉重複發問。
現在發現更多可以先參考的地方了，謝謝。

**Comment by TJ72** [comment]
沒關係的～歡迎發問～即使是重複的問題我們也可以很快地給你 reference
