### ISSUE TITLE
[General] 二進位

### ISSUE THREAD

**Issue by CKJK47** [coding-coworking-club/python-spring-2021#235]
## 提交連結

https://judge.ccclub.io/status/310cd3e6ba1dfcd7db23e53d6be1ad99
## 程式碼

```python
def to_binary(n):
    binary_num = format(n, "b")
    num_list = []
    for i in range(len(binary_num)):
        if binary_num[i] == binary_num[i - 1]:
            continue
        num_list.append(binary_num[i])
    return [int(num) for num in num_list]
```

## 錯誤訊息

<img width="981" alt="截圖 2021-03-24 下午6 47 01" src="https://user-images.githubusercontent.com/79802408/112297992-7beb3e00-8cd1-11eb-9af7-81cb59a5d691.png">

## 問題描述

1. 用format(n, ""b)取得二進位的數字部分(像是測資1的16就轉成10000)
2. 把10000一個一個取出，如果跟前一個一樣就不加入num_list
3. 最後return一個裡面全部轉成int的串列
4. 測資都對但是顯示Wrong answer，不確定是哪邊出問題，或是題目理解錯誤

**Comment by TJ72** [comment]
題目理解沒錯，但 for-loop 裡面 if 判斷式的 index 出了一點問題

**Comment by CKJK47** [comment]
問題已解決，謝謝！
