### ISSUE TITLE
[General] 助教業績統計

### ISSUE THREAD

**Issue by CKJK47** [coding-coworking-club/python-spring-2021#236]
## 程式碼

```python
performance = [int(num) for num in input().split(" ")]
assistant = []

while performance != [0]:
    assistant.append(sum(performance))
    performance = [int(num) for num in input().split(" ")]
    
print(assistant.index(max(assistant)) + 1, max(assistant))
```

## 問題描述

1. 我自己用了一個土法煉鋼的方式，最後印出最大值的index以及最大值
2. 關於本題我猜測題目希望我們用到enumerate的功能，但是上課中只提到在for迴圈內使用，這樣會印出每一個index，無法只印出最大值。因此想詢問如何使用enumerate只印出最大值。

**Comment by TJ72** [comment]
我覺得這題不太適合用 enumerate 耶！如果真的要讓程式更有效率的話，可以直接在 while-loop 迴圈裡輸入完第 i 筆之後，直接比較第 i 筆的助教業績和前面 i-1 筆的業績最高的誰比較高，然後記錄下當前 i 筆資料業績最高的成績和他的編號，這樣持續到迴圈結束直接輸出，這樣效率應該會比`.index()`或`enumerate`還要好一些

**Comment by CKJK47** [comment]
按照助教的方式也解出來了，謝謝！
