### ISSUE TITLE
[Homework 2] 小仔養豬

### ISSUE THREAD

**Issue by janna0329** [coding-coworking-club/python-spring-2021#238]
## 程式碼

```python

```

## 錯誤訊息

Wrong answer

## 問題描述

已經用測資試過了，都是正確的
但交到批改系統上都是wrong answer

想法:
1.先將母豬總數和小豬總數算出
2.將有母豬的位置存入list中
3.確認在母豬身邊的小豬數量
4.確認溫度是否適合

**Comment by janna0329** [comment]
> ## 提交連結
https://judge.ccclub.io/status/323c36dd651f191fe0c53467e309da15
> ## 程式碼
information=input().split(" ")
x=int(information[0])
y=int(information[1])
r=int(information[2])
d=int(information[3])
num_mom=0
num_kid=0
cartesian_coordinates=[]

for i in range(y+1):
    cartesian_coordinates.append([int(num) for num in input().split(" ")])
for i in range(y+1):
    for j in range(x+1):
        if cartesian_coordinates[i][j]==0:
            num_mom+=1
        else:
            num_kid+=cartesian_coordinates[i][j]
print(num_mom,",",num_kid)
#母豬座標
u=[]
v=[]
for i in range(y+1):
    for j in range(x+1):
        if cartesian_coordinates[i][j] == 0:
            u.append(i)
            v.append(j)  
#母豬四周圍小豬數
around_kid=0
for t in range(len(u)):
    for i in range(y+1):
        for j in range(x+1):
            if ((u[t]-i)**2)+((v[t]-j)**2) <= r**2 :
                around_kid+=cartesian_coordinates[i][j]
#環境溫度是否正常
if (around_kid/num_kid)*100 > d:
    print(0)
else:
    print(1)
> ## 錯誤訊息
> Wrong answer
> 
> ## 問題描述
> 已經用測資試過了，都是正確的
> 但交到批改系統上都是wrong answer
> 
> 想法:
> 1.先將母豬總數和小豬總數算出
> 2.將有母豬的位置存入list中
> 3.確認在母豬身邊的小豬數量
> 4.確認溫度是否適合

**Comment by TJ72** [comment]
`print(num_mom,",",num_kid)`這樣輸出數字與 ',' 間會有空格喔

**Comment by janna0329** [comment]
> `print(num_mom,",",num_kid)`這樣輸出數字與 ',' 間會有空格喔

天哪!太感謝了，我卡了好久，馬上AC了
