### ISSUE TITLE
[Homework #] 小仔追盜賊

### ISSUE THREAD

**Issue by cy-hsu-md** [coding-coworking-club/python-spring-2021#243]
## 提交連結

https://judge.ccclub.io/status/5a1bc7079fd6fcbd4f6410429036e329

## 程式碼

```python
#先定義輸入與停止時機
lst=[]
while 1:
    item=input()
    if item == "END":
        break
    else:
        lst.append(item) #將輸入的字串放進一個我自己定義的串列中，以方便下面處理

for n in lst:
    n = n.strip()
    a = "0"
    for i in range(0,len(n)):
        #先定義如果字串中的任一個地方為題目給定的四個半形標點符號
        if n[i] == "." or n[i] == ";" or n[i] == ":" or n[i] ==",":
            #如果是第一個的話那就一定留著輸出並且後面加空格
            if i == 0:
                a += (n[i]+" ")
                continue
            else:
                #如果不是第一個的話：如果跟前面相同就忽略，如果不同的話就輸出且後面加空格
                if n[i] != n[i-1]:
                    a += (n[i]+" ")
                    continue
                elif n[i] == n[i-1]:
                    continue
        #這邊考慮如果輸入的一串字串中的空格前面有標點符號的話，這個空格要忽略不計（因為前面設定標點符號後面要多加一個空格)，或是這個空格的前面也是空格的話也要忽略不計
        elif n[i] == " " 
            if n[i-1] == "." or n[i-1] == ";" or n[i-1] == ":" or n[i-1] ==",":
                continue
            elif n[i-1] == " ":
                continue
            else:
                a += n[i]
        else:
            #接下來考慮若有輸入藏身地的話，前後要加反斜線
            if n[i] == "藏" and n[i+1] == "身" and n[i+2] =="地":
                a += ("\\藏身地\\")
                continue
            elif n[i] == "身" and n[i-1] == "藏" and n[i+1] == "地":
                continue
            elif n[i] == "地" and n[i-2] == "藏" and n[i-1] == "身":
                continue
            else:
                #其他部分直接輸出
                a += (n[i])
                continue
    print(a[1:])
```

## 問題描述

我的想法是先定義輸入與停止的時機，並且將輸入的字串加進一個我自己定義的串列中方便運算。
接著定義若字串中有遇到題目給地的四個半形標點符號的話要如何輸出。
接著定義字串中如果遇到"藏身地"的話要前後加上反斜線輸出。
接著定義字串中其他字串直接輸出。

在自己的jupyternotebook上輸入兩組測資顯示出來都是和批改系統給的output一樣的答案，不過丟到批改系統上卻顯示 wrong answer，不知道我的程式與想法哪裡出了問題呢？再麻煩各位同學與助教指點了，謝謝！

**Comment by hchbiggrass** [comment]
1. 雖然標點符號後面要接空格，但每一句最後面不會有空格。
2. 目前的寫法在標點符號後面有多個空格時無法處理。

**Comment by cy-hsu-md** [comment]
> * 雖然標點符號後面要接空格，但每一句最後面不會有空格。
> * 目前的寫法在標點符號後面有多個空格時無法處理。

謝謝您的提醒
1. 關於每句最後面不會有空格：最後我試過，在要輸出前用 a = a.rstrip() 就可以解決。
2. 標點符號後面有多個空格的處理方式：目前想破頭沒有想到比較適合的寫法，不知道如果是用這種字串的寫法的話，您有沒有比較建議往哪個方向去思考呢？

謝謝您！

**Comment by hchbiggrass** [comment]
有一種方法可以試試看：用迴圈，如果空格後面還有空格就把後面的空格殺掉

**Comment by cy-hsu-md** [comment]
> 有一種方法可以試試看：用迴圈，如果空格後面還有空格就把後面的空格殺掉

謝謝您的回覆，後來我直接改成如果一個空格前面是空格的話，那這個空格就忽略不計，然後就被accepted了。(已經將程式碼更新在上面了。）

不過這樣子好像輸入如果是There is a    book的話（a 和 book 中間有四個空格），輸出會變成There is a book。我當初是糾結在如果輸入的文字中間如果有空格的話要保留，但是標點符號間的空格要刪除，但依照這個寫法好像是無論在文字間的空格或是標點符號間的空格，只要超過兩個都會被刪除，結果被批改系統accepted。

這部分好像令人有點困惑，我印象中有看到GitHub上別的同學發問中，也有在程式中放入要保留文字間的空格的寫法。不知道題目真正想問的是哪個呢？以及想說這部分是否可以麻煩助教加註在題目中呢？這樣其他同學應該較容易理解。

另外，可否也請教您，如果是要同時「剔除標點符號間的空格（然後再用程式前面的部分標點符號後加一個" ")」以及「保留文字間的空格」的話，要怎麼寫會比較好呢？

謝謝您！

**Comment by jeffery12697** [comment]
如果空白在字和字中間，是不做消除的喔，題目有說是標點符號後的空白才需要做處理，方法的話你可以，用迴圈跑字串，跑到標點符號後再檢查後面的空白，如果是複數個就只保留一個，如果沒有就加一個～

**Comment by cy-hsu-md** [comment]
好的，謝謝您！
