### ISSUE TITLE
[Week 4] 打字機

### ISSUE THREAD

**Issue by NTNU-CYY** [coding-coworking-club/python-spring-2021#247]
## 提交連結

https://judge.ccclub.io/status/1d56b9ef961a6f369bfa6cd93a72e392

## 程式碼

```
str_input_lst = [ str(j) for j in input()]

a = len(str_input_lst)
k = 0

while k < a:                                                               # 第一個迴圈是把字串前面的 "+" 、 "-" 、"*" 都拿掉
    if str_input_lst[k] != "+" and "-" and "*":
        break
    if str_input_lst[k] == "+" or "-" or "*":
        str_input_lst.pop(k)
        k -= 1
    k += 1

i = 0
b = len(str_input_lst)
while i < b:                                                                  # 第二個迴圈才是處理 "+" 、 "-" 、"*"  的效果

    if str_input_lst[i] == "+":
        str_input_lst.pop(i)       
        add = str_input_lst[i-1]
        str_input_lst.insert(i, add)
        b = len(str_input_lst)

    elif str_input_lst[i] == "-" :
        str_input_lst.pop(i)
        str_input_lst.pop(i-1)
        b = len(str_input_lst)

    elif str_input_lst[i] == "*" :
        str_input_lst.pop(i)
        j=0
        while j < i:
            str_input_lst.insert(i+j,str_input_lst[j])
            j += 1 
        b = len(str_input_lst)   
      
    i += 1

print("".join(str_input_lst))

```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/80100772/112443567-1017dc80-8d88-11eb-9168-90d12c55c174.png)

## 問題描述

嘗試了Judge上面的sample，結果是可以的。
放入Visualize，感覺也符合我寫的思路。
另外，也嘗試輸入了幾種input，看起來也OK，不知為何無法accepted。

想釐清自己寫code邏輯上，是否有盲點，謝謝。

**Comment by hchbiggrass** [comment]
記得貼上submit的連結喔，細節請參考[github 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)

**Comment by NTNU-CYY** [comment]
謝謝助教，之前一直找不到自己submit的連結。補上了，謝謝。

**Comment by hchbiggrass** [comment]
雖然你已經用while來跑迴圈，但index值在有刪東西的時候沒有對好

**Comment by NTNU-CYY** [comment]
感謝助教，好像發現盲點了。
應該是處理 "-" 的時候，刪了前面的字元，但卻未將index調回前面，所以如果連續幾個特殊符號，就會跳掉。
目前已經重新修改code，但因為Week 4已關閉，不曉得如何測試程式碼是否正確？
謝謝。

**Comment by hchbiggrass** [comment]
題庫(Problems)裡面也有這一題，找一下就有了

**Comment by NTNU-CYY** [comment]
謝謝助教，我在題庫裡找到了，但很不幸，送出答案後，依然沒被接受。
結果是Runtime Error
提交連結如下
https://judge.ccclub.io/status/d6f4a1bb91e66dc657a86dfabd6f8ac5

請問助教，我是否應該另開提問，還是在這個頁面下，繼續提問即可。
謝謝

**Comment by hchbiggrass** [comment]
很接近答案了，還有一種狀況要考慮：輸入的字串只有運算符號

**Comment by NTNU-CYY** [comment]
耶~~~感謝hchbiggrass 助教的不厭其煩，已順利accepted，謝謝。
