### ISSUE TITLE
[General] 6-3：母音種類個數

### ISSUE THREAD

**Issue by brian112986** [coding-coworking-club/python-spring-2021#248]
## 提交連結

https://judge.ccclub.io/status/faff25e3e6dddb8e9f1daf486caa2578
## 程式碼

```python
x = input()
y = ["a", "e", "i", "o", "u", "A", "E", "I", "O", "U"]
count = 0
for i in range(0,len(x)):
    if x[i] in y:
        count += 1
print(count)
```

## 問題描述

自行測試都是對的，但是judge系統還是回報wrong answer，想請問程式碼是哪裡出問題？謝謝助教

**Comment by chianshianli** [comment]
(非助教，僅供參考)
題目是問母音種類個數，你的程式碼出來的會是母音個數。
例如 yee ，題目要的答案是 1，你的程式碼出來會是 2 喔 ~

**Comment by brian112986** [comment]
對誒我沒有看清楚題目，謝謝你
