### ISSUE TITLE
[Week 2] NTU等第

### ISSUE THREAD

**Issue by penguin1131** [coding-coworking-club/python-spring-2021#25]
## 提交連結

https://judge.ccclub.io/status/527d09f3bc7f434a04e768cfb619fa83
## 程式碼

```python
a = int(input())
if a>=90:
    print ("A+")
elif a>=85:
    print ("A")
elif a>=80:
    print("A-")
elif a>=77:
    print("B+")
elif a>=73:
    print("B")
elif a>=70:
    print("B-")
elif a>=67:
    print("C+")
elif a>=63:
    print("C")
elif a>=60:
    print("C-")
elif score <=59:
    print("F")     
else:
    print("X")
```

## 問題描述

在jupyter notebook可以正常輸出，也跟課堂上助教demo時的內容相同，但在judge系統中卻一直顯示錯誤。
有檢查過是否半全型的輸入問題，但還是無法解決。
實在是抓不出那邊有問題，因此上來提問。

**Comment by andykuo0956** [comment]
（我是學員所以不一定下面的回答有幫助哈哈哈
這樣不會輸出Ｘ
最低只有Ｆ

**Comment by TJ72** [comment]
感謝上面同學的回答，最後的 elif和 else那邊邏輯的確需要改一下。然後最後一個 elif的變數好像用錯了喔。
