### ISSUE TITLE
[Homework 2] 小仔養豬

### ISSUE THREAD

**Issue by CKJK47** [coding-coworking-club/python-spring-2021#252]
## 提交連結

https://judge.ccclub.io/status/21c40b8d4a9a6371a319e41dc972e6b0
## 程式碼

```python
#先定義x, y, r, d
variable = [int(n) for n in input().split()]
x = variable[0]
y = variable[1]
r = variable[2]
d = variable[3]

#把每一行裝進一個大的list
Big_list = []
num = 0
while num <= y:
    small_list = [int(n) for n in input().split()]
    Big_list.append(small_list)
    num += 1
    if num > y:
        break

#算母豬數量B_pig
B_pig = 0
for k in Big_list:
    if 0 in k:
        B_pig += 1

#算小豬數量S_pig
S_pig = 0
for k in Big_list:
    S_pig += sum(k)
#印出第一行答案
print(B_pig, S_pig, sep = ",")
    
#建立母豬的座標uv_list，以及小豬的座標ij_list
uv_lst = []
ij_lst = []
Big_list = Big_list_2[:]
for k in range(len(Big_list_2)):
    for l in Big_list_2[k]:
        # 遇到0就紀錄母豬的座標u, v
        if l == 0:
            [u, v] = [k, Big_list_2[k].index(l)]
            uv_lst.append([u, v])
        # 遇到非0就紀錄小豬的座標i, j
        else:
            [i, j] = [k, Big_list_2[k].index(l)]
            ij_lst.append([i, j])
        #最後把紀錄完該座標的數目以"#"代替，當作紀錄完，才不會如果遇到一個
        #list裡面有重複的數字的話index紀錄錯誤
        Big_list_2[k][Big_list_2[k].index(l)] = "#"
        
#判定小豬是否在母豬四周，並用符合的小豬數做成一個串列
cnt = []
for h in uv_lst:
    for m in ij_lst:
        if (h[0] - m[0]) ** 2 + (h[1] - m[1]) ** 2 <= r ** 2:
            cnt.append(Big_list[m[0]][m[1]])

#判斷小豬是否過於靠近母豬formulation
for p in cnt:
    if (p / S_pig) * 100 > d:
        ans = 0
        break
    else:
        ans = 1
print(ans)
```

## 錯誤訊息

<img width="916" alt="截圖 2021-04-01 下午6 36 39" src="https://user-images.githubusercontent.com/79802408/113282215-35bd5c80-9319-11eb-833c-ffe56273993c.png">

## 問題描述

1. 每一段落運算以註解說明
2. 輸出母豬及小豬個數沒問題
3. 關於答案第二行，我先建立母豬的坐標list，再建立小豬的坐標list，然後用母豬的list對小豬list跑迴圈，如果有小豬座標符合座標距離公式，就把該座標代表的小豬數放進一個cnt串列之中
4. 最後對cnt串列跑迴圈，只要有符合密集度條件迴圈就停止輸出0，都沒有就輸出1
5. 目前找不出程式錯誤在哪裡QQ

**Comment by happywillie** [comment]
我不是助教，但我在猜問題是不是出在「建立小豬的座標ij_list」那一段，裡面有寫到：
for j in Big_list[k]:
    if j != 0:
        [i, j] = [Big_list[k].index(j), k]

在Big_list[k].index(j)這裡會不會有一個問題，假設 j = 2 (兩隻小豬)好了，但在Big_list[k]裡，有兩個以上的點有兩隻小豬，它的index會不會記錄到前一位的位置

比如說
a = [2,0,2,1]
print(a.index(2))
print出來的答案是0，第二個2的位置就沒被記錄到了

**Comment by CKJK47** [comment]
感謝樓上提到的問題，我用計算完座標後把那個數字變成"#"代替，就不會取到錯誤的index修正後，測資2仍然錯誤，還是不知道錯在哪裡QQ
修正後code如下，其他部分沒有改動
#建立母豬的座標uv_list，以及小豬的座標ij_list
uv_lst = []
ij_lst = []
Big_list = Big_list_2[:]
for k in range(len(Big_list_2)):
    for l in Big_list_2[k]:
        # 遇到0就紀錄母豬的座標u, v
        if l == 0:
            [u, v] = [k, Big_list_2[k].index(l)]
            uv_lst.append([u, v])
        # 遇到非0就紀錄小豬的座標i, j
        else:
            [i, j] = [k, Big_list_2[k].index(l)]
            ij_lst.append([i, j])
        #最後把紀錄完該座標的數目以"#"代替，當作紀錄完，才不會如果遇到一個
        #list裡面有重複的數字的話index紀錄錯誤
        Big_list_2[k][Big_list_2[k].index(l)] = "#"

**Comment by CKJK47** [comment]
還未得到解答，是否能請助教再過目，謝謝

**Comment by yichensu** [comment]
> 還未得到解答，是否能請助教再過目，謝謝

可以再傳目前修改後的完整程式嗎～
目前排版比較難確認問題
感謝！

**Comment by CKJK47** [comment]
> > 還未得到解答，是否能請助教再過目，謝謝
> 
> 可以再傳目前修改後的完整程式嗎～
> 目前排版比較難確認問題
> 感謝！
我已經修改貼文了，這是修改後的程式碼，謝謝！

**Comment by yichensu** [comment]
@CKJK47 先給你幾個建議：
- Big_list = Big_list_2[:] 這行看起來有誤，可以在想一下正確的複製方式
- 你的程式有很多重複的地方，可以思考如何在一開始輸入資料時，就能儲存位置（後面那兩個串列 uv_lst = [] ij_lst = [] ）與判斷計算母豬小豬數量
- 建議思考前面使用 while loop 還是 for loop 比較能達成你的目的；另外，通常 loop 判斷不包含等號會比較好理解與控制，而改使用 for loop 也可以避免需要自行更新 num 的值與相對容易將重複步驟簡化
