### ISSUE TITLE
[Homework 2]  小仔選配飼料

### ISSUE THREAD

**Issue by happywillie** [coding-coworking-club/python-spring-2021#253]
## 提交連結

https://judge.ccclub.io/status/ed51ddfce9b0178620e37a84fe591386

## 程式碼

```python
#配飼料

#輸入資料
basic =  [int(i) for i in input().split(" ")]
a_company = [int(i) for i in input().split(" ")]
b_company = [int(i) for i in input().split(" ")]

#定義基本參數
min_price = float("inf")
price = 0
best_a = 0
best_b = 0

#執行u,v的各種組合
for u in range(0,basic[0]+1):
    for v in range(0,basic[0]+1-u):
        
        #符合付費條件的u,v組合
        if (u * a_company[0] + v * b_company[0] ) >= basic[1] and \
        (u * a_company[1] + v * b_company[1] ) >= basic[2] and \
        (u + v) <= basic[0]:
            price = u * a_company[2] + v * b_company[2]
            
            #找出最小金額的u,v組合
            if price < min_price or \
            (price == min_price and (u + v) > (best_a + best_b)) or \
            (price == min_price and (u + v) == (best_a + best_b) and u < best_a):
                min_price = price
                best_a = u
                best_b = v

#執行u,v的各種組合
print(str(best_a)+","+str(best_b))
print(min_price)
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/81223368/112577528-6be97080-8e2f-11eb-9ed3-21eeb24b0b62.png)

## 問題描述

1. a_company為甲公司、b_company為乙公司，u為甲公司飼料購買噸數、v為乙公司飼料購買噸數
2. basic[0]為至多採購的公噸數、basic[1]為蛋白質含量標準、basic[2]為脂質含量標準
3. u,v使用for迴圈提供各種組合(u = 0  v = 0, u = 0  v = 1, u = 0  v = 2......以此類推)，先用第一個if找出滿足題幹敘述的u,v組合，算出相對應的金額price
4. 用第二個if找到最小金額值的u,v組合，將該組合的資訊存進best_a, best_b
5. **測資時看似正常，沒有出現問題，但在提交時出現runtime error，不曉得是不是有自己沒有考慮到的條件**

**Comment by TJ72** [comment]
Runtime Error 的原因應該是出在`input().split(' ')`上，這部分請參考 #187 上的討論，其他運算上看起來應該沒有什麼問題～

**Comment by happywillie** [comment]
成功了！非常感謝！
