### ISSUE TITLE
[General] 時間戳記

### ISSUE THREAD

**Issue by ghost** [coding-coworking-club/python-spring-2021#258]
## 提交連結

https://judge.ccclub.io/status/a4f0021e2d70c566f50f0dd48c89f388
## 程式碼

```python
from datetime import datetime
n=int(input())
the_time=datetime.fromtimestamp(n)
print(the_time.strftime('%Y-%m-%d %H:%M:%S'))
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/52339710/112713598-f786fe00-8f10-11eb-996e-090cd554a1c5.png)
![image](https://user-images.githubusercontent.com/52339710/112713606-05d51a00-8f11-11eb-9cdb-c817601b65c1.png)

## 問題描述

雖然ac了但在小時的部分跟judge的答案不一樣，請問是sample output給錯嗎？還是有其他原因，麻煩助教解答了謝謝！

**Comment by hchbiggrass** [comment]
Judge並沒有錯，只不過用Jupyter notebook時會自動改成當地時區的時間，所以如果你在台灣，因為台灣時區是+8，你用timestamp轉的時候會發現時間會快8小時。要檢驗這件事情很簡單：
1. 用你的程式碼輸入0。照理說timestamp的起點是1970年1月1日0:00，你的話應該會發現是1970年1月1日的9點。至於為什麼是這個日期，請參考[這篇](https://zh.wikipedia.org/wiki/UNIX%E6%97%B6%E9%97%B4)。
2. 你也可以直接改自己電腦的時區，並且在jupyter restart kernal，會發現輸出的時間變化。

如果不想要輸出的時間受到時區影響，需要定義時區，最開始匯入的模組改成
from datetime import datetime, timezone
從時間戳轉成時間的語法改成
datetime.fromtimestamp(n, tz=timezone.utc)
就可以了

**Comment by ghost** [comment]
了解，感謝！
