### ISSUE TITLE
[Homework 1] 小葉喝可樂 

### ISSUE THREAD

**Issue by andykuo0956** [coding-coworking-club/python-spring-2021#26]
##提交連結
be68c9140353
## 程式碼
```python
begin = int(input())
rag = int(input())

sumco = 0

if begin < rag:
    print(begin)
elif begin >= rag:
    for i in range(begin):
        #print(begin)
        if begin >= rag:
            sumco = sumco + begin
            #print(sumco)
            begin = begin // rag
        else:
            sumco = sumco + begin
            break
    print(sumco)
```
## 問題描述
input output都沒有問題，我自己設計了幾個數字也是對的，不確定問題在哪裡～
想法：
先設一個變數sumco
如果小葉買的數量低於賣場兌換數量，則輸出小葉購買數量
如果小葉買的數量高於賣場兌換數量，那就丟進一個迴圈，每一次都讓sumco增加一輪，每一輪是小葉可以換到的總數，如果小葉可以換到的總數小於賣場兌換數量 則加上最後兌換到的幾瓶並跳出
拜託大家惹

**Comment by Yueh-H** [comment]
嗨 我不是助教，不過你跟我一開始卡到的點有點類似

後來思考後發現 少掉了一個考慮
就是如果一開始兌換的時候有剩下空瓶沒有去兌換的，那麼兌換後的飲料喝掉的飲料 後的空瓶 必須加上一開始的空瓶
不知道是不是你卡的點～～

**Comment by andykuo0956** [comment]
> 嗨 我不是助教，不過你跟我一開始卡到的點有點類似
> 
> 後來思考後發現 少掉了一個考慮
> 就是如果一開始兌換的時候有剩下空瓶沒有去兌換的，那麼兌換後的飲料喝掉的飲料 後的空瓶 必須加上一開始的空瓶
> 不知道是不是你卡的點～～

哇！我沒考慮到這點，謝謝你～我回去試試看是不是卡在這裡！

**Comment by andykuo0956** [comment]
> > 嗨 我不是助教，不過你跟我一開始卡到的點有點類似
> > 後來思考後發現 少掉了一個考慮
> > 就是如果一開始兌換的時候有剩下空瓶沒有去兌換的，那麼兌換後的飲料喝掉的飲料 後的空瓶 必須加上一開始的空瓶
> > 不知道是不是你卡的點～～
> 
> 哇！我沒考慮到這點，謝謝你～我回去試試看是不是卡在這裡！

我修正了這個錯誤（應該是修正了？），帶了一些數字（20/3  20/5）執行出來跟我自己用紙筆算的一樣，結果還是wa嗚嗚嗚，不知道方不方便請您幫我看一下問題在哪裏～謝謝！
`
begin = int(input())
rag = int(input())

sumco = 0
perround = begin + 1

if begin < rag:
    print(begin)
elif begin >= rag:
    for i in range(begin):
        #print(begin)
        if perround >= rag:
            sumco = sumco + begin
            #print(sumco)
            perround = begin // rag + begin % rag
            #print(perround)
            begin = begin // rag
            #print(begin)
            #print("")
        else:
            sumco = sumco + begin + (rag % begin)
            #print(begin)
            #print(rag % begin)
            break
    print(sumco)
`

**Comment by Yueh-H** [comment]
嗨 同學你好
你的code沒有顯示縮排，這樣看不懂XD～

**Comment by alvisyjchen** [comment]
可以考慮 begin = 5, rag = 3 這筆測資，輸出應該是 7。另外關於 if 的用法也可以再看課程內容確認一次哦

**Comment by andykuo0956** [comment]
> 嗨 同學你好
> 你的code沒有顯示縮排，這樣看不懂XD～

啊對不起！
http://codepad.org/gsQM2Kwh
我不確定怎麼在這上面用正確的顯示，先傳連結給你看看～～謝謝！

**Comment by andykuo0956** [comment]
寫出來了！後來用while迴圈寫就方便許多，謝謝大家～
