### ISSUE TITLE
[Homework 2] 小仔養蛋雞I

### ISSUE THREAD

**Issue by yolingyang** [coding-coworking-club/python-spring-2021#262]
## 提交連結

  
https://judge.ccclub.io/status/f730c1179d33f4a97d581638678a1e6f

## 程式碼

```  
import math
num = [int(z) for z in input().split()]
i,x,t,l = num[0],num[1]*0.01,num[2],num[3]*0.01

total = 0 # 總共蛋數
minus_rate = 0  # x 天前累計蛋下降的比例

for days in range(1,t+1) :
    single_rate = (1+0.5 * days)* 0.01 #第 x 天當天蛋下降的比例
    rate = x - minus_rate - single_rate 
    if rate >= l:
        egg = (rate * i)
        egg = math.ceil(rate * i)
        total += egg
        minus_rate += single_rate 
       #print("more", days, rate, egg) 

    else:
        egg = (l * i)
        egg = math.ceil(l * i)
        total += egg  
        #print("less", days, rate, egg)

print(total)

```

## 錯誤訊息

Wrong Answer  

## 問題描述
有拿 sample 1 測試，算出來會是 1115 而非 1114  
1. 把每一天 print 出來發現是在第 15 天，不知道為什麼 rate 會是 `0.23000000000000004 ` （以程式來說應該要是 `0.23`）  
2. 第 12 天也有類似情況，可是程式自動把最後的 `3` 給移除了   
不太確定怎麼會這樣～謝謝  
<img width="364" alt="截圖 2021-03-27 下午6 43 36" src="https://user-images.githubusercontent.com/80040871/112718212-7b021880-8f2c-11eb-99e9-35aaf6f08b13.png">

**Comment by Viggochang** [comment]
電腦是用二進位在儲存數字資料，所以會把我們常用的十進位的小數轉換成二進位再儲存
簡單來說可以理解成 在轉換後出現一些浮點數的誤差
有興趣的話可以關鍵字搜尋 浮點數誤差

再回歸到程式碼的問題
所以基本上要盡量減少會產生小數的步驟
你一開始讀入 x 和 l 的時候都產生了小數
計算 single_rate 的時候也是
建議在一開始計算比例的時候都先不要乘上0.01
最後算 egg 的時候再乘0.01
這樣就可以減少浮點數造成的誤差

基本上測資有設計過
照上面建議的樣子修改 
應該就可以AC了

**Comment by yolingyang** [comment]
了解～～  
有成功 AC 了 感謝感謝 🙏
