### ISSUE TITLE
[General] 數字最小值排列

### ISSUE THREAD

**Issue by nalajhu** [coding-coworking-club/python-spring-2021#269]
## 提交連結

https://judge.ccclub.io/status/5d398619b77c6f0469b25cc865db6689
## 程式碼

```python
num_lst = input()
if num_lst[0] != 0:
    ans_lst = []
    for i in num_lst:
        ans_lst.append(i)
    ans_lst = sorted(ans_lst)
    count = ans_lst.count('0')
    if count > 0:
        number = 0
        while number <= count:
            if ans_lst[0] == '0':
                ans_lst.remove('0')
            number += 1
        number1 = 1
        while number1 <= count:
            ans_lst.insert(1,'0')
            number1 += 1
    for k in ans_lst:
        print(int(k),end="")
```

## 問題描述

測試範例的輸出都是正確，但是出現WA。
覺得自己把問題變複雜了，又不得不考量"0 不能放在數字首位"，將"0"轉換為"11"進行排序，再轉換回來。

**Comment by TJ72** [comment]
我覺得你的想法還不錯，但因為你是用字串型態的數字在做排序，所以 `'11'` 是小於所有比 `'2'` 大的數字的 (你可以在 Jupyter上試試看～)所以如果輸入 `'23450'` 的話，輸出就會是 `'02345'`了！

**Comment by nalajhu** [comment]
if ans_lst[0] == "0":
        ans_lst.remove('0')
        ans_lst.insert(1,'0')
多增加這三行程式，解決23450的狀況，但是仍是WA???

**Comment by TJ72** [comment]
你只解決了只有一個 '0' 的情況，那如果有兩個、三個甚至更多 '0' 呢？想想看有沒有更一般化的寫法吧

**Comment by nalajhu** [comment]
解出來了，不過繞了蠻大一圈的，以更新如上程式碼
