### ISSUE TITLE
[General] 181103 字串加密 II

### ISSUE THREAD

**Issue by cys939** [coding-coworking-club/python-spring-2021#270]
## 提交連結
https://judge.ccclub.io/status/3611d3ea3650d12b069de66bcb6d7782

## 程式碼

```python
s = input()
n = input()
lst = []

if len(s) <= len(n) : 
    for i in range (len(s)):
        ans = chr(int(ord(s[i])) + int(n[i]))
        lst.append(ans)

while len(s) > len(n) :
    n = n + n 
    for i in range (len(s)):
        ans = chr(int(ord(s[i])) + int(n[i]))
        lst.append(ans)
print("".join(lst))
```

## 錯誤訊息

Runtime Error
## 問題描述

（雖然有用其他方法寫對，但還是想了解這個寫法的問題在哪）
解題想法是：
先判斷字串s是否大於數字n，若字串較短或一樣長，則直接計算；
若字串較長於數字，則將數字重複置放（有參考其他助教提示要用while）
在 Jupyter 上測試沒問題、TraceCode 也看過正常，
但批改系統顯示 Runtime Error ，想請問是否哪裡遺漏，先謝謝解答！

**Comment by TJ72** [comment]
因為加密數字長度的兩倍有可能還是比原先要加密字串的長度還要短阿！用長度的倍數來補足不是一個很保險的做法， `%` 常是解決這種補足長度很好的出發點

**Comment by Viggochang** [comment]
@cys939 如果問題已經被回答了，記得關閉問題喔～
