### ISSUE TITLE
[General] 停車位順位

### ISSUE THREAD

**Issue by Molly995** [coding-coworking-club/python-spring-2021#278]
## 提交連結

https://judge.ccclub.io/status/7990f0d7876efff0c59aff2b85346fe9

## 程式碼

```python
##定義排序的順序
def parking_order(n):
    count = 0                      ##設一變數方便排序
    count += int(n[2])*10          ##把年資*10後加回count（*10是為了跟奇偶的變數做區分）
    if int(n[3])%2 == 1:           ##設定奇數+2，偶數+1
        count += 2 
    else:
        count += 1
    return (n[1], 1/count)         ##回傳棟別和count變數（先從棟別開始排序，若棟別相同則照count數字由小到大排）
                                   ##count累積數字越大者，倒數後越小，則排序越前面



number = int(input())                ##輸入，得知有幾位住戶登記
lst = [] 
for i in range(number):              ##照數量給n行輸入
    lst.append(input().split())      ##把輸入的字串轉為list
    
ans = sorted(lst, key=parking_order) ##將取得的字串list依函數規則排序
for k in range(len(ans)):            ##輸出排序過的住戶ID
    shelf = ans[k]
    print(shelf[0])
```

## 錯誤訊息
Wrong Answer

## 問題描述

測了很多次，輸出的答案也都對，不知道哪裡沒考慮到

**Comment by TJ72** [comment]
如果可以在數字上找到一個好的分數代表排序等級的話是一個不錯的方法，但我感覺分數的計算好像跟題目說得不太一樣喔！題目在年資上的排序是區間等級的排序，我覺得用整數計算會有問題

**Comment by Molly995** [comment]
我也一直在想是不是錯在年資那一條，那請問助教，若照5年為一個區間，以下為例
甲 A 12 100
乙 A 13 133
甲和乙都是未滿15年的年資，這樣子的話是號碼為奇數的乙排在前面嗎？

**Comment by Molly995** [comment]
還是規則更簡單？
只有
- 10年以上(含) > 5年以上(含)
- 未滿10年> 未滿5年
這兩種可能？

**Comment by Molly995** [comment]
把規則照下面規則改好後，已AC QQ
- 年資<5
- 10>年資>=5
- 年資>10

原來是只要照這上面的規則就好，我以為還要考慮到下一個區間的問題，例如15年以上、20年以上
感謝助教！

**Comment by Molly995** [comment]
想加問，我的code中有用到取list中的list，但寫起來很迂迴，是否有比較簡潔的方式能把list中的list中的特定index取出來呢？

**Comment by TJ72** [comment]
> 想加問，我的code中有用到取list中的list，但寫起來很迂迴，是否有比較簡潔的方式能把list中的list中的特定index取出來呢？

可以直接用 2-dimensional list 的 index 叫出指定位置的值喔～以上面的 code 為例：
```python
for k in range(len(ans)):
    print(ans[k][0])
    # shelf = ans[k]
    # print(shelf[0])
```

**Comment by Molly995** [comment]
了解了！
我之前嘗試 print(ans[k[0]])，但k被判斷為整數所以叫不出來 囧
感謝助教的回答！
