### ISSUE TITLE
[Week 5] 數字組合最大值排序

### ISSUE THREAD

**Issue by hadao02** [coding-coworking-club/python-spring-2021#280]
## 提交連結
https://judge.ccclub.io/status/2d1567267766fd8a859f166881c1bbcf

## 程式碼

```
def function(n):
    n = str(n)
    i = sorted(n, reverse=True)
    i = ''.join(i)
    return(i)
n = input()
n = n.split()
n = sorted(n, key=function)
print(n)

```

## 問題描述

"Wrong answer" and I do not know why... Both of the outputs are right

**Comment by TJ72** [comment]
If you sort the numeric numbers in string, the results may be wrong when the numbers in different digits. You can try the input `n = 112 98 235`.

**Comment by hadao02** [comment]
> If you sort the numeric numbers in string, the results may be wrong when the numbers in different digits. You can try the input `n = 112 98 235`.

Thank youuuu
