### ISSUE TITLE
[General] 書碼編輯 II

### ISSUE THREAD

**Issue by ghost** [coding-coworking-club/python-spring-2021#281]
## 提交連結

https://judge.ccclub.io/status/a28e534cc4878bd582babc1d35bde8ff
## 程式碼

```python
import json
n=input()
dicn=json.loads(n)
l=[chr(i) for i in range(65,65+26)]
dic2=dict([(i,j) for i,j in enumerate(l)])
def n12(x):
    return dic2[x//26//26]+dic2[x//26%26]+dic2[x%26]
def n3(x):
    return dic2[x//26//26//26]+dic2[x//26//26%26]+dic2[x//26%26]+dic2[x%26]
for i in dicn:
    for ii,j in enumerate(dicn[i]):
        dicn[i][ii]=n12(int(j[:3]))+n12(int(j[3:6]))+n3(int(j[6:])) 
    print(i,dicn[i])
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/52339710/112762301-8854fb00-9031-11eb-9e85-d331c43c1309.png)
![image](https://user-images.githubusercontent.com/52339710/112762312-9a369e00-9031-11eb-808b-d0a1528f306d.png)

## 問題描述
我是先用兩個函數來轉換成英文字，然後再用迴圈把每個數字都轉換，兩個測資都對，不知道哪裡有bug，截圖是output的does跟['AACAABAAAF', ....之間沒有空格，但Disneyowned ['AABAAB..有，不知道是不是這個原因錯誤，另外想問一下輸入的數字一樣是10碼嗎？還是會有17575-17575-456975=>ZZZZZZZZZZ這種的，再麻煩助教了謝謝！

**Comment by TJ72** [comment]
我這邊的 output does 後面是有空格的，所以我覺得 WA 的原因應該不是這個。我感覺 code WA 的原因應該是 Judge 系統裡面的字典是沒有順序的(雖然在 Jupyter 上有)，所以當最後在用字典的 key 跑 for-loop 的時候可能不會按照原本輸入的書本順序跑出輸出。

**Comment by ghost** [comment]
感謝！！！！！ac了
