### ISSUE TITLE
[General] 193301 揪狼殺

### ISSUE THREAD

**Issue by nick30924** [coding-coworking-club/python-spring-2021#298]
## 提交連結

https://judge.ccclub.io/status/3cf6984bf96de239a0758ff8aa92373b

## 程式碼

```python
n = int(input())
OKtime = []

for n in range(n):
    time = [int(i) for i in input().split()]
    for t in time:
        OKtime.append(t)

OKpeople = []

for h in range(24):
    OKcount = OKtime.count(h)
    OKpeople.append(OKcount)

if max(OKpeople) < 12:
    print(OKpeople.index(max(OKpeople)))
else:
    OKfinal = []
    ans_lst = []
    for i in OKpeople:
        if i >= 12:
            OKfinal.append(OKpeople.index(i))
    for h in range(24):
        count = 1
        if h in OKfinal:
            count += 1
            for i in range(1, 24):
                if (h + i) in OKfinal:
                    count += 1
                else:
                    break
        ans_lst.append(count)
    print(ans_lst.index(max(ans_lst)))
```

## 錯誤訊息

WA

## 問題描述

我試過了兩個sample都是對的，但找不到自己哪裡寫錯，解題想法大概如下：
1.先使用迴圈將每個人可以的時間全部丟到一個串列裡
2.使用迴圈range(24)取0點到23點可以的數量，並正好可以將index視為時間去對應人數
3.若串列最大值小於12(也就是少於12人)，則取最大值之index，即時間點
4.若串列最大值大於等於12，則先將所有大於等於12人的時間點填入OKfinal串列中
5.使用迴圈range(24)取各個時間點，並先令count = 1，若某時間點也正好落在OKfinal中，則使count +1
6.若某時間點+1的時間點也在OKfinal中，則count再加一，若不連續則停止迴圈
7.ans_lst為每個時間點所獲得的count，count最多者即為連續最多者，也就是答案

找不到盲點在哪，還請大家幫忙看一下，謝謝

**Comment by ghost** [comment]
非助教，感覺沒有考慮到大於等於12人然後都沒有連續的情況。

**Comment by nick30924** [comment]
謝謝你的回覆~ 對於大於等於12人的情形，我有在第五步寫到，超過12人的情形如果有出現在OKfinal中，則把count+1，這麼一來沒有超過12人的時間點都會只是1，而只要有超過12人的時間點，沒有連續的情況下也會成為count == 2，應該有考慮到，還是我哪裡誤解還是程式沒有寫得夠周全。

**Comment by TJ72** [comment]
我感覺第22行的 `lst.index(element)` 怪怪的耶～ `.index()` 只能取到串列中該元素第一次出現的 index ，如果有兩個以上的時間都有相同的人數，那永遠都只能取到排在前面的

**Comment by nick30924** [comment]
感謝助教提點，成功獲得AC了~我發現只要使用for i in range(len(OKpeople))就可以避開index取值的問題，本來還想把取過的>=12人命令成0讓index不重複取到，結果用前述的方法就變得更簡單了。
