### ISSUE TITLE
[General] 確認是否安裝成功時，跳出環境未啟動訊息

### ISSUE THREAD

**Issue by chianshianli** [coding-coworking-club/python-spring-2021#3]
## 程式碼

```python

```

## 錯誤訊息

![python environment not activated](https://user-images.githubusercontent.com/18030336/109482820-72e3c400-7ab9-11eb-983d-aea8c04c32f1.png)

## 問題描述

確認 python 是否安裝成功時，出現環境未啟動的警語（如上圖），但目前在 jupyter 上練習習題都沒問題，有 google 了一下相關問題，但有點難理解 😭 請問有需要去動他嗎？如果這問題太伸手牌再煩請告知我在自己研究一下，謝謝！

**Comment by alexypdu** [comment]
試試看用 **Anaconda Prompt** 開啟呢？

**Comment by chianshianli** [comment]
可以耶~謝謝您 🤟
