### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by emilyjenjen** [coding-coworking-club/python-spring-2021#30]
## 程式碼

buy=int(input())
num=int(input())
change1=int((buy-(buy%num))/num)
if change1<num:
    print(int(buy+change))
else:
    change2=((change1+(buy%num))-((change1+(buy%num))%num))/num
    if change2<num:
        print(int(buy+change1+change2))
    else:
        change3=int[(((change1-change2*num)+change2)-((change1-change2*num)+change2)%num)/num]
        print(int(buy+change1+change2+change3))

## 問題描述

一開始我是想說一層一層（每換一次寫一段程式碼）來計算出總共換了多少瓶可樂，再加上原本購買數量。不過後來寫一寫才想到這樣數字一大就會跑不出來，所以就開始想這個問題是不是要用迴圈？不過課程又還沒交所以感覺有辦法用現在學到的function寫。但實在是怎麼想都想不出來，後來有試著使用+=，但一樣寫一寫發現他也是需要用迴圈的感覺，可否請助教給予提示？

**Comment by cyhsieh264** [comment]
請附上提交連結以及錯誤訊息，並參考 [github 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036) 修正程式碼格式，謝謝！

註：作業通常會涵蓋近一兩週新學的內容，可以考慮使用迴圈。另修正過後，如要繼續發問可再開啟提問～
