### ISSUE TITLE
[General] 停車位順位

### ISSUE THREAD

**Issue by CKJK47** [coding-coworking-club/python-spring-2021#302]
## 程式碼

```python
def priority(lst):
    if lst[1] == "A":
        return 1
    elif lst[1] == "B":
        return 2
    elif lst[1] == "C":
        return 3
    
    if int(lst[2]) >= 10:
        return 1
    elif int(lst[2]) >= 5:
        return 2
    elif int(lst[2]) < 5:
        return 3
    
    if int(lst[3]) % 2 == 1:
        return 1
    elif int(lst[3]) % 2 == 0:
        return 2
    
n = int(input())
num = 0
LST = []
while num < n:
    lst = [str(i) for i in input().split()]
    LST.append(lst)
    num += 1
for j in range(len(LST)):
    LST[j] = priority(LST[j])

**ans = sorted(LST, key = lambda x: (x[1], x[2], x[3]))**
for k in range(len(ans)):
    print(ans[k][0])
```

## 錯誤訊息

<img width="703" alt="截圖 2021-03-31 下午5 28 13" src="https://user-images.githubusercontent.com/79802408/113122769-844df680-9246-11eb-91d3-3f7fb0842164.png">

## 問題描述

1. 我先定義一個函式把每一個住戶資訊都轉換成數字，以利直接用數字大小排序
2. 輸入住戶資訊，並全部存成一個大的list(LST)，之後用函式轉換住戶資訊
3. 對大的LST進行排序，想要使用lambda功能，先看index為1、再看index為2、最後看index為3
4. 錯誤：'int' object is not subscriptable的理由是？為什麼無法直接用指定index去排序？又要怎麼改才會達到排序的需求呢？

**Comment by TJ72** [comment]
同學我有點看不太懂你的問題耶！你上面 po 的 code 是不是跟你實際跑的 code 不是同一篇？我在上面的程式碼找不到`multi_sort` function耶！

**Comment by CKJK47** [comment]
> 同學我有點看不太懂你的問題耶！你上面 po 的 code 是不是跟你實際跑的 code 不是同一篇？我在上面的程式碼找不到`multi_sort` function耶！

不好意思我貼錯截圖QQ
已經重新上傳正確的錯誤截圖了，謝謝！

**Comment by TJ72** [comment]
上面的 code 在輸入完住戶資料(存成 2-dimensional list 之後)，你先用了 `priority` function 處理排序問題。但在你的函式中的寫法不管輸入什麼參數(lst)，都只會回傳一個整數，所以接下來做串列的 sorting 時，因為串列中的每個元素都是整數，當 lambda function 取 `x[1], x[2], x[3]` 時，Python 才會回傳 TypeError。
簡言之，就是 `priority` function 回傳值的問題，在這你應該想讓他回傳一個串列(or tuple)，所以應該是參數裡的全部元素都運算完得到結果之後，再裝到 list (or tuple) 作為回傳值，這樣就可以解決 lambda function 裡遇到的問題了！

**Comment by CKJK47** [comment]
我了解問題了，謝謝！
