### ISSUE TITLE
[Homework 2] 小仔養蛋雞II

### ISSUE THREAD

**Issue by jimmy97332** [coding-coworking-club/python-spring-2021#306]
## 提交連結

https://judge.ccclub.io/status/676c04095c90299727a7cbde8bdf66a1
## 程式碼

```python
import math
I, x0, T, L, D = map(int, input().split())

N=0
best1=0 #不換羽毛的解
N2=0
N3=0
befored=0
afterd=0
add=0
best2=0 #換羽毛的最佳解
day=0 #答案天數
#先算不換羽毛的
for t in range(1,int(T+1)):
    if ((x0-(t+((1+t)*t)/4))*0.01) < int(L)*0.01:
        x1=int(L)*0.01
    else:
        x1=((int(x0)-(t+((1+t)*t)/4))*0.01)
    N+=I*x1
    N=math.ceil(N)
    #print(math.ceil(N))#檢查每個
    best1=math.ceil(N)
#print(f"不換羽毛:{best1}")#檢查

#換羽毛分為換羽前跟換羽後，d為換羽毛的第一天 
#換羽毛前
for d in range(1,T+1):
    for i in range(1,d):
        if (x0-(i+((1+i)*i)/4)) < L:
            x2=L*0.01
        else:
            x2=(x0-(i+((1+i)*i)/4))*0.01     
        N2+=I*x2    
        N2=math.ceil(N2)
#換羽毛後
    for j in range(d+D,T+1): 
        if (d+D)>=(T+1):    
            break
        else:            
            if (90-(j-(d+D)+0.5*add)) < L:
                x3=L*0.01
            else:
                if j==(d+D):#換完後第一天
                    x3=90*0.01        
                else:
                    x3=(90-(j-(d+D)+0.5*add))*0.01    
            N3+=I*x3
            #print(f"j:{j},N3:{N3}")
            N3=math.ceil(N3)
            add+=(j+1) #先加天數，下一圈開始用到
        
    #print(f"d:{d}/{N2},{N3}")#檢查    
    totald = N2+N3
    #只留最佳解
    if totald>best2:
        best2=totald
        day=d
    N2=0 #跑下一圈 d 時先清空
    N3=0 #跑下一圈 d 時先清空
#比較換跟不換
if best1>best2:
    print(f"-1,{best1}")   
else:
    print(f"{day},{best2}")
```

## 錯誤訊息

WA
## 問題描述

試跑是成功的，
我先算出不換羽毛的，再算換羽毛的。
換羽毛分為換羽前跟換羽後，分before跟after計算，再加總為total，d為換羽毛的第一天。
最後比較換跟不換哪個好
想不到哪裡錯了

**Comment by Viggochang** [comment]
你的 afterd 和 befored 在每次 `for d in range(1,T+1):` 迴圈開始時都應該歸0
因為底下的 i 迴圈 和 j 迴圈 並不是所有情況下都會執行
假如總共產蛋10天 換羽需要5天 那從第6天開始都不會執行到 j 迴圈
所以 befored 不會被更新 這時候就會用到第5天的 befored

另外，其實你根本不需要用到 afterd 和 befored 
直接 totald = N2 + N3 就好

**Comment by Viggochang** [comment]
`for i in range(d-1):`
i 迴圈設定有錯
請再複習一下 range 的範圍怎麼取

**Comment by Viggochang** [comment]
j 迴圈裡的判斷式有問題

第1個 if 裡面算產蛋率的式子跟後面else裡面的不一樣(括弧位置有錯)
應該要先更新add再判斷是否小於L吧，你的code會變成用上一次的 j 算出來的產蛋率但斷是否小於Ｌ

```
    for j in range(d+D,T+1):         
        if (90-(j-(d+D))+0.5*add) < L:
            x3=L*0.01
        else:
            if j==(d+D):#換完後第一天
                x3=90*0.01     
            else:
                add+=j #先加天數
                x3=(90-(j-(d+D)+0.5*add))*0.01    
```

**Comment by jimmy97332** [comment]
> `for i in range(d-1):`
> i 迴圈設定有錯
> 請再複習一下 range 的範圍怎麼取

已修正為range(1,d)

**Comment by jimmy97332** [comment]
> 你的 afterd 和 befored 在每次 `for d in range(1,T+1):` 迴圈開始時都應該歸0
> 因為底下的 i 迴圈 和 j 迴圈 並不是所有情況下都會執行
> 假如總共產蛋10天 換羽需要5天 那從第6天開始都不會執行到 j 迴圈
> 所以 befored 不會被更新 這時候就會用到第5天的 befored
> 
> 另外，其實你根本不需要用到 afterd 和 befored
> 直接 totald = N2 + N3 就好

已經刪除 afterd 和 befored，直接 totald = N2 + N3。
在第59、60行已有歸0，
換羽毛後的已把剩餘天數大於換羽毛天數給考慮進去，會直接跳出

**Comment by jimmy97332** [comment]
> j 迴圈裡的判斷式有問題
> 
> 第1個 if 裡面算產蛋率的式子跟後面else裡面的不一樣(括弧位置有錯)
> 應該要先更新add再判斷是否小於L吧，你的code會變成用上一次的 j 算出來的產蛋率但斷是否小於Ｌ
> 
> ```
>     for j in range(d+D,T+1):         
>         if (90-(j-(d+D))+0.5*add) < L:
>             x3=L*0.01
>         else:
>             if j==(d+D):#換完後第一天
>                 x3=90*0.01     
>             else:
>                 add+=j #先加天數
>                 x3=(90-(j-(d+D)+0.5*add))*0.01    
> ```

在第50行改寫成 add+=j +1
因為換完羽毛後第一天產店不會掉產率，故下一天才開始第一次掉產率，
再第一圈起出add=0，結束時把add變成下一圈的數字(j+1)，
如此一來第二圈一開始的add就可以是正確的數字。
但答案還是WA。QQ

**Comment by Viggochang** [comment]
思考一下你的 add 在什麼時候會需要歸0重新計算
你現在的 add 會一直增加下去

**Comment by jimmy97332** [comment]
> 思考一下你的 add 在什麼時候會需要歸0重新計算
> 你現在的 add 會一直增加下去

了解了，非常感謝
