### ISSUE TITLE
[Homework 2] 小仔養蛋雞I

### ISSUE THREAD

**Issue by jingyutsao** [coding-coworking-club/python-spring-2021#309]
## 提交連結

https://judge.ccclub.io/status/cec008e47c76eda3fd17a7a3edb36708

## 程式碼

```python
#小仔養蛋雞I

import math

conditionstr = input().split(" ")
condition = [int(j) for j in conditionstr]
ratelst = [condition[1] - 1.5]
egglst = []

for i in range(2, condition[2] + 1):
    egg_rate = ratelst[-1] - (1 + 0.5 * i)
    if egg_rate >= condition[3]:
        ratelst.append(egg_rate)
    else:
        ratelst.append(condition[3])
    
for eggrate in ratelst:
    egglst.append(math.ceil(eggrate * condition[0] * 0.01))
    
print(int(sum(egglst)))
```

## 問題描述

1.算出每天的產蛋率
2.算出每天產多少蛋
3.印出總和

用題目給的資料算出來都是對的，但不知道為什麼是 wrong answer...

**Comment by Viggochang** [comment]
`ratelst = [condition[1] - 1.5]` 這個設定有問題
如果第一天的產蛋率就低於最低產蛋率
則應該以最低產蛋率計算

**Comment by jingyutsao** [comment]
我修改過後還是wrong answer...

附上新的提交連結:
https://judge.ccclub.io/status/e162ba979b1da94734aaf30413bbc1de

**Comment by Viggochang** [comment]
你新的 code 裡寫到
`if condition[1] <= condition[3]:`
&ensp;&ensp;&ensp;&ensp;`print(int(condition[3] * condition[0] * 0.01 * condition[2]))`

這裡應判斷每日的產蛋數是否為小數，若有小數則無條件進位
處理好上述的問題後，才乘上天數

**Comment by jingyutsao** [comment]
完成了!!!非常感謝!

**Comment by Viggochang** [comment]
要記得 close issue 喔
