### ISSUE TITLE
[General] 5-1：翻箱倒櫃

### ISSUE THREAD

**Issue by chrisjan611** [coding-coworking-club/python-spring-2021#31]
## 提交連結

https://judge.ccclub.io/status/ce0a264ef83ec79b69a0d8f900553d57
## 程式碼

lst1=input()
lst2=input()
lst1=lst1.split(" ")
lst2=lst2.split(" ")
s=str(input())
(s in lst1) or (s in lst2)
```python

```

## 問題描述

在jupyter notebook上可以執行，但在Judge上無法。由於在lst1、lst2為字串的情況下in這個方法也是可以執行的，因此我無法確定我是否成功把lst1、lst2轉換成串列了。
嘗試把最後一行的lst1、lst2改成lst1.split(" ")、lst2=lst2.split(" ")也是失敗的，麻煩助教了，謝謝！

**Comment by TJ72** [comment]
lst.split(' ')有確實達到用間隔做分段轉存成list的需求了，但我感覺問題是出在 Judge系統是要求把判斷結果 print出來。

**Comment by TJ72** [comment]
另外 下次要把程式碼貼在指定的區域喔！

**Comment by chrisjan611** [comment]
真的是加print就成功了，我卡超久哈哈！
抱歉貼錯地方，謝謝助教解答。
