### ISSUE TITLE
[General] 綜2-6 合法括號窮舉

### ISSUE THREAD

**Issue by Din0-3** [coding-coworking-club/python-spring-2021#311]
## 提交連結
https://judge.ccclub.io/status/7641d3b1019e30abf7bfd62f16522f66

## 程式碼

```python

#初步篩選掉不可能變合法的括號
def chk_pr_lite(line):
    cnt = 0
    for i in line:
        if cnt < 0:
            break
        if i == '(':
            cnt += 1
        elif  i == ')':
            cnt -= 1
    return (cnt >=0 )

#檢查括號的合法性
def chk_prent(line):
    cnt = 0
    for i in line:
        if cnt < 0:
            break
        if i == '(':
            cnt += 1
        elif  i == ')':
            cnt -= 1
    return (cnt == 0 )


n = int(input())*2

lst = [""]

for _ in range(n):
    temp_lst= []
    for i in range(len(lst)):
        if chk_pr_lite(lst[i]+"("):
            temp_lst.append(lst[i]+"(")
        if chk_pr_lite(lst[i]+")"):
            temp_lst.append(lst[i]+")")
    lst = temp_lst


output = []

for each in lst:
    if chk_prent(each):
        output.append(each)
    else:
        continue
        
for i in (sorted(output)):
    print(i)

```

## 錯誤訊息

time limit exceeded 

## 問題描述

因為定義是要n組括號，所以是輸出一組有2n個字元，每個字元都是`(`或是`)`的字串，原則上有2 ^ 2n 次方種可能性。我一開始用2次方窮舉爆memory，嘗試了幾次節省空間都沒效，所以只好改用一個一個字元一邊生成一邊篩選的方式解。

在input x 2 = n 之下，第一層for loop 決定要輸出n次，每次都嘗試在list中已有的元素後面加上`(`或是`)`，並用第一個函數初步檢查合法性，因為如果明顯有`)`在前面則不可能合法，只留下有希望的字串，重複這個過程直到完全輸出。

第二個個函數則是檢查合法性，最後留下合法的字串才放進要output的list裡面
至於排序的部分，因為`(`本來就比`)`前面所以直接`.sorted()`

修正之後沒有爆memory了，但是還是time limit exceeded，想不出還可以怎麼optimize 。請幫忙看看，感謝～

**Comment by TJ72** [comment]
可以試試看用深度優先搜尋(depth first search)來實作這題喔～

**Comment by Din0-3** [comment]
不好意思
爬了一些文章，概念上可以理解但是要寫有點無從下手的障礙
想請問有推薦閱讀的資源嗎～

**Comment by TJ72** [comment]
我覺得可以找一些實體的範例看一下 code 要怎麼寫，或是在 Youtube 上也會有一些教學影片可以幫助下手

**Comment by Din0-3** [comment]
好的～
感謝🙏
