### ISSUE TITLE
[Homework 2] 小仔追盜賊

### ISSUE THREAD

**Issue by imkjkj** [coding-coworking-club/python-spring-2021#314]
## 提交連結

https://judge.ccclub.io/status/e74a2a14ecd985d0a0c14773e5e93639

## 程式碼

```python
a=input()
res=[]    #設定一個空的串列用來接初步整理過後的字串
half=["," , "." , ";" , ":"]    #把半形的符號設定成一個串列
while a != "end":    #只要輸入end就結束
    for i in a:
        if res == []:
            res.append(i) #第一個字串不管是什麼都放到串列res中
        elif (i in half) and i == res[-1]:    
            continue  #第二個之後的每個字串如果是和前一個字串是相同半形符號的話就跳過不放到res串列裡
        elif (i != res[-1] and res[-1] in half) or (i not in half and res[-1] in half):
            res.append(" ")  #如果當前的字串是半形符號且和前個字串不同(例如: ":"和",")時，先加一個空格再把後面的半形符號加到res串列
            res.append(i)
        else:
            res.append(i)  #如果字串是文字或空白就直接加入res字串
    res.append("\n")  #每段密語結束後加入換行符號
    a = input()  #繼續輸入下一段密語

res = res[0:-1]  #不要取到最後一個換行符號

#如果最後一個字串是半形符號再後面加入一個空白
if res[-1] in half:
    res.append(" ")

#確保每個半形符號後面只有一個空白
res2=res[0:2]  #設立一個新串列res2預設為res串列的前兩的字串
for m in range(2,len(res)):
    if res[m] == " " and res2[-2] in half and res2[-1] == " ":
        continue  #當前的字串的空白且上上個字串是半形符號且上個字串是空白時就跳過不把當前字串加到res2串列中
    else:
        res2.append(res[m])  #如果沒有半形符號後面接著兩個空白的情況則直接把當前的字串加到res2串列


#移除開頭的空白
k=0  #k預設為0
while k<1:
    if res2[k] == " " and k == 0: #若開頭的第一個字串是空白
        res2 = res2[1:]  #則跳過第一個字串
        k = 0  #持續檢查第一個字串是否是空白
    else:
        k += 1  #直到第一個字串不是空白就結束這個while迴圈

#在藏身地前後加入反斜線
res3=res2[0:2]  #設立一個新的串列res3預設為res2串列的前兩個字串
for j in res2[2:]:
    if j == "地" and res3[-1] == "身" and res3[-2] == "藏":  #若當前字串為"地"且前個字串為"身"且前錢個字串為"藏"
        res3.insert(-2, "\\")  #則在倒數第二個index的地方插入反斜線
        res3.append(j+"\\")  #再把"地"加到res3串列，之後再加入另一個反斜線
    else:
        res3.append(j)  #若沒有出現"藏身地"則持續把res2串列字串加到res3串列

print("".join(res3))  #把串列連接成字串後輸出
```

## 錯誤訊息

judge系統顯示Runtime error

## 問題描述

測試的兩組sample都是正確的，而且line上其他前輩提供的測試資料譬如 a    a!!:    :,,, 也是正確的，但系統仍顯示runtime error，不知道是哪邊出錯或什麼條件沒考慮到？ 需要求救各位大大了，感謝！

**Comment by chianshianli** [comment]
(非助教 僅供參考)
1. 輸入大寫 END 為結束，不是小寫 end
2. 如果最後一個字串是半形符號再後面加入一個空白這邊應該要去掉(?，我自己是特地把這狀況下後面的空白去掉了，有 AC
3. 你的 code 如果一行一行輸入應該都是對的，但如果一次輸入多行而且遇到第二行以後是空白的狀況就會錯誤，可以試試下面這個：
    I have a pen...       ;;;;,,,,
a   a!!:   :, , 
    I have a pen...
END
你會發現第三行開頭的空白沒去掉，可以把你的 code 丟去 python tutor 跑看看應該可以理解原因。

加油！祝早日 AC

**Comment by imkjkj** [comment]
感謝chianshianli大大指點了一盞明燈！
以下根據chianshianli大大的建議修改原本的程式碼，另外增加了 #移除第二句以後的密語開頭的空白 這個段落，測試之後第二行以後的開頭空白可以成功去掉，但現在judge系統卻變成了wrong answer，需要各位大大再幫忙指點迷津，非常感恩！

附上連結
https://judge.ccclub.io/status/a2a15f02d1b649e4d489abe0dfb8a783

**Comment by Peterorr** [comment]
@imkjkj 
請問你方便把上述程式碼按照 [github 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036) 修正一下嗎？
這樣助教會比較好協助你，可以的話也一併附上提交連結喔！

**Comment by imkjkj** [comment]
感謝提醒！先附上提交連結，感謝！

**Comment by Peterorr** [comment]
@imkjkj 
本題題意就是基於一個 while loop ，進行各項文字處理及判斷的題目，
而你在 while 內外都有 input()，代表你特別處理了 `第一次輸入`，
並且在 while loop 之外才開始進行文字處理，表示程式預期至少都要有一行輸入。
如果今天使用者直接輸入 END，是不是程式就出錯了呢？

目前整個程式架構看起來是遇到一個條件就寫個迴圈或判斷式處理，
可讀性會稍微低一些，要試圖把整個程式流程重構一下，會比較容易找出問題及調整。

祝你 debug 順利，歡迎繼續討論喔～
有空再看的參考資料：https://blog.niclin.tw/2020/02/29/readable-code-1/

**Comment by imkjkj** [comment]
感謝助教！目前有依照助教建議以及作業的提示修改了一版，但還是無法accept，不知道還有哪邊沒有考慮到，需要請再助教提點，感恩～～

附上連結
https://judge.ccclub.io/status/f14214f31a1b9db6e1a6917a31a8aa88

**Comment by Peterorr** [comment]
@imkjkj 
你有確認每一行後面的空白都被清除了嗎？可以直接用去除前後空白的指令～請 Google!
`去除後面的空白` 那邊，若 `each_line_adjust3` 本身就是一個空白字元呢？
自己重新手刻的話要注意邊界條件喔！

**Comment by imkjkj** [comment]
謝謝助教，已經成功accept! 感謝提點！
