### ISSUE TITLE
[General] 6-1：因數

### ISSUE THREAD

**Issue by Jenny950638** [coding-coworking-club/python-spring-2021#324]
## 提交連結

https://judge.ccclub.io/status/9c1526ecc49d6f814a193800d00e7c9f
## 程式碼

```python
n = input(int())
    for i in range(1,n+1):
            if n % i ==0 :
                print(i)
```

## 錯誤訊息

Compile Error
Sorry: IndentationError: unexpected indent (solution.py, line 2)
## 問題描述

一開始先input一個整數，再製造一個迴圈，用變數i帶入這個迴圈，只要數入的數字可以整除i,代表i是這個數因數，因此輸出，而i變數的範圍從1開始到n+1結束，但是最後結果跑不出來，不知道是不是有條件沒考慮清楚，麻煩大家及助教了!感恩~~

**Comment by Viggochang** [comment]
請補上提交連結，細節請參考[github 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)

**Comment by Jenny950638** [comment]
不好意思，已補上了喔，感謝!

**Comment by Viggochang** [comment]
空格有問題
for 前面不用空格
if 前請空四格

**Comment by TJ72** [comment]
會出現 Compile Error 是因為第二行 for 迴圈不應該縮排的地方縮排了(unexpected indent)！
通常需要縮排的地方只有：
1. for-loop(while-loop) 內的運算
2. if/elif/else 判斷式內的運算
而且縮排請固定空 4 個空格就可以囉！
所以照上面的 code 格式應該要這樣縮排：
```python
for i in range(1, n+1):
    if n % i == 0:  # 這行縮 4 個空格
        print(i)        # 這行再縮 4 個空格
```
然後上面的 code 還有一個地方需要注意，就是 python 預設輸入的資料類型是 `str`，妳第一行是想把輸入的資料型態轉變成 `int` ，所以應該是要用 `int(input())` 才對喔～如果還不熟悉建議可以分開來寫～

**Comment by Jenny950638** [comment]
好的了解了，感謝助教們!!
