### ISSUE TITLE
[Homework 2] 小仔養豬

### ISSUE THREAD

**Issue by CKJK47** [coding-coworking-club/python-spring-2021#327]
## 提交連結

https://judge.ccclub.io/status/63e3a20c55e4ec2b0df68e1632f1fdd5
## 程式碼

```python
variable = [int(n) for n in input().split()]
x = variable[0]
y = variable[1]
r = variable[2]
d = variable[3]

#把每一行裝進一個大的list
Big_list = []
for i in range(y + 1):
    s = [int(n) for n in input().split()]
    Big_list.append(s)

#建立母豬的座標uv_list，以及小豬的座標ij_list
uv_list = []
ij_list = []
B = 0
S = 0
for i in range(len(Big_list)):
    for j in range(len(Big_list[i])):
        #母豬數量B
        #遇到0就紀錄母豬的座標u, v
        if Big_list[i][j] == 0:
            B += 1
            uv_list.append([i, j])
        #小豬數量S
        #遇到非0就紀錄小豬的座標i, j
        else:
            S += Big_list[i][j]
            ij_list.append([i, j])
        
#印出第一行答案
print(B, S, sep = ",")    

#判定小豬是否在母豬四周，要把符合的小豬數做相加並存入一個surrounding的串列
surrounding = []
#對每一個母豬的座標檢驗
for a in uv_list:
    #把每一個小豬座標都帶入公式看是否在母豬周圍
    cnt = 0
    for b in ij_list:
        #index為0是x座標，index為1是y座標
        if (a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2 <= r ** 2:
            cnt += Big_list[b[0]][b[1]]
    surrounding.append(cnt)
<img width="1164" alt="截圖 2021-04-04 下午11 35 02" src="https://user-images.githubusercontent.com/79802408/113513909-63670780-959e-11eb-9a6f-6c2bc9322577.png">

for n in surrounding:
    ans = 1
    if (n / S) * 100 > d:
        ans = 0
        break
print(ans)
```

## 問題描述

1. 步驟按註解
2. 把數量都裝進一個大的list
3. 遇到0就母豬數+1，非0就加上小豬數量，並分別記錄座標
4. 對每個母豬座標檢驗，符合在周圍就把小豬數相加，並把最後相加的數字都裝進surrounding串列
5. 對surrounding串列檢驗，只要有一個>密集度，迴圈就停止且ans = 0
6. 測資都對，但是顯示runtime error

**Comment by yichensu** [comment]
@CKJK47 可思考 ans 如何正確宣告，以及第四步創新串列是否有必要性（提示：雙層回圈內外要怎麼放可以多思考）

**Comment by CKJK47** [comment]
> @CKJK47 可思考 ans 如何正確宣告，以及第四步創新串列是否有必要性（提示：雙層回圈內外要怎麼放可以多思考）
助教好：
想請問外圈放母豬、內圈放小豬這樣的邏輯是否有錯誤？因為我的想法是同一個點的小豬，是有可能同時在兩個母豬點周圍，所以我以每一個母豬點當起點，去算周圍的總小豬數，算完再換下一個母豬點。
(Hint提示外圈放小豬是避免小豬被重複計算，可是依題意小豬本來就有可能被同時算到多個母豬點的周圍)
另想請問迴圈內外顛倒放是否會在這一題影響運算？因為我目前測資都是正確的

**Comment by yichensu** [comment]
@CKJK47 延續你的思考，的確小豬可能在多隻母豬旁邊，可以進一步思考如何避免重複計算（提示：迴圈可以不用跑完）；目前測資雖然正確，但surrounding開始就可能造成錯誤，會有比創串列更簡潔與避免錯誤的方法，ans 的宣告也要多思考變數創建的基本原則。

**Comment by CKJK47** [comment]
@yichensu 
不好意思我還是不太懂為什麼會有錯誤QQ
如果每隻母豬都跑一次，而且每跑一次之前我都有把cnt歸零再對周圍的小豬進行加總，這樣應該不會計算到重複的小豬
另外在最後ans的部分，改成if...else...這樣的語法是正確的嗎？謝謝

**Comment by CKJK47** [comment]
仍未得到解答，不好意思

**Comment by yichensu** [comment]
@CKJK47 單就你的做法本身沒有太大的錯誤，但可以思考一下會不會造成surrounding產生空值。另外，可以試著思考為何建議迴圈內外層的放法跟你所想不同，會讓你需要少做很多步驟並避免現在這個問題。
