### ISSUE TITLE
[General] 小明去爬山

### ISSUE THREAD

**Issue by jennifer090** [coding-coworking-club/python-spring-2021#329]
## 提交連結

https://judge.ccclub.io/status/426e30ba0397ce5c7f43741f7cb45c2c

## 程式碼

```python
a=int(input())  #先存有幾個區
ans=[]
i=0
while i<a:  #跑每個區
    f=int(input())
    list1=[]
    t=0
    while t<f: #跑每區的每個路線
        list1.extend(input().split(','))
        t+=1
    height=[int(k) for k in list1[::3]]  #將同一區的高度 涼亭 廁所 資訊分別存成3個list
    rest=list1[1::3]
    bath=list1[2::3]
    sum1=sum(height) #先把山的高度算出來(sum1)
    if 'True' in rest[0:4] and 'True' in bath[0:4]:  #如果開始到第一個涼亭和廁所的距離小於300m 則繼續，若否跳到else sum1=-1
        for l in rest:  #檢查每涼亭
            if l=='True':
                c=rest.index(l)
                rest.insert(c,'*')
                rest.remove(l)
                if 'True' in rest[c+1:c+4] or c>=(len(rest)-4): #如果最後一個True離終點少於300m(據點總數-3，但又因為c為index 所以再減一)則也給過
                    continue
                else:
                    sum1=-1  #只要一有不正確sum1的值就不是高度而是被改成-1並結束迴圈
                    break
        for u in bath:   #檢查廁所
            if u=='True':
                c=bath.index(u)
                bath.insert(c,'*')
                bath.remove(u)
                if 'True' in bath[c+1:c+4] or c>=(len(bath)-4):
                    continue
                else:
                    sum1=-1
                    break
    else:
        sum1=-1
    ans.append(sum1)
    i+=1
far=sorted(ans)  #由小到大排所有的路線
if far[-1]==-1:      #如果連最大的值都是-1則代表沒有可以的路線，print(stay at home)
    print('stay at home')
else:
    for f in far:
        if f!=-1:  #出現第一個不是-1且最小的值則印出來並結束迴圈
            print(ans.index(f))
            break
```

## 錯誤訊息
WA

**Comment by TJ72** [comment]
我看了上面的程式碼有發現幾個可能造成 WA 的問題：
1. 題目好像沒有說到 "第一個個據點一定要有涼亭根廁所" 這個條件
2. 第 16 行的 for-loop index 是用 i ，我不確定會不會造成最外層 while-loop 迴圈 index 的干擾
3. 判斷廁所和涼亭的距離條件好像不太對耶～建議可以參考一下 #220 底下的討論串～

**Comment by jennifer090** [comment]
> 我看了上面的程式碼有發現幾個可能造成 WA 的問題：
> 
> 1. 題目好像沒有說到 "第一個個據點一定要有涼亭根廁所" 這個條件
> 2. 第 16 行的 for-loop index 是用 i ，我不確定會不會造成最外層 while-loop 迴圈 index 的干擾
> 3. 判斷廁所和涼亭的距離條件好像不太對耶～建議可以參考一下 #220 底下的討論串～

前面兩個我改正了，感謝!但是我修改了第三個，還是WA。
我改成1. 先檢查前一開始前三個位置據點是否有涼亭(從開始後300m內是否有True)(如果有，進下個條件，沒有就直接out) 
2.用for 迴圈找True 的位置，從最前面的開始，遇到第一個True，用*把他替換掉(避免重複index值永遠為最小)，再從那個位置往前取3個據點(距離這個涼亭300m內是否有至少一個涼亭)，如果這3個據點有任意一個值為True 或是 這個True 的index 值大於總據點數-3(最後一個True離終點小於300m)則繼續，若不符合則out，迴圈Break
完整的程式碼我重新改在上面了，再麻煩助教了

**Comment by TJ72** [comment]
不太懂為什麼要把 'True' 用 '*' 替換掉耶！替換了 "300公尺內是否有涼亭與廁所" 的條件不就會因為前面的 'True' 被替換而沒辦法正確判斷嗎？如果要判斷 300公尺距離的條件，應該只要用一個 for-loop range 從 0～據點數-2，看自己與下兩個據點是否有 'True'，應該這樣就可以解決題目的要求了～

**Comment by jennifer090** [comment]
> 不太懂為什麼要把 'True' 用 '*' 替換掉耶！替換了 "300公尺內是否有涼亭與廁所" 的條件不就會因為前面的 'True' 被替換而沒辦法正確判斷嗎？如果要判斷 300公尺距離的條件，應該只要用一個 for-loop range 從 0～據點數-2，看自己與下兩個據點是否有 'True'，應該這樣就可以解決題目的要求了～

抱歉，我看了很久還是不太懂助教您的解釋，您的意思是 用一個 for-loop range 從 0～據點數-2，去看 「每一個」據點前面兩個據點是否有True 還是「每個True 」前面兩個據點是否有True? 
至於我的解法是，因為我記得串列如果有很多相同的東西，如果要求這個東西的index會被限在index最小的那個數字，但因為迴圈是從頭開始跑，所以我的想法是先找True，定位(用*"換掉)在看True 前面兩個據點(用index定位)是否有true(前面那兩個還是True，迴圈還沒跑到哪裡，所以不會被替換)，是的話就繼續，然後下一個會被替換的就是符合前一個300m內的True，這樣能確保兩涼亭至少300m內， 但我改了還是不太行，還是說我理解錯助教的意思了，麻煩了～

**Comment by TJ72** [comment]
抱歉～我一開始看太快了orz 妳的方法應該也是可以的～ Runtime Error 是因為第 30, 31 行的串列 rest 在複製的時候沒有改到

**Comment by jennifer090** [comment]
感謝助教的耐心回復!!!但是...

> 抱歉～我一開始看太快了orz 妳的方法應該也是可以的～ Runtime Error 是因為第 30, 31 行的串列 rest 在複製的時候沒有改到

謝謝助教耐心讀了這麼久，真的非常感激!!，但是改了這個部分還是WA(抱歉占用助教這麼多時間)，我在想是不是距離的關係，300m內應該不包含300m吧，所以應該是找True 下面的兩個據點而不是3個吧?

**Comment by TJ72** [comment]
第 19 行和第 29 行的 `c>=(len(rest)-2):` 和 `c>=(len(bath)-2)` 不太對～至於你上面的問題，我覺得照上面程式的邏輯找 "True" 下面 3 個據點有沒有 "True" 是對的沒錯喔～

**Comment by jennifer090** [comment]
> 第 19 行和第 29 行的 `c>=(len(rest)-2):` 和 `c>=(len(bath)-2)` 不太對～至於你上面的問題，我覺得照上面程式的邏輯找 "True" 下面 3 個據點有沒有 "True" 是對的沒錯喔～

助教說的那部份我改完了！但系統還是給wa ，我想了很久還是想不到問題出在哪....

**Comment by TJ72** [comment]
我建議把串列的 index 寫下來，然後想想怎麼取 "True" 後面三個 element 和最末端的第三個 element 的 index 怎麼取。其實 WA 的原因真的就在第 21、31 行的判斷

**Comment by jennifer090** [comment]
> 我建議把串列的 index 寫下來，然後想想怎麼取 "True" 後面兩個 element 和最末端的第三個 element 的 index 怎麼取。其實 WA 的原因真的就在第 21、31 行的判斷

助教不好意思，因為你前面說找True 下面3個據點，可是這邊說True後面兩個element，我有點不太清楚這兩個是不是同樣的意思，我覺得我最不懂的地方是到底是300m內是指，3個據點(200m)還是4個(300m)，再麻煩助教了，謝謝!!

**Comment by TJ72** [comment]
抱歉～上一則回覆是 typo，照妳 code 的邏輯要找 True 後面 3 個 element。然後我發現在第 15 行的起始條件 index 也是錯的。這些 index 的地方確認清楚應該就可以 AC 了！加油～

回到妳的問題：從現在的位置(0)，往下走 3 個據點的話，應該是 300 m 喔

**Comment by jennifer090** [comment]
AC了!!!!!非常感謝助教耐心跟我討論這麼久～學到了很多!!
