### ISSUE TITLE
[General]8-4：最大公因數

### ISSUE THREAD

**Issue by jennabanana** [coding-coworking-club/python-spring-2021#336]
## 提交連結

https://judge.ccclub.io/status/bdbd3e6b754cca6053b8ecf7012802b1

## 程式碼

```python

def gcd(a,b):
    if a>b:
        smaller=b
    else:
        smaller=a
    for i in (smaller,0,-1):
        if a%i==0 and b%i==0:
            return i
l1=[int(a) for a in input().split(" ")]
l2=[int(b) for b in input().split(" ")]
final_ans=[]
for x,y in zip(l1,l2):
    ans=gcd(x,y)
    final_ans.append(ans)
print(final_ans)
```

## 錯誤訊息

![截圖 2021-04-05 下午4 33 53](https://user-images.githubusercontent.com/80043361/113555156-ffd7eb00-962c-11eb-93f0-e472329be156.png)

## 問題描述

在jupyter裡是顯示if a%i==0 and b%i==0這一行為zero division error，想請問為何會有zero division error的問題？或哪裡出錯？謝謝！

**Comment by TJ72** [comment]
因為 for 迴圈忘了加上 range 了～如果妳只寫 `for i in (smaller, 0, -1):` 的話，相當於從裝著 smaller, 0, -1 的 tuple 裡面取值，所以 Jupyter 才會有 zero division error 的錯誤訊息
