### ISSUE TITLE
[Homework 1] 吉吉印方形

### ISSUE THREAD

**Issue by Lienwuuu** [coding-coworking-club/python-spring-2021#34]
## 提交連結

https://judge.ccclub.io/status/8da1fc9d1becdd23b981e01e0f0f23e5

## 程式碼

```python
num = int(input())
space = num-2
print( "*" *num)
print( ("*" + " "*space +"*" + "\n") * space , sep="", end="" )
print( "*" *num)
```

## 問題描述

在jupyter上測試可行
但是在judge上是錯誤答案
不曉得哪裡出錯了呢?

我的想法是:
output的第一行跟最後一行會有跟input數字一樣多的星號
中間有input數字-2行，每行是頭尾各一個星號，中間有input數字-2的空格

**Comment by alvisyjchen** [comment]
可以試試看 num = 1 的狀況哦～

**Comment by Lienwuuu** [comment]
疑問已解決，感謝回覆!
