### ISSUE TITLE
[General] 完全平方數 II

### ISSUE THREAD

**Issue by jasonluo07** [coding-coworking-club/python-spring-2021#340]
## 提交連結

https://judge.ccclub.io/status/f32eeaa6776af84de6f95fe8979511c3

## 程式碼

```python
a, b = [int(i) for i in input().split()]

if a > 0:
    pass
else:  # a <= 0:
    a = 0

count = 0
for i in range(a, b+1):
    for j in range(0, i+1):
        if i == j**2:
            count += 1
            break
print(count)
```

## 錯誤訊息

Time Limit Exceeded

## 問題描述

測資都正確，trace code 也都覺得沒什麼太大問題，不知道是哪邊出了問題QQ

**Comment by TJ72** [comment]
試試看有沒有辦法用一層迴圈就解決你的問題(或是不用迴圈也可以)

**Comment by jasonluo07** [comment]
> 試試看有沒有辦法用一層迴圈就解決你的問題(或是不用迴圈也可以)
助教你好，我寫一個迴圈還是會 Time Limit Exceeded

```python
a, b = [int(i) for i in input().split()]

if a > 0:
    pass
else:  # a <= 0:
    a = 0

count = 0
for i in range(a, b+1):
    if int(i ** 0.5) ** 2 == i:
        count += 1
print(count)
```

**Comment by TJ72** [comment]
sorry～原來一層迴圈也過不了 Judge。那要不要試試看：算大於等於下界的最小完全平方數和小於等於上界的最大完全平方數，然後再用兩個數的根號相減就好

**Comment by chianshianli** [comment]
> > 試試看有沒有辦法用一層迴圈就解決你的問題(或是不用迴圈也可以)
> > 助教你好，我寫一個迴圈還是會 Time Limit Exceeded
> 
> ```python
> a, b = [int(i) for i in input().split()]
> 
> if a > 0:
>     pass
> else:  # a <= 0:
>     a = 0
> 
> count = 0
> for i in range(a, b+1):
>     if int(i ** 0.5) ** 2 == i:
>         count += 1
> print(count)
> ```

我也有用到 ``` if int(i ** 0.5) ** 2 == i: ``` 這但會出現
TypeError: can't convert complex to int
請問你也會嗎？

**Comment by jasonluo07** [comment]
> > > 試試看有沒有辦法用一層迴圈就解決你的問題(或是不用迴圈也可以)
> > > 助教你好，我寫一個迴圈還是會 Time Limit Exceeded
> > 
> > 
> > ```python
> > a, b = [int(i) for i in input().split()]
> > 
> > if a > 0:
> >     pass
> > else:  # a <= 0:
> >     a = 0
> > 
> > count = 0
> > for i in range(a, b+1):
> >     if int(i ** 0.5) ** 2 == i:
> >         count += 1
> > print(count)
> > ```
> 
> 我也有用到 `if int(i ** 0.5) ** 2 == i:` 這但會出現
> TypeError: can't convert complex to int
> 請問你也會嗎？

我的沒有出現這個問題耶

**Comment by chianshianli** [comment]
> > > > 試試看有沒有辦法用一層迴圈就解決你的問題(或是不用迴圈也可以)
> > > > 助教你好，我寫一個迴圈還是會 Time Limit Exceeded
> > > 
> > > 
> > > ```python
> > > a, b = [int(i) for i in input().split()]
> > > 
> > > if a > 0:
> > >     pass
> > > else:  # a <= 0:
> > >     a = 0
> > > 
> > > count = 0
> > > for i in range(a, b+1):
> > >     if int(i ** 0.5) ** 2 == i:
> > >         count += 1
> > > print(count)
> > > ```
> > 
> > 
> > 我也有用到 `if int(i ** 0.5) ** 2 == i:` 這但會出現
> > TypeError: can't convert complex to int
> > 請問你也會嗎？
> 
> 我的沒有出現這個問題耶

後來發現是我讓負數開根號了！修正就沒問題了～謝謝！
