### ISSUE TITLE
[Week 2] 停車費

### ISSUE THREAD

**Issue by NTNU-CYY** [coding-coworking-club/python-spring-2021#35]
## 程式碼

```
ti = str(input("請輸入入場時間"))
to = str(input("請輸入出場時間"))
tt = str(input("是否有台大證件(Y/N)"))

ti1 = int(ti[0:2])
ti2 = int(ti[3:])

to1 = int(to[0:2])
to2 = int(to[3:])

if to1 >= 24:
    to1 = 23

pt = (to1*60+to2) - (ti1*60+ti2)

if pt % 30 == 0:
    ptm = (pt / 30)*20
else:
    ptm = (pt // 30)*20 + 20

if tt == "Y":
    if ptm <= 20:
        pptm = 0
    else:
        pptm = ptm/2
else:
    pptm = ptm

print(int(pptm))


```

## 問題描述

我用jupytar notebook測試，答案都是對的
但系統都顯示wrong answer

[W2_停車費_未pass.txt](https://github.com/coding-coworking-club/python-spring-2021/files/6090004/W2_._.pass.txt)

**Comment by TJ72** [comment]
可以先請你幫我把 input()括號裡的字串刪掉後再重新丟 Judge嗎？Judge系統的 input()是不能丟預設字串的喔！

**Comment by TJ72** [comment]
然後下次請記得幫我把程式碼貼在指定的區域喔。

**Comment by NTNU-CYY** [comment]
謝謝助教，我試過之後，都OK了！

（之後我會記得把程式碼貼到對的區域！謝謝助教提醒～～）

智元


TJ72 <notifications@github.com> 於 2021年3月5日 週五 下午8:14寫道：
