### ISSUE TITLE
[Homework 2] 小仔追盜賊

### ISSUE THREAD

**Issue by diyo140906** [coding-coworking-club/python-spring-2021#355]
## 提交連結

https://judge.ccclub.io/contest/31/problem/05

## 程式碼

```python
single=[]
words=[];
s=input();
while s!="END":
    for i in s:
        single.append(i);
    words.append(single);
    single=[]
    s=input();

#處理重複標點符號：
for i in words:
    for j in range(len(i)):
        if(j==len(i)):
            break;
        if(i[j]==".") or (i[j]==":") or (i[j]==",") or (i[j]==";"): 
                while (i[j]==i[j+1]):
                    del i[j+1];
                    if((j+1)==len(i)):
                        break;

#處理單獨標點符號(維持後面一個空格)：                   
for i in words:
    for j in range(len(i)):                        
        if(j+1==len(i)):
            break;
        if(i[j]==".") or (i[j]==":") or (i[j]==",") or (i[j]==";"):
            while(i[j+1]==" "):
                del i[j+1];
                if((j+1)==len(i)):
                    break;
            i.insert(j+1," ")            

#處理空白：
for i in words:
    while i[0]==" ":
        i.remove(" ");
    while i[-1]==" ":
        i.pop();

#處理藏身地：
place=[];
s=0;
for i in words:
    for j in range(len(i)):
        if(i[j]=="藏"):
            if(i[j+1]=="身"):
                if(i[j+2]=="地"):
                    place.append(j);
    for n in place:
        i.insert(int(n+s),"\\");
        s+=1;
        i.insert(int(n+3+s),"\\");
        s+=1;

#最終輸出：
for i in words:
    print("".join(i));
```

## 錯誤訊息

![wrong](https://user-images.githubusercontent.com/20159565/113749486-4bc58580-973c-11eb-84e5-223cf9e43adf.png)

## 問題描述

解題：主要是先將輸入的所有字串，全部拆成單獨字元儲存於words中，再依據題目需求針對需修改的部分依序做處理。
1.重複標點符號：使用for迴圈先找出有半形的位置，若後面有連接重複的半形，則使用while迴圈依序delete。
2.標點符號後的單獨空格：一樣使用for迴圈先找出有半形的位置，將連接在它之後的空格先全部刪除，最後再補一個空格在它後面的位置。
3.前後空白刪除：前面的空格使用remove消除，後面的空格則使用pop，兩者皆有用到while迴圈。
4.增加斜線在藏身地前後：先用for迴圈和if條件先找出有連續出現藏身地三個字的位置，將所有位置的index(這裡使用「藏」字的位置)，先儲存於另一個list，再用這個list的位置資料，直接去insert反斜線；因增加斜線後會使後面的字元往後移，因此insert的時候有稍微將list的資料稍做調整。

問題：測資過後沒有問題，但不確定是哪裡有缺漏。

**Comment by nick30924** [comment]
我剛剛用你的程式輸入"....,"就不行了，我發現在第十四行會取不到值，應該改成j == (len(i) - 1)，因為這個例子最後會讓i串列變成含有兩個元素，使len(i) == 2，所以當j == 1也就是取最後一個值的時候，應當要break卻沒有正常的停止。

如果還是不行的話，你可以試試看輸入一行就輸出一行的方式，若輸出的一行不為END則照著規則輸出，若為END就什麼都不輸出並且結束程式。我自己的程式是以一問一答的方式寫的有獲得AC，也許你可以改改看你的迴圈成一問一答的方式試試看？ （我不是助教所以只是猜測這會不會也是原因ＱＱ，也有可能有其他沒發現的地方）

**Comment by diyo140906** [comment]
感謝Nick大大!
我有嘗試過把那行改成j == (len(i) - 1)，雖然輸入"....,"可以過，但"...."卻突然不行，後來發現因為兩者在進入while迴圈出來後，一個是len==1，一個len==2，所以當j==1的時候，一定會有其中一個不符合所以沒辦法break，所以我改成j >= (len(i) - 1)，之後兩邊都可以過了。
最後我也把程式改成你說的輸入一行輸出一行的方式，也成功AC了!
你是救星!

**Comment by Viggochang** [comment]
基本上 **一行一行輸出** 或 **一次全部輸出** 都是可以的~
@diyo140906 若問題已解決，請記得關閉問題喔！
