### ISSUE TITLE
[General] 小明的電話簿

### ISSUE THREAD

**Issue by cc5324** [coding-coworking-club/python-spring-2021#369]
## 提交連結
https://judge.ccclub.io/status/c57e35de1c8f43d15b237e4086106f25

## 程式碼

```python
tele_book = {}
to_search = []
ans = []
new = input()

while True:
    if new == "end":
        break
    elif new[0] == "a":
        temp_list = []
        temp_list = new.split(" ")
        tele_book.update({temp_list[1]:temp_list[2], temp_list[2]:temp_list[1]})  #以利查詢，故將{姓名:電話}、{電話:姓名}兩種形式都加入字典
        new = input()
    elif new[0] == "s": #建立待搜尋的list，以利後續查詢、輸出
        temp_list = []
        temp_list = new.split(" ")
        to_search.append(temp_list[1])
        new = input()

for i in to_search:
    if i in tele_book:
        print(tele_book[i])
    else:
        print("Cannot find"+" "+i)
```

## 問題描述

試過題目給的sample，輸出結果是相同的，但在judge上卻是WrongAnswer~!
自己也有另外做測資，但都沒有找到癥結點，
所以想請大家幫忙看看可能是哪裡有問題，（或是有我未注意到的規則? ）感謝!!

**Comment by TJ72** [comment]
在 Judge 裡的電話簿操作是有順序的，之後才登記到的資料，在前面查詢應該是要輸出 "Cannot find 人名/電話號碼" 的。所以如果你全部輸入完再一起處理輸出的話，就沒辦法按照操作順序輸出結果

**Comment by cc5324** [comment]
> 在 Judge 裡的電話簿操作是有順序的，之後才登記到的資料，在前面查詢應該是要輸出 "Cannot find 人名/電話號碼" 的。所以如果你全部輸入完再一起處理輸出的話，就沒辦法按照操作順序輸出結果

我懂了，在前面每筆輸入後，就要直接進行操作，按照這個方式修改後AC了，感謝~
