### ISSUE TITLE
[General] 揪狼殺

### ISSUE THREAD

**Issue by CKJK47** [coding-coworking-club/python-spring-2021#370]
## 提交連結

https://judge.ccclub.io/status/aa0c1e6c4a92ad2b2371f91105802354
## 程式碼

```python
#先製作一個函式，輸入為一個任選0點～23點的串列，希望回傳一個字典，並按照(1) 連續整點的時間長度 (2) 起始時間 排列
def pick(X):
    ans = {}
    current = X[0]
    v = current
    length = 1
    for i in range(1, len(X)):
        if X[i] - v == 1:
            length += 1
            ans[current] = length
            v = X[i]
        elif X[i] - v != 1:
            ans[current] = length
            length = 1
            current = X[i]
            v = current
    return sorted(ans.items(), key = lambda x: (-x[1], x[0]))

n = int(input())
time = {}
count = 0
while count < n:
    count += 1
    t = [int(i) for i in input().split()]
    #製作一個time字典{時間(0點～23點): 人數}，只要輸入的時間有在字典則人數+1，沒有就新增
    for key in t:
        if key in time:
            time[key] += 1
        else:
            time[key] = 1
#如果人數<12，就排列time字典，按照人數多的在前面排列
if n < 12:
    sol = sorted(time.items(), key = lambda x: -x[1])
    #印出排列的第一個sol[0]之中的時間[0]
    print(sol[0][0])
#如果人數>= 12的狀況，就先把value >=12 的時間key都挑出來加入sol串列中    
else:
    sol = []
    for key in time:
        if time[key] >= 12:
            sol.append(key)
    #把時間串列遞增排序，會長成[0,1,2,3,6,7,8,10,14,15,16...]的樣子
    sol = sorted(sol)
    #運用一開始的函式把sol丟進去回傳一個字典，並按照最長時間、起始時間進行排序，最後印出字典第一個的時間
    print(pick(sol)[0][0])
```

## 錯誤訊息

<img width="1204" alt="截圖 2021-04-08 下午5 05 20" src="https://user-images.githubusercontent.com/79802408/113999421-9ce48f00-988c-11eb-9a23-58913ab35e00.png">

## 問題描述

1. 步驟按註解
2. 使用測資測試都對，自己也測了幾組都沒什麼問題，但找不太到問題在哪裡
3. 函式效果如圖
<img width="682" alt="截圖 2021-04-08 下午5 26 23" src="https://user-images.githubusercontent.com/79802408/114002650-a3283a80-988f-11eb-945d-7ed9b331f0ef.png">

**Comment by CKJK47** [comment]
<img width="586" alt="截圖 2021-04-08 下午5 21 46" src="https://user-images.githubusercontent.com/79802408/114001853-e8983800-988e-11eb-853c-427c99479f35.png">
函式效果如圖

**Comment by TJ72** [comment]
上面的 code 中你好像沒有考慮到 "回報人數超過12人，但大家都有空的時間裡人數沒有超過12人"的情況，所以沒有特定的時間被加入 sol 串列中

**Comment by CKJK47** [comment]
> 上面的 code 中你好像沒有考慮到 "回報人數超過12人，但大家都有空的時間裡人數沒有超過12人"的情況，所以沒有特定的時間被加入 sol 串列中

AC了，謝謝助教
