### ISSUE TITLE
[Homework 3] 小明上菜啦 II

### ISSUE THREAD

**Issue by circleyuan22** [coding-coworking-club/python-spring-2021#377]
## 提交連結
https://judge.ccclub.io/status/f2715789934867b95de839b0f56c9368

## 程式碼

```python
menu = {}
try:
    while True:
        a = input()
        if menu.get(a, False):
            print(f"{a} already exists")
        else:
            d = {}
            for i in a:
                low_i = i.lower()
                d[low_i] = d.get(low_i, 0) + 1 
            exist = False
            for j in menu:
                if menu[j] == d:
                    print(f"{a} is {j}, {j} already exists")
                    exist = True
                    break
            if not exist:
                menu[a] = d
                print(f"Create {a}")
except:
    pass
```

## 錯誤訊息
![Screenshot from 2021-04-11 23-37-49](https://user-images.githubusercontent.com/80245641/114310876-f9f77380-9b1e-11eb-8486-4e2b4f6b44ab.png)

## 問題描述
1. 題目似乎沒寫清楚何時結束 input，想問程式該如何結束？（看到很多同學都是 `TimeLimitExceeded`）
    - 有試過不指定 Error 類型，或是輸入一行 input 就印一行 output
2. 想問是全部 input 完再一次印，還是輸一行印一行？

謝謝。

**Comment by sam7k9621** [comment]
1. 第一題是在考不定數量的輸入，這在week5的隨堂練習有出現過
2. 都可以

**Comment by circleyuan22** [comment]
> 第一題是在考不定數量的輸入，這在week5的隨堂練習有出現過

我這邊有用上課教的 `try...except` 了，可是還是 TLE，想問是可能還有其他地方寫錯嗎？試了很久都沒過...
謝謝！

**Comment by sam7k9621** [comment]
TLE 一般來說是代表你執行時間太久，不一定是錯
但是你要想辦法優化他，類似概念可以參考week6 字母麥片

**Comment by circleyuan22** [comment]
感謝助教，AC 了
