### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by Din0-3** [coding-coworking-club/python-spring-2021#38]
## 提交連結
https://judge.ccclub.io/status/857e13d6787aba34ef510ebe5db34912

## 程式碼

```python

buy_coke=int(input())
exchange=int(input())
bottle=buy_coke
drink_coke=buy_coke

while bottle >=exchange :
    drink_coke += bottle//exchange
    bottle = bottle//exchange
    bottle += bottle%exchange
    
print(drink_coke)

```

## 錯誤訊息

Time Limit Exceeded
Time: 2007ms Memory: 8MB Lang: Python3 Author: dinowsy@gmail.com

## 問題描述

在寫這題的時候一直遇到time limit exceeded
題目給我的感覺像是考while loop，因為照這個條件會進行多少次是不確定的，重複領可樂的圈數可以是數以萬計不太可能窮舉。
但是題目給的時間是1000ms，而我試了幾次都會到2000ms左右然後就跳time limit exceeded
不知道是不是我對題意理解錯誤希望我們不要用loop的寫法？還是我對loop不熟所以有什麼地方弄錯時間才會不夠
感謝

**Comment by cyhsieh264** [comment]
使用迴圈這個思路沒什麼問題，不過在用 while loop 的時候要特別注意迴圈何時終止，可以想看看是否有一些情境會讓執行條件永遠成立，而導致迴圈一直跑下去。

另外可能要注意 `%` 這個運算子的使用，若是 `1 % 2` 會一直得到 `1`（ 1 除以 2 的商數為 0，餘數為 1）。因此如果是規定每 2 個空瓶就可以換 1 瓶可樂，那麼在你的程式當中 `bottle >= exchange` 這個條件永遠會被滿足，迴圈就會一直執行下去。

可以再整理一下各個變數所代表的含義，重新思考如何設計迴圈的執行與終止條件～

**Comment by Din0-3** [comment]
感謝！
