### ISSUE TITLE
[Homework 3] 小明上菜啦 II

### ISSUE THREAD

**Issue by yolingyang** [coding-coworking-club/python-spring-2021#384]
## 提交連結

    
https://judge.ccclub.io/status/3901f585fe79a31d3fafcf2bec65395a

## 程式碼

```   
def count(word): #計算一個字串裡面每個母字出現次數
    char = {}
    word = list(word.lower())
    for a in word:
        if a not in char:
            char[a] = 1
        else:
            char[a] += 1
    return char

def if_same(word1, word2): # 判斷兩個字串每個字母出現次數是否相同
    if count(word1) == count(word2):
        return True
    else:
        return False

receipe = []
while True:
    food = input()
    repeat = 0 # 跑 receipt list 迴圈，如果任一字串和 input 的字母出現次數一樣的話，就會 repeat + 1，也會用 this 來記住是哪個字和 input 一樣
    for r in receipe:
        if if_same(food,r) == True:
            this = r
            repeat += 1
    if repeat > 0:
        print(food, "is", this, end = "")
        print("," ,this, "already exists")
            
    else:
        print("Create", food)
        receipe.append(food)
            

```

## 錯誤訊息

  
Runtime error  

## 問題描述

  
如同程式上的備註，一開始先建立兩個 function 分別計算一個字串每一字母（不分大小寫）出現的次數，另一個 function 判斷兩個字串是否字母出現次數相同  
接下來 receipe 這個 list 來紀錄已經建立握的菜單、以及建立一個無窮迴圈（因為題目沒有說在什麼情況下會結束），每次都會 input `food`    
再透過上面的 if_same function 判斷 food 是否已存在於 receipe 內，印出相對應文字  
資測兩筆都 ok，不確定哪邊有問題～再麻煩了！謝謝

**Comment by tcwang76** [comment]
妳自己也說明了妳寫的是無窮迴圈，
妳的程式沒有設計一個可以停下來的機制，即使 input 已經跑完了程式也停不下來，
所以才會出現 runtime error 的訊息。

可以回想一下之前練習過的隨堂練習裡面 "不知道要輸入幾行" 這題是怎麼處理的。
(在這裡就先不直接告訴你答案了)

**Comment by yolingyang** [comment]
@tcwang76     
謝謝你的回覆～  
有把 input 那邊改為當 input 非空值時才會執行（參考 `Week 6 - 書碼編輯`）   
但還是一樣 runtime error 😭 
https://judge.ccclub.io/status/f62ff5a0a939d4265d4f8101614a50b8  
```  
food = input()

while food != "":
    repeat = 0
    for r in receipe:
        if if_same(food,r) == True:
            this = r
            repeat += 1
    if repeat > 0:
        print(food, "is", this, end = "")
        print("," ,this, "already exists")
            
    else:
        print("Create", food)
        receipe.append(food)
    food = input()
```

**Comment by tcwang76** [comment]
@yolingyang
"[week 6 書碼編輯](https://judge.ccclub.io/problem/193401)" 程式停止的條件是當最後一次 input == 0 的時候，
跟這題不一樣，為什麼不參考 "[不知道要輸入幾行](https://judge.ccclub.io/problem/203202)" 這一題呢...?

judge 在讀取測資時是讀入一個檔案，
所以當讀完檔案最後一行之後就會產生一個 "EOF Error (End-of-File Error)"，
試試看利用這個 error 來設定讓程式跳出無限迴圈的條件吧。

**Comment by yolingyang** [comment]
@tcwang76     

你好，我有用 `try except` 來跳出無限迴圈，目前錯誤訊息變成是 time limit exceeded. 不知道是哪邊可能導致效能太差，再麻煩提點了～謝謝        
https://judge.ccclub.io/status/3f81803390f26530c068cad39e70eea4

我的作法改成是：   
把不重複料理名稱存在 `receipe` 這個 dictionary，   
key 是第一次出現的名稱、value 是每把每個字母/中文字轉為小寫、sort 過的 list （透過 `organized` 這個 function）    
所以每次有個新的 input 都會去執行 organized function，看輸出的值有沒有已經在 receipe.values() 來判斷是否重複     
```  
#小明上菜拉 II
def organized(word):   #return list，將 word 包含的字母轉為小寫 + 排序後存成 list    
    lst = [char for char in word.lower()]
    return sorted(lst)

def get_key(val):
    for key, value in receipe.items():
        if val == value:
            return key

receipe = {}  #存取不重複的料理名稱  


while True:
    try:
        food = input()
        if food != "":
            if food in receipe:  # 如果名稱一模一樣   
                print(food, "already exists")

            elif organized(food) in receipe.values():  # 如果 organized()後一模一樣    
                print(food, "is", get_key(organized(food)), end = "")
                print("," ,get_key(organized(food)), "already exists")


            else:  # 不重複的料理名稱  
                print("Create", food)
                receipe[food] = organized(food)
    except:
        break 
```

**Comment by huaitzu** [comment]
@yolingyang TLE 的問題可以參考 #416 進行修改～
