### ISSUE TITLE
[Homework 1] 吉吉印方形

### ISSUE THREAD

**Issue by jimmy97332** [coding-coworking-club/python-spring-2021#39]
## 提交連結

https://judge.ccclub.io/status/898332764f9e3f973957f944161b71a0
## 程式碼

```python
num = int(input())
a = num-2
print( "*" *num)
for i in range(a):
    print("*" + " "*a +"*" )
print( "*" *num)
```

## 問題描述

在jupyter notebook可以執行成功，
在作業系統wrong anwser。
想法是頭尾直接印出倍數，中間用迴圈印出n-2個，print裡面有設計n-2個空白。

**Comment by andykuo0956** [comment]
偶不是助教
我把程式碼複製IDE上執行是正確的，點ㄋ的連結進去狀態也是AC（？

**Comment by andy90303** [comment]
我原本也寫得跟你一樣 但檢查後發現這樣寫如果num是1的話就錯了

**Comment by alvisyjchen** [comment]
可以考慮 num = 1 的情況，思考讓變數都維持在正整數的寫法。
