### ISSUE TITLE
[Homework 3] 小明上菜啦 II

### ISSUE THREAD

**Issue by sqark912** [coding-coworking-club/python-spring-2021#391]
## 提交連結
https://judge.ccclub.io/status/e1c4668d8b43b9bfe18b627f27b104da

## 程式碼

```python
menu = {}  #設一個空菜單字典
while True:
    try:
        n = input()  #EX:雞包紙ABC
        n1 =sorted([str(i) for i in n.lower()])  #將input轉成list  #[雞,包,紙,a,b,c]
        new = True #設定flag
        for key in menu:  #針對input 檢查是否在菜單裡
            if n.lower() == key.lower():  #EX: 雞包紙ABC 雞包紙abc 雞包紙ABc 
                print(f"{n} already exists")  #“新料理名稱already exists”
                new = False  #有檢查到一樣的就break了
                break
            elif n1 == menu[key]:  
                print(f"{n} is {key}, {key} already exists")   #“舊料理名稱”, “舊料理名稱” already exists”
                new = False  #有檢查到一樣的就break了
                break
            else:
                continue
        if new == True:
            menu[n] = n1  #{雞包紙ABC : [雞,包,紙,a,b,c]}
            print(f"Create {n}") #“Create “新料理名稱””
    except:
        break
```

## 錯誤訊息

Wrong Answer

## 問題描述

已經有考慮不定行輸入的問題，測資也都對

不知道哪裡出了問題，再煩請助教解惑了!

**Comment by sam7k9621** [comment]
大小寫的判斷沒有符合我們的要求
你可以測測看這個
AA
Aa -> Aa is AA, AA already exists

**Comment by sqark912** [comment]
> 大小寫的判斷沒有符合我們的要求
> 你可以測測看這個
> AA
> Aa -> Aa is AA, AA already exists

是我會錯意題目了嗎?

我以為大小寫視為一樣，
所以如果菜色是AA，Aa是同一道嗎?
又因為他無須排列組合，所以我的code輸出了
AA→Create AA
Aa→Aa already exists

**Comment by sam7k9621** [comment]
建議再看一次sample2 的輸出

**Comment by sqark912** [comment]
> 建議再看一次sample2 的輸出

不好意思，我用我的code 把sample 2打進去
輸出的結果都是含答案相符的啊...
abc ab
->Create abc ab
aabb c
->aabb c is abc ab, abc ab already exists
aab,bc
->Create aab,bc
aa,bbc
->aa,bbc is aab,bc, aab,bc already exists
AA,BBC
->AA,BBC is aab,bc, aab,bc already exists
aa bb c
->Create aa bb c

還是我真的眼殘 拼錯字之類的...
再煩請協助了QQ

多試了一個AAV> 建議再看一次sample2 的輸出

不好意思，我用我的code 把sample 2打進去
輸出的結果都是含答案相符的啊...
abc ab
->Create abc ab
aabb c
->aabb c is abc ab, abc ab already exists
aab,bc
->Create aab,bc
aa,bbc
->aa,bbc is aab,bc, aab,bc already exists
AA,BBC
->AA,BBC is aab,bc, aab,bc already exists
aa bb c
->Create aa bb c

還是我真的眼殘 拼錯字之類的...
再煩請協助了QQ

多試了一個
AAB,bC
我的邏輯是" 因為大小寫視為一樣，且無須重新排列組合 "
應該輸出 “新料理名稱already exists”
我的code輸出→ AAB,bC already exists

**Comment by sam7k9621** [comment]
AA→Create AA
Aa→Aa already exists

這邊應該輸出 Aa -> Aa is AA, AA already exists

如同sample2裡面的
AA,BBC
->AA,BBC is aab,bc, aab,bc already exists
