### ISSUE TITLE
[General] 3-4：自己回文

### ISSUE THREAD

**Issue by chianshianli** [coding-coworking-club/python-spring-2021#4]
## 提交連結

https://judge.ccclub.io/status/f967bac7e97d35dd496bc86d2bdf8013

## 程式碼

```python
s = input()
print(s + s[::-1])
```

## 問題描述

這題解法是看 Udemy 上 Q&A 才會的，用了影片沒教的東西才解出來，請問這題用意就是希望學員自己 google 解決問題，還是有辦法用影片內容去解呢？

**Comment by TJ72** [comment]
回文的確是在商管女孩的教學影片中沒有提到，不過在星期四的課程中講師會補充其他字串好用的用法喔。
另外求救 Google大神我覺得也是很棒的解決方法！

**Comment by chianshianli** [comment]
瞭解！感謝回覆 🙇
