### ISSUE TITLE
[Week 2] 小仔填志願

### ISSUE THREAD

**Issue by Molly995** [coding-coworking-club/python-spring-2021#40]
## 程式碼

```python

```

## 問題描述

官網上提到關於每周隨堂練習:
- 讀書會隔天 23:59 前，請至 **Contests** 中作答。
- 在那之後，請至 **Problems** 中作答。

但在Problems中找不到"小仔填志願"這個題目，其他的隨堂練習都有找到。

**Comment by TJ72** [comment]
"小仔填志願"已經可以在**Problem List**中找到囉！感謝同學！
