### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by vickilovehippo** [coding-coworking-club/python-spring-2021#41]
## 提交連結

https://judge.ccclub.io/status/8a750cbee15a71ccf6e0111feaf0ce1d
## 程式碼

colabuy=int(input())
colacollect=int(input())  
freecola= colabuy//colacollect 
totalcola= colabuy+ freecola
if freecola<colacollect:
    print(totalcola)
else:
    while freecola >= colacollect: 
        freecola= freecola//colacollect 
        totalcola+=freecola
    print(totalcola)

```python

```

## 問題描述

我設定免費可樂數量超過規定集滿的空瓶數量後
就跑while迴圈 直到免費可樂數量不能再兌換
輸入sample input 得到正確的sample output
但仍顯示wrong answer 不知還有哪裡思考不足 再麻煩指點 謝謝

**Comment by cyhsieh264** [comment]
程式碼的部分沒有按照發文格式書寫，可能無法確認問題所在，請參考 [github 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036) 修改後再重新開啟提問。
