### ISSUE TITLE
[Homework 3] 小明上菜啦 II

### ISSUE THREAD

**Issue by Jane-lcy** [coding-coworking-club/python-spring-2021#416]
## 提交連結

https://judge.ccclub.io/status/3e355e2778c3dc634150bfef5c7a7823
## 程式碼

```python
dic = {} #原始的字典名稱{0:'紙包雞'}
dic_s = {} #重新排列比較的字典{'包機紙':0}
kv = 0

while True:
    try:
        name = input()
        if name in dic.values(): #菜名一模一樣
            print(name + ' already exists')
        else: #菜名不一樣
            name_l = name.lower() #轉換小寫
            name_ls =''.join(sorted(name_l)) #sorted轉成字串
            if name_ls in dic_s: #重新排列後菜名一樣
                print(name + ' is ' + dic[dic_s[name_ls]] + ', ' + dic[dic_s[name_ls]] + ' already exists')
            else: #完全不一樣菜名
                dic_s[name_ls] = kv
                dic[kv] = name
                kv += 1
                print('Create ' + name)
    except:
        break
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/79711028/115995715-ea902400-a60e-11eb-8685-977344e5c74d.png)

## 問題描述

測資都正確，但顯示Time Limit Exceeded，不曉得應該如何調整，謝謝

**Comment by tcwang76** [comment]
Time Limit Exceed表示妳的程式碼跑的時間太久，超過限制，
這主要是因為你雖然使用 dictionary 的結構，
可是 dic.values() 這個函式其實等於把 dictionary 裡面所有的 value 值轉換成一個類似於list的資料結構，
所以在判斷 if xxx in dic.values() 的時候還是要把整個 list 跑一次直到找到東西為止，仍然會超時。

至於妳的程式碼，其實已經有用排序過後的料理名稱作為 key 值放在 dic_s 裡面幫助判斷了，已經算是完成最重要的一部份！
建議可以把排序前的料理名稱作為 value 值存到同一個字典裡與 key 值做為對照，
這樣要判斷時只要用 dic[key] 就可以直接取到裡面的 value 值，避免使用 dic.values() 這個函式。

重點是 --->
先判斷這個料理名稱的排列組合是否已經出現在字典裡過，
再判斷已經出現過的這個排列組合，所對應已經在菜單上的料理名稱是不是一模一樣。

**Comment by Viggochang** [comment]
首先，建議你先簡化存資料的方式
可以用一個字典存資料就好，儲存的方式為 `dic_s = {name_ls: name}`
以排列過後的名字為key, 原本的名字為value

進行條件判斷時，如果使用 `if name in dic.values() ` 的話
python 會把 dic.values() 裡每個元素都檢查一遍看是否相等
這樣會造成時間太久

所以建議你可以為每個輸入的 name_input 都建立 name_ls_input
條件判斷時，可以用字典的取值方式去判斷

像是如果 `name_input == dic_s.get(name_ls_input) `
就代表 輸入的名字跟原本字典裡的某個名字一樣
`name_input != dic_s.get(name_ls_input) and dic_s.get(name_ls_input) != None` 
就代表 輸入的名字的組成存在字典，但名字不一樣

用get取值的話會快很多
