### ISSUE TITLE
[Homework 3] 小明上菜啦 III

### ISSUE THREAD

**Issue by Jane-lcy** [coding-coworking-club/python-spring-2021#417]
## 提交連結

https://judge.ccclub.io/status/5ac699cc9a7de59a1b01ccd135146b4e
## 程式碼

```python
import re
str1 = input().lower()
str2 = input().split(',')
for substr in str2:
    outstr = re.sub(substr.lower(), '', str1)  # 從小明印象中料理的名字上消去菜單上面殘留的詞彙
    str1 = outstr
if len(str1) == 0:
    print('True')
else:
    print('False')
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/79711028/115996056-650d7380-a610-11eb-9fae-5323ab7712c1.png)

## 問題描述

提供的測資都有正確，可是Judge上還是WA，不知道問題在哪裡，是否能多提供一些測資試試看呢?

**Comment by sam7k9621** [comment]
你是採用replace 的方法把出現過的字串取代
你可以想想看如果先出現了一個較長卻不會擺進去的子字串
然後後面是正確可以排進去的子字串會發生什麼事
