### ISSUE TITLE
[Homework 3] 小明上菜啦II

### ISSUE THREAD

**Issue by CKJK47** [coding-coworking-club/python-spring-2021#419]
## 提交連結

https://judge.ccclub.io/status/4028594acb65420472c3b7ae448e6ba8
## 程式碼

```python
s = input()
print(f"Create {s}")
menu = {}
menu[s] = ''.join(sorted(s.lower()))

while True:
    try:
        s = input()
        #輸入跟字典中的key完全一樣
        if s in menu:
            print(f"{s} already exists")
            break
        #設定ans = 0的條件
        ans = 0
        #對每一個menu中的key檢查，如果經過小寫+排序後跟s經過小寫+排序後相同
        for i in menu:
            if ''.join(sorted(s.lower())) == menu.get(i):
                print(f"{s} is {i}, {i} already exists")
                #ans = 1，不會進入下方的條件
                ans = 1
        #ans仍然為0代表從未出現過
        if ans == 0:
            print(f"Create {s}")
            menu[s] = ''.join(sorted(s.lower()))
    except:
        break
```

## 錯誤訊息

<img width="1177" alt="截圖 2021-04-28 下午4 48 41" src="https://user-images.githubusercontent.com/79802408/116375171-99b44180-a841-11eb-8968-b222fc948a5a.png">

## 問題描述

1. 步驟如註解步驟如註解
2. 測資皆正確
3. WA不知道是哪種邊際條件沒有考慮到

**Comment by sam7k9621** [comment]
測資沒有正確喔，請再檢查一次測資

**Comment by CKJK47** [comment]
> 測資沒有正確喔，請再檢查一次測資

Code已經修改過，測資應該也都正確，仍然WA

**Comment by sam7k9621** [comment]
請你再詳盡檢查一遍唷
測資仍然不正確

**Comment by sam7k9621** [comment]
麻煩再檢查一次，你的測資仍然不正確（提示：測資一）

**Comment by CKJK47** [comment]
<img width="397" alt="截圖 2021-04-29 下午2 35 43" src="https://user-images.githubusercontent.com/79802408/116510875-30433a00-a8f8-11eb-9ee1-8ab73c5a155f.png">
這是跑測資一出來的截圖，還是看不出哪裡不一樣...

**Comment by j84022814** [comment]
想請問您這樣的寫法，後來有發現為何不對嗎??

**Comment by CKJK47** [comment]
> 想請問您這樣的寫法，後來有發現為何不對嗎??

如果出現一模一樣的話，already exists之後就break，就無法再輸入了

**Comment by j84022814** [comment]
了解謝謝您 但如果不用break，使用elif s not in menu: ，跑去judge就會變成TLE

**Comment by CKJK47** [comment]
> 了解謝謝您 但如果不用break，使用elif s not in menu: ，跑去judge就會變成TLE

沒錯，我也跟你一樣遇到相同的狀況，所以後來我就放棄這個寫法改用其他邏輯寫了
