### ISSUE TITLE
[Homework 3] 小明上菜啦 III

### ISSUE THREAD

**Issue by chianshianli** [coding-coworking-club/python-spring-2021#420]
## 程式碼

```python
impression = input().lower  # 輸入印象中的菜名
remain = [i.lower() for i in input().split(",")  # 存殘餘片段

for i in remain:  # 把重複的詞換成空格
    impression = impression.replace(i.lower(), " ")
impression = impression.replace(" ", "") # 把空格改成空字串
if impression == "": 
    print("True")
else:
    print("False")

```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/18030336/116100235-517d0e00-a6df-11eb-9a11-363becdc19ce.png)

## 問題描述
想問為何會出現 AttributeError 以及如何改正，有 google 了但看不出所以然 😭 
而且看其他同學提問好像也有用到類似方法，但他們都沒出現錯誤。

**Comment by sam7k9621** [comment]
請參考 #417

**Comment by chianshianli** [comment]
@sam7k9621 助教我的問題是，為何其他同學至少還能跑出 WA 但我卻連跑都不能跑 @@

**Comment by sam7k9621** [comment]
impression = input().lower  # 輸入印象中的菜名

你在這邊漏掉了括弧，所以impression 變成是一個funciton而不是string

**Comment by chianshianli** [comment]
原來如此！謝謝助教～
