### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by yolingyang** [coding-coworking-club/python-spring-2021#43]
## 提交連結

    
https://judge.ccclub.io/status/60363a3fc9ea65567fd89bf0a8f3b922  

## 程式碼

```python  
# 總數 = total, 餘數 = leftover, 新可以兌換的 = new 

total = int(input())
market = int(input())

new = total // market
leftover = total % market
total += new

while True:
    if (new + leftover) // market > 0:
        leftover = (new + leftover) % market
        new  = (new + leftover) // market
        total += new
    else:
        break

print(total)  

```

## 錯誤訊息

  
Wrong Answer
Time: 22ms Memory: 8MB Lang: Python3 Author: yolingyang@gmail.com

## 問題描述

  
拿了兩個題目的範例測試都正確，原本想說是不是 while 迴圈問題（如果 `賣場規定需集滿的空瓶數量` = 0 or 1 的話會有問題）  
但如果是這樣，錯誤訊息應該是 `runtime error` 而不是 `wrong answer` 對嗎～

**Comment by alvisyjchen** [comment]
可以試試看 total = 5, market = 3 這筆測資，答案應該是 7。
