### ISSUE TITLE
[Homework 3] 小明上菜啦 II

### ISSUE THREAD

**Issue by Lucy-Ting** [coding-coworking-club/python-spring-2021#432]
## 提交連結

https://judge.ccclub.io/status/e17a47a711e8df4137d4b45ce3087c4b

## 程式碼

```python

oriname=[]
orires=[]
total={}
res = {}

while True:
    try: 
    
        b=input()
        oriname.append(b)
        bfix=b.lower()

        res={}
        for i in bfix:   
            if i not in res:
                res[i] = 1
            else:
                res[i] += 1      

        if oriname[-1] in total: #一模一樣的
            
            print(oriname[-1]+" already exists")
            

        elif res in orires:
                    
            print(oriname[-1]+" is "+oriname[orires.index(res)]+", "+oriname[orires.index(res)]+" already exists" )

                
        else:
            print("Create "+oriname[-1])
            total[oriname[-1]]=res

        orires.append(res) 
        
    except:
        pass
       
```

## 問題描述

放到judge上顯示TLE，但目前的版本已經是修正過的了，不確定還能從哪個部分去修改，麻煩助教指導了!

**Comment by tcwang76** [comment]
我先提醒你幾個比較明顯的問題好了，

1. 無窮迴圈
在 while 迴圈裡面使用 try-except 的用意，
是為了讓程式在讀完最後一行的輸入之後，可以跳出迴圈結束程式運行，
因此 except 裡面要接 break 才能跳出迴圈，使用 pass 的話只是跳過此步驟的意思，
又會重新回到 try 從頭開始跑，變成無窮迴圈。

2. 用 dictionary 取代 list
這題要改善程式運行的時間，就要盡量避免使用 list 儲存資料，
因為 list 的特性就是，不管是使用 for-loop 還是用 if xxx in list 的方法，
都是從 list 裡面的第一個物件看到最後一個，直到找到你要的東西為止，
這時如果儲存的資料量很龐大，取出來的次數及所花的時間就會很可觀。

     而字典因為沒有順序性，可以直接呼叫 key 值，一次就完成查找的動作，
     因此要盡量用字典呼叫 key 值的方式來避免使用 list。

     先試著不用 oriname 和 orires 這兩個 list 來儲存出現過的料理名稱及對應的排列組合吧。

3. 料理名稱排列組合的處理
提醒你如果先將每次的料理名稱重新排序，
理論上使用同一個排列組合的料理名稱們，經過排序後都會長得一模一樣，
你就不用用字典把每個使用過的字母及個數儲存下來了。
