### ISSUE TITLE
[Homework 3] 小明上菜啦 II

### ISSUE THREAD

**Issue by a119164** [coding-coworking-club/python-spring-2021#434]
## 提交連結

https://judge.ccclub.io/status/fd5bb69ba5d18c6cd5a2d437d02b5e12

## 程式碼

```python
name_list = []
sorted_name_list = []
lower_name_list = []
sorted_lower_name_list = []

while True:
    try:
        name = input()
        lower_name = name.lower()
        sorted_lower_name = sorted(lower_name)
        sorted_lower_name = ''.join(sorted_lower_name)
        sorted_name = sorted(name)
        sorted_name = ''.join(sorted_name)

        if (name in name_list):
            print(name + ' already exists')
            
        elif (lower_name in lower_name_list):
            num = lower_name_list.index(lower_name)
            print(name_list[num] + ' already exists')
            
        elif (sorted_name in sorted_name_list):
            num = sorted_name_list.index(sorted_name)
            print(name+' is '+name_list[num]+', '+name_list[num]+' already exists')
        
        elif (sorted_lower_name in sorted_lower_name_list):
            num = sorted_lower_name_list.index(sorted_lower_name)
            print(name+' is '+name_list[num]+', '+name_list[num]+' already exists')
        
        else:
            name_list.append(name)
            sorted_name_list.append(sorted_name)
            lower_name_list.append(lower_name)
            sorted_lower_name_list.append(sorted_lower_name)
            print('Create '+name)
            
    except:
        break
```

## 問題描述

測資都有過，但卻WA
我在猜可能是大小寫視為同一個名稱的問題
但我覺得我也都有考慮了...QQ

**Comment by hclpush** [comment]
1. 可以試試看以下測資：
- AAAAAAAAAAAAAAAAAAAAAAa\n
- aaaaaaaaaaaaaa\n
-  AAAAAAAAAAAAAAAAAAAAAAA\n
-  aaaaaaaaaaaaaaaaaaaaaaa\n
-  AAAAAAAaaaaaaaaAAAAAAAa\n
-  'aaaaaaaaaaaaaaaaaaaaBBB\n'

2. 建議使用字典解決TLE的狀況。key可以是輸入的字串，value可以是小寫後的輸入字串

**Comment by a119164** [comment]
## 提交連結

https://judge.ccclub.io/status/430b5311c72826be9b8eb2454c455a33

## 程式碼

可是如果改成
```python
# 小明上菜啦 II
name_list = []
sorted_name_list = []
lower_name_list = []
sorted_lower_name_list = []

while True:
    try:
        name = input()
        lower_name = name.lower()
        sorted_lower_name = sorted(lower_name)
        sorted_lower_name = ''.join(sorted_lower_name)
        sorted_name = sorted(name)
        sorted_name = ''.join(sorted_name)

        if (name in name_list):
            print(name + ' already exists')
            
        elif (lower_name in lower_name_list):
            num = lower_name_list.index(lower_name)
            print(name + ' already exists')
            
        elif (sorted_name in sorted_name_list):
            num = sorted_name_list.index(sorted_name)
            print(name+' is '+name_list[num]+', '+name_list[num]+' already exists')
        
        elif (sorted_lower_name in sorted_lower_name_list):
            num = sorted_lower_name_list.index(sorted_lower_name)
            print(name+' is '+name_list[num]+', '+name_list[num]+' already exists')
        
        else:
            name_list.append(name)
            sorted_name_list.append(sorted_name)
            lower_name_list.append(lower_name)
            sorted_lower_name_list.append(sorted_lower_name)
            print('Create '+name)
            
    except:
        break

```

助教您給的測資就會過了
但繳交到Judge上還是WA嗚嗚

**Comment by huaitzu** [comment]
> 可是如果改成
> 
> ```python
> # 小明上菜啦 II
> name_list = []
> sorted_name_list = []
> lower_name_list = []
> sorted_lower_name_list = []
> 
> while True:
>     try:
>         name = input()
>         lower_name = name.lower()
>         sorted_lower_name = sorted(lower_name)
>         sorted_lower_name = ''.join(sorted_lower_name)
>         sorted_name = sorted(name)
>         sorted_name = ''.join(sorted_name)
> 
>         if (name in name_list):
>             print(name + ' already exists')
>             
>         elif (lower_name in lower_name_list):
>             num = lower_name_list.index(lower_name)
>             print(name + ' already exists')
>             
>         elif (sorted_name in sorted_name_list):
>             num = sorted_name_list.index(sorted_name)
>             print(name+' is '+name_list[num]+', '+name_list[num]+' already exists')
>         
>         elif (sorted_lower_name in sorted_lower_name_list):
>             num = sorted_lower_name_list.index(sorted_lower_name)
>             print(name+' is '+name_list[num]+', '+name_list[num]+' already exists')
>         
>         else:
>             name_list.append(name)
>             sorted_name_list.append(sorted_name)
>             lower_name_list.append(lower_name)
>             sorted_lower_name_list.append(sorted_lower_name)
>             print('Create '+name)
>             
>     except:
>         break
> ```
> 
> 助教您給的測資就會過了
> 但繳交到Judge上還是WA嗚嗚

可以請你貼上你在 judge 提交這段程式碼的網址嗎？
另外這題建議你用字典處理，不然解決了 WA 會遇到 TLE 喔！
解題思路可以參考今晚釋出的 [HW3虛擬碼](https://www.notion.so/ccclub/HW3-Hint-d5bf1c6e9f0b4fa1bcf62085e102d722)

**Comment by a119164** [comment]
我付上網址囉
感謝助教
我想先解決WA嗚嗚我再來思考TLE的問題QQ

**Comment by huaitzu** [comment]
@a119164 
AAAAAAAAAAAAAAAAAAAAAAa
aaaaaaaaaaaaaa
AAAAAAAAAAAAAAAAAAAAAAA
aaaaaaaaaaaaaaaaaaaaaaa
AAAAAAAaaaaaaaaAAAAAAAa
aaaaaaaaaaaaaaaaaaaaBBB

以上這個測資還是沒有過喔><
像是輸入的第 3 行「AAAAAAAAAAAAAAAAAAAAAAA」
輸出應該要是「AAAAAAAAAAAAAAAAAAAAAAA is AAAAAAAAAAAAAAAAAAAAAAa, AAAAAAAAAAAAAAAAAAAAAAa already exists」
但你的程式碼跑出來會是「AAAAAAAAAAAAAAAAAAAAAAA already exists」

**Comment by a119164** [comment]
可是題目不是說大小寫視為一樣嗎
「大小寫視為同一道」
所以應該是要顯示already exists才符合題目的邏輯吧?

**Comment by sam7k9621** [comment]
題目的意思是同一道沒錯，也有說要提醒小明
但是完全一樣跟大小寫一樣的提醒方式不一樣
我們會再增加一個 sample 來提醒同學
