### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by Hongzhang0404** [coding-coworking-club/python-spring-2021#44]
## 程式碼

```python
b1= int(input())            #一開始買的可樂數量
reg_Col1= int(input())      #賣場規定兌換的可樂數量
s1=0                        #能喝到的總數量
r1=0                        #可樂瓶餘數
  
while (b1//reg_Col1 >= 1):
    s1+= b1
    r1+= b1%reg_Col1
    b1= b1//reg_Col1
    if (r1//reg_Col1 ==1):
        s1+=1
print(s1+b1)   


```

## 問題描述
您好，我測試sample給予的輸入值，輸出值也都相同，也考慮了其他學員說的剩餘瓶數，但是系統還是給我wrong answer，請問可能是哪裡出錯?

**Comment by alvisyjchen** [comment]
可以試試看輸入 b1 = 5, reg_Col1 = 3 當作測資，正確輸出應該是 7，再次思考程式裡面是不是有沒考慮到的條件。

另外，下次記得參照 Notion 中的學員須知 / GitHub Issue 使用教學，提交正確的連結哦

**Comment by Hongzhang0404** [comment]
## 提交連結
https://judge.ccclub.io/contest/25/problem/0101

## 程式碼

## 錯誤訊息
Wong Answer

## 問題描述
感謝回答，並以附上連結，
我已試輸入 b1 = 5, reg_Col1 = 3 當作測資，獲得7輸出，但還是wrong answer，請問還有可能哪裡出錯?

**Comment by cyhsieh264** [comment]
@Hongzhang0404 如果程式碼有更新，記得附上更新後的版本喔！

另外提交連結指的是，你提交答案後所產生的連結，而不是題目本身的連結。
可能要麻煩你修正發問內容，改完之後再點擊 `Reopen issue` 開啟提問，以便助教幫忙確認～

具體要怎麼找到連結請參考：[github 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)
