### ISSUE TITLE
[Homework 3] 小明上菜啦 II

### ISSUE THREAD

**Issue by ebony75310** [coding-coworking-club/python-spring-2021#450]
## 提交連結

https://judge.ccclub.io/status/7ccfd1a94e702ff3edd5ea67dfbdfcb2
## 程式碼

```dictionary1 = {}
dictionary2 = {}
c = ""
d = ""

while True:
    n = input()
    n_sort = sorted(n, reverse = False)
    n_sort = [i.upper() for i in n_sort if isinstance(i,str)]
    a = ""
    n_join = a.join(n_sort)
        
    if n in dictionary1:
        print(f"{n} already exists")
            
    elif n_join in dictionary2:
        d = dictionary2.get(n_join)
        print(f"{n} is {d}, {d} already exists")
            
    else :      
        print(f"Create {n}")   
            
        c = n
        dictionary1[n] = n_join
        dictionary2[n_join] = n

```

## 問題描述

測資兩項都可以過，也有額外設其他測資都可以，但結果顯示Runtime Error，不清楚有甚麼可以修改的方向

**Comment by ebony75310** [comment]
補充說明 : 我有看下面一些同學有加上try跟except的條件，但我自己試過還是Time Limit Exceed，想請問助教有沒有甚麼方法可以改善? 謝謝助教

**Comment by huaitzu** [comment]
你的程式碼裡有出現 dictionary1 和 dictionary2，但是你開頭只有定義 dictionary2，所以跑到 `if n in dictionary1:` 的時候就會 `NameError: name 'dictionary1' is not defined`

另外，你的程式碼沒有設定停止的條件，要運用 `try except` 來處理不定行輸入

最後 TLE 的部分可以參考 #416 進行修改～

**Comment by ebony75310** [comment]
我了解了，謝謝助教的回答 !
