### ISSUE TITLE
[Week 7] 資料比對

### ISSUE THREAD

**Issue by Din0-3** [coding-coworking-club/python-spring-2021#451]
## 提交連結

https://judge.ccclub.io/status/f327245ffa9d00d9771f6210695c0621

## 程式碼

```python
# 處理資料
import re

txt =[]
while True:
    try:
        txt.append(input())
    except:
        break

sept = txt.index("raw-data.txt")
l_data = txt[1:sept] #labeled data
r_data = txt[sept+1:] #raw data

# 建立查找的dictionary
convert = {}
for each_line in r_data:
    key = re.sub("[^A-Za-z\s]", "", each_line) 
    key = key.lower()
    convert[key] = each_line

# 輸出
for line in l_data:
    idx = line.index("\t")
    print(line[:idx + 1], end = "")
    try:
        print(convert[line[idx + 1:]])
    except KeyError:
        print(line[idx + 1:]) 



```

## 錯誤訊息
WA

## 問題描述

大致上分成三塊

input 的部分把資料輸入成一個list然後用分別取出label data 跟 raw data

接下來建立一個dictionary 來映射raw data 跟raw data處理後的樣子，使用regular expression把標點符號，即非`A-Za-z\s` 的刪掉，接著轉為小寫

最後針對每一筆label data先print 出包括`\t`之前的部分，然後`\t`之後的部分用dictionary 查找，有符合的就調岀raw data，不符合的就print原本的

不知道WA是否是對哪邊的題意理解有誤或是少做了哪個部分，感謝指點！

**Comment by TJ72** [comment]
在做 `raw data` 的字串處理時，漏保留數字了

**Comment by Din0-3** [comment]
原來如此
感謝！
