### ISSUE TITLE
[Homework 3] 小明上菜啦 II

### ISSUE THREAD

**Issue by ystliu** [coding-coworking-club/python-spring-2021#455]
## 提交連結

https://judge.ccclub.io/contest/40/problem/02

## 程式碼

```python
dishes = {}
dic = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

while True:
    try:
        s = input() 
        lower = []
        for i in s:
            if i in dic:
                lower.append(i.lower())
            else:
                lower.append(i)
        lower = sorted(lower)
        srtd = ''.join(lower)
        if srtd in dishes and s == dishes[srtd]:
            print(f"{s} already exists")
        elif srtd in dishes and s != dishes[srtd]:
            print(f"{s} is {dishes[srtd]}, {dishes[srtd]} already exists")
        else:
            dishes[srtd] = s
            print(f"Create {s}")
    except:
        break
```

## 錯誤訊息

runtime error
https://judge.ccclub.io/status/c1c3271b2c191d1be2cc2971eddf683d 
<img width="1135" alt="Screen Shot 2021-05-04 at 21 53 59" src="https://user-images.githubusercontent.com/80040647/117014374-5109f600-ad23-11eb-81a8-77a8a6324415.png">
## 問題描述

我自己用anaconda 跑起來是對的，但是不能交ＱＱ

**Comment by sam7k9621** [comment]
請附上正確的連結不是截圖
另外你的code 輸出不對，你確定你是交這份到judge？

**Comment by ystliu** [comment]
測試輸出多打一行，已經修正，不好意思

**Comment by sam7k9621** [comment]
你的寫法是對的不過應該是花太多時間？
要把輸入轉成小寫其實直接用lower() 就好不需要特別用for loop 吧？

**Comment by ystliu** [comment]
好的，謝謝助教
