### ISSUE TITLE
[General] 冠亞軍分數差

### ISSUE THREAD

**Issue by konichihuahua** [coding-coworking-club/python-spring-2021#46]
## 提交連結

https://judge.ccclub.io/status/e6818a619198955d15e7e42377e7781f
## 程式碼

```python
try:
  n=[int(a) for a in input().split()]
  a=max(n)

  while(1):
    n.remove(a)
    if n.count(a)==0:
      break

  b=max(n)

  print(a-b)

except:
  print(0)

```

## 錯誤訊息

Time Limit Exceeded

## 問題描述

為..什麼....會..超..時咧....

**Comment by TJ72** [comment]
亞軍的定義好像不太對喔！通常分數排第二的(即使跟冠軍同分)，不也是叫分占第一、二名嗎？
