### ISSUE TITLE
[General] 判定 list 中是否有出現 False

### ISSUE THREAD

**Issue by MichaelChou0806** [coding-coworking-club/python-spring-2021#464]
## 程式碼

```python
pool=[
   [0, True], [1, True], [2, False, False], 
   [3, True, False], [4, True, True], [5, False]
     ]
#pool為一個大 list，裡面還有6個小list包含index，及一至多個 bool
#最終想要檢定每個小list中, 若有出現 False 就判定為 False (即使包含 True)


#採用方法A: "在小 list 中用 find 語法找到 False 則判 False"
final_answer_A = []
for A in range(len(pool)):
    if False in pool[A]:
        final_answer_A.append(False)
    else:
        final_answer_A.append(True)
print(f"A, 用找的方法: {final_answer_A}")


#方法B: "計算小 list 中 False 的總量，大於0就判 False"
final_answer_B = []
for B in range(len(pool)):
    
    if pool[B].count(False)>0:
        final_answer_B.append(False)        
    else:
        final_answer_B.append(True)
print(f"B, 記數的方法: {final_answer_B}")
```

## 問題描述
output 為
A. 用找的方法: [False, True, False, False, True]
B. 記數的方法: [False, True, False, False, True]
(答案一樣)

想要請問...
為何第0個 [0, True] 會被判定為 False
且相同的包含一個 True 的 [1, True] 則正常判定為 True
而第5個 [5, False] 被判定為 True (應為 True)
(中間幾個都如預期的判斷)

ps. 用 count 語法計算 pool 中小 list 的 False
pool[0] = 1
pool[5] = 0
跟程式判斷結果一樣，但與預期的不同

**Comment by nick30924** [comment]
我不是助教，不過可以分享一下我的想法:
我剛剛試了一下，數字的0和1其實也是帶有bool意義的，如果串列中包含0，就表示False元素也在其中，若包含1則是表示True，這就解釋了為什麼[0, True]會被判定有False含在裡面，而[1, True]則都表現True的性質。
「而第5個 [5, False] 被判定為 True (應為 True)」你寫的output那邊只有五筆資料，這裡指的是第六筆(實際有跑六筆，index = 0~5)，跑出來有被判定為False，所以應該沒有問題。

**Comment by TJ72** [comment]
我記得凱文之前有補充過不同資料型態代表的 `bool `，其中在資料型態為整數時，`0 `代表 `False`，`1 `以上代表 `True`。我建議可以改成判斷 `False `是否在第二個元素後仍有出現 `pool[i][1:]`，應該就可以避免 index 為 0 的困擾了
