### ISSUE TITLE
[Homework 3] 小明上菜啦 II

### ISSUE THREAD

**Issue by emilyjenjen** [coding-coworking-club/python-spring-2021#465]
## 提交連結

https://judge.ccclub.io/status/73a32a34cb5daa30a91e7e95e4559704
## 程式碼

```python
menu_dict = {}
while True:
    line = input()
    if line:
        linelower = line.lower()
        menu_sorted = []
        for i in range(len(linelower)):
            menu_sorted.append(linelower[i])
        check = "".join(sorted(menu_sorted))
        if check not in menu_dict:
            print("Create " + line)
            menu_dict[check] = line
        elif check in menu_dict and menu_dict[check] == line:
            print(line + " already exists")
        elif check in menu_dict and menu_dict[check] != line:
            print(line + " is " + menu_dict[check] + ", " + menu_dict[check] + " already exists")
    else:
        break
```

## 問題描述

我的想法跟虛擬碼提示一樣。先將input每個字元切開，加到一個list，再將那個list sort好，再用“”.join()得到一個檢查的string（在此稱之為check）。如果check不在事先創立的字典menu_dict裡面（意即menu_dict沒有一個key是check）就創立一個key  = check然後他的value是input。（在此key要是已經lower了）。如果check已在事先創立的menu_dict中，那就檢查他是不是menu_dict[check]的value == input，如果一模一樣就print already exists。如果check在字典中，但value不等於input，則print input is check的value，check的value already exists。
有檢查測值都對，丟到judge卻runtime error，請問是哪裡沒考慮清楚嗎？謝謝！

**Comment by emilyjenjen** [comment]
已自行找到問題AC了：沒有打try except、for loop 寫法改成check = "".join(sorted(list(linelower)))
不過for loop明明感覺我原本的寫法也沒問題，不知道為什麼runtime error，可以麻煩助教幫忙解惑嗎？然後也有點不清楚我這個while迴圈打法沒有try except是為什麼不可行？

**Comment by sam7k9621** [comment]
然後也有點不清楚我這個while迴圈打法沒有try except是為什麼不可行？

針對這邊：如果我沒有理解錯的話你是想while loop 裡面要放 try except 對吧（看你問句是雙重否定XD）
因為我們的測資是不定行輸入，也就是要撞到EOF 才會停下來，如果不放try except 的話對程式而言他不知道何時該終止，就會變成無窮迴圈
