### ISSUE TITLE
[Homework 4] 推薦系統

### ISSUE THREAD

**Issue by CKJK47** [coding-coworking-club/python-spring-2021#466]
## 提交連結

https://judge.ccclub.io/status/a814598301ee94624678419a224c69d8
## 程式碼

```python
#threshold為相似度門檻
threshold = int(input())
#先創造每個人會買的東西的字典buy(input)
buy = {}
#recommend是最後建議要買的東西的字典(output)
recommend = {}
#order是想要創建商品出現的順序
order = []

#先定義計算相似度的公式，如果相似度超過設定閾值，就回傳True，反之回傳False
def similarity(s1, s2):
    if (len(s1 & s2) / len(s1)) >= (threshold / 100):
        return True
    else:
        return False
    
while True:
    try:
        s = input().split(" ")
        if s == ['end']:
            break
        else:
            #創造key為人名，value為買的東西的集合，的buy字典
            buy[s[0]] = set(s[1:])
            #只要商品沒出現過就新增進order內，同時也排出商品出現順序
            for i in s:
                if i in order:
                    continue
                order.append(i)
    except:
        break

#對每個人名跑迴圈
for i in buy:
    #ans為最後推薦要買的東西的集合
    ans = set()
    #對每個人名跑第二次回圈從頭檢查
    for j in buy:
        #如果對到同一個人就不做事
        if i == j:
            pass
        #對到不同人
        else:
            #如果相似度高於門檻
            if similarity(buy[i], buy[j]) == True:
                #計算兩個人買東西的差集difference，並將ans中還沒有的元素新增進ans中
                difference = buy[j] - buy[i]
                for k in difference:
                    ans.add(k)
    #最後把要推薦要買的東西存進recommend字典，key為人名，value為推薦的東西的串列
    #串列用order的順序index排列
    recommend[i] = sorted([m for m in ans], key = lambda x: order.index(x))
#最後輸出
for key in recommend:
    print(key + " ", end = "")
    print(" ".join(recommend[key]))
```

## 錯誤訊息

<img width="1047" alt="截圖 2021-05-08 下午10 06 42" src="https://user-images.githubusercontent.com/79802408/117542094-b9b9e100-b049-11eb-9ae3-04897aaccfd5.png">

## 問題描述

1. 步驟如圖註解，我是使用set解法
2. 原本有輸出順序的問題，現在已修正，跟測資相同但是仍然WA
3. 不知道是哪一步出問題...麻煩助教幫忙解惑><謝謝！

**Comment by amandayclee** [comment]
題目的說明有表示 「在輸出的第一行，我們先輸出凱文，**接著依照商品出現的順序**依序輸出要推薦給凱文的卡片、機車、番茄。」

所以在輸出的部分要想想看怎麼達成這個目的，用 set() 的確不會排序。

**Comment by CKJK47** [comment]
> 題目的說明有表示 「在輸出的第一行，我們先輸出凱文，**接著依照商品出現的順序**依序輸出要推薦給凱文的卡片、機車、番茄。」
> 
> 所以在輸出的部分要想想看怎麼達成這個目的，用 set() 的確不會排序z

> 題目的說明有表示 「在輸出的第一行，我們先輸出凱文，**接著依照商品出現的順序**依序輸出要推薦給凱文的卡片、機車、番茄。」
> 
> 所以在輸出的部分要想想看怎麼達成這個目的，用 set() 的確不會排序。

我已經修正排序問題，但是仍然WA，不知道是哪邊邏輯有誤，謝謝助教！

**Comment by amandayclee** [comment]
你排序的方式會有問題哦，因為你一個商品只有放入「第一次」出現的順序，但如果是對到不同的人名，商品出現的順序可能會不同，這個就沒有被考慮到。

小提醒～
目前整個架構看起來有蠻多可以省略的部分，ex. 是不是可以不用用到 bool function 就能判斷是不是要繼續推薦小明喜歡的商品給凱文？或者是不用特別因為提示裡面有提到，就先入為主使用 set()。很多步驟可以用已知且包含排序性質的方式去處理，不用想得太複雜！另外，若人名後面沒有任何推薦的物品，是沒有空白的呦。

**Comment by CKJK47** [comment]
AC了，謝謝助教！！
後來覺得函式不用寫太複雜，直接在外面做反而容易達到題目要求
