### ISSUE TITLE
[General] <selenium>動態爬蟲問題請教

### ISSUE THREAD

**Issue by 11087tim** [coding-coworking-club/python-spring-2021#468]
## 程式碼

```python
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
import time
'''open chrome by browser'''
browser = webdriver.Chrome("/Users/zhangshufen/Desktop/chrome/chromedriver")

default_url = "https://tw.tradingview.com/"
browser.get(default_url)  # send request
time.sleep(5)  # break for 5 secs

search_block = browser.find_element_by_class_name("tv-header-search__input js-header-search__input")
search_block.send_keys("2330")
button = browser.find_element_by_xpath("/html/body/div[2]/div[3]/div/div[3]/form/label/span/svg")
button.click()  # hit the button
search_block.clear()  # clear the search block'''
```

## 錯誤訊息

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/80166253/117528476-10e99280-b005-11eb-92f4-2020278fad8a.png">

## 問題描述

<錯誤重發>
就是，本人在嘗試用selenium進行動態爬蟲，但一直無法定位到正確的搜尋匡和執行搜尋的button，我很納悶。因為我明明已經使用開發者工具去定位我要的搜尋匡和搜尋鍵，但還是無法執行。
不知道是不是我定位錯的HTML碼，想請問各位有任何建議與指教可以分享嗎？？ thks

**Comment by hchbiggrass** [comment]
Selenium是模擬人類行為的爬蟲，所以在測試的時候請全程盯著開起來的瀏覽器分頁，看它的行為是否如同你的預期。這種作法類似之前用trace code看程式碼怎麼運作，知道它每個步驟在幹嘛才能找到錯誤。以這次的例子來說，我複製你的程式碼到自己電腦上面跑，發現有問題的地方是send_keys(2330)沒有作用，所以就算你在點進去的網頁有正確定位，如果連網頁都沒有進去就沒有可能定位成功了。另外，以我個人的習慣，使用Selenium就不會使用request和BeautifulSoup了。

**Comment by 11087tim** [comment]
謝謝助教的解釋，但延續剛剛的問題，我利用XPATH來找到搜尋的button但不曉得為什麼就是按不下去？？
嘗試按其他的按鍵就可以，但就是搜尋格中的搜尋見一直按不下去，因此想發問。

**Comment by hchbiggrass** [comment]
按鍵按不到的時候，根據我的經驗，用css定位點不到就改用xpath定位來點，這兩種總有一種可以點到。在你的情況，或許也可以直接模擬按Enter。
