### ISSUE TITLE
[General] 6-3：母音種類個數

### ISSUE THREAD

**Issue by Corgihsiao** [coding-coworking-club/python-spring-2021#47]
## 提交連結

https://judge.ccclub.io/status/9de4db963389fa930e61c0f9fdf2ec67
## 程式碼

```python
#輸入一個字串，輸出字串中母音種類個數（同樣字母大小寫視為不同）
a = input()
p= ["a","e","i","o","u","A","E","I","O","U"]

i = 0
n=1
total = 1
for i in range(len(a)):
    if int(a.count(p[i]))>1:
        int(a.count(p[i])) == (int(a.count(p[i]))//int(a.count(p[i])))
        total += int(a.count(p[i]))

    elif int(a.count(p[i]))==1:
        total += int(a.count(p[i]))

    i +=1
print(total)

```

## 問題描述

我用loop從 i=0 開始，重複母音的部分想透過assign變數等於除以自己來解決，這樣就確保他不管有沒有重複一定會是1
在jupyter上面不管是用sample或是測試其他字母都成功，但judge一直給我wrong answer。
麻煩各位解惑，感謝。

**Comment by TJ72** [comment]
在`for i in range(len(a))`我想你應該是想根據 list p的長度來跑這個 for-loop，如果是的話應該要用` len(p)`來跑喔！還有一個是一開始你初始化`total = 1`也不太對，我沒理解錯的話應該要初始化`total = 0`。

BTW 下次請提供正確的提交連結喔！
