### ISSUE TITLE
[Homework 3] 小明上菜啦 II 

### ISSUE THREAD

**Issue by david900825** [coding-coworking-club/python-spring-2021#470]
## 提交連結
https://judge.ccclub.io/status/a75b0cb94ddddb6de0174a20c470c020

## 程式碼

```python
#小明上菜啦第二題
dic = {}
sort = ""
while True:
    try:
        menu = input()
        little = sorted(menu.lower())
        for i in little:
            sort += i
        if dic.get(sort) != None:
            if menu == dic.get(sort):
                print(dic.get(sort),"already exists")
            else:
                print( menu ,end = ' ')
                print("is",end = ' ')
                print(dic.get(sort), end = ', ')
                print(dic.get(sort) ,"already exists")
        else:
            dic[sort] = menu
            print("Create", menu)
        sort = ""
    except:
        break
```

## 錯誤訊息
![截圖 2021-05-09 下午12 30 57](https://user-images.githubusercontent.com/79702248/117560672-6d5eb780-b0c2-11eb-84f4-846aabba5553.png)

## 問題描述
根據助教所說已經注意到在查找是否已存在於字典中時要用if key in dict 而非 for loop ，然而跑出來還是time limit exceeded，想詢問看看究竟哪邊出現錯誤呢？

**Comment by tcwang76** [comment]
如果有用到 dic.keys()、dic.values()、dic.items() 這些函數，
他們都會產生類似於 list 的資料結構，
所以一樣要把 list 裡面的元素一個一個拿出來檢查，
建議你參考 #416 這裡的解釋噢~

**Comment by david900825** [comment]
已經把程式碼改成助教說的那樣子了（更新在上面），利用dic.get()來找值，可是還是time limit exceeded，是哪裡沒有注意到嗎...謝謝助教指教了！

**Comment by sam7k9621** [comment]
在執行程式的時候把語句 print() 出來這件事其實是有點花時間的
比較好的習慣應該會是整理成一個字串，print() 一次就好喔
可以從這邊先檢查一下
