### ISSUE TITLE
[Homework 4] 小明上菜啦 IV

### ISSUE THREAD

**Issue by zoee22** [coding-coworking-club/python-spring-2021#473]
## 提交連結

https://judge.ccclub.io/status/e763255d4d202b2d1572ece0e005d661
## 程式碼

```python
def puzzle(wood):
    if sum(wood)%4!=0: #總長度不符正方形
        return False
    
    side_len=sum(wood)/4 #邊長
    chosen_wood=[] #被選到的木材長度
    left_len=side_len-sum(chosen_wood) #剩餘長度
    index=0
    for i in range(4): #問題點:只有一個list在輪，不知道要怎麼for4個邊(對到4個邊)
        if left_len==0: #若剩餘的長度=0，則一個邊選擇完成
            break
        elif left_len>=wood[index]: #若剩餘邊長>=已知，表可以選出已知、填補剩餘邊長
            chosen_wood.append(wood[index]) #把已知值加到chosen
            left_len-=wood[index] #新的剩餘邊長=原剩餘邊長-已知值
        else: #已知值裡都找不到填補剩餘邊長的長度(index已到最後)
            return False
            wood+chosen_wood #放回之前被選到的已知值
            left_len+=sum(chosen_wood) #把剩餘長度加回去

        del wood[index-1]
        index+=1
        while wood[index]==wood[-1] and sum(chosen_wood)==side_len:
            return True
        
inf=[int(num) for num in input().split(',')] #已知值
inf.sort(reverse=True)
print(puzzle(inf))
```

## 錯誤訊息

![未命名](https://user-images.githubusercontent.com/80198686/117576208-98bfc180-b117-11eb-98ef-6c40db354ecb.png)

## 問題描述

前提：參考了hint，但不是用try-except，用if-elif-else
問題：大概知道自己的問題是出在for i in range(4)那邊，像註解寫的，因為只有一個list，所以正方形各個邊選到的長度到最後都會全部放在這個list，有試過設4個list但似乎後面步驟要整個大改，也有想過在for-loop的最後清除list的資料，但不確定擺在哪裡、或會不會影響到其他地方，所以想請教可以怎麼改~?謝謝!

**Comment by sam7k9621** [comment]
我的建議會是：chosen_wood=[] #被選到的木材長度 
這個可以改成 選到的木材index，最後把選到的index 移除就好
另外：return False
            wood+chosen_wood #放回之前被選到的已知值
            left_len+=sum(chosen_wood) #把剩餘長度加回去

這邊你先return 惹所以不會執行後面的部分

**Comment by zoee22** [comment]
好的我試試!謝謝你!!
