### ISSUE TITLE
[Homework 4] 信箱地址檢查

### ISSUE THREAD

**Issue by CKJK47** [coding-coworking-club/python-spring-2021#475]
## 提交連結

https://judge.ccclub.io/status/5686ab47850db80098a667eb1842eace
## 程式碼

```python
import re

email = input().split(',')
ans = []
#使用re.match方式檢查
for i in email:
    #帳號部分
    #開頭一定要是英數字(1或多個)
    #[.+_-]只能出現其中一個(or不出現)，所以後面一定要接1~多個英數字，這樣的組合可以有1~多個
    
    #[@]只能出現一個
    
    #'@'後面一定要是英數字(1或多個)
    #把域名拆解成'.'加上1~多個英數字，這樣的組合可以1~多個
    #結尾一定要符合英數字
    if re.match('^[a-zA-Z0-9]+([\.|\+|\_|\-]?[a-zA-Z0-9]+)+[@]{1}[a-zA-Z0-9]+(\.[a-zA-Z0-9]+)+$', i):
        ans.append("True")
    else:
        ans.append("False")
print(ans)
```

## 錯誤訊息

<img width="1197" alt="截圖 2021-05-10 下午3 12 59" src="https://user-images.githubusercontent.com/79802408/117619741-365fd300-b1a2-11eb-9bbd-83d984dd1caa.png">

## 問題描述

1. 第一次使用re，目前judge上兩筆測資都對，不知道是哪邊邏輯有誤
2. 正規表達的邏輯已註解

**Comment by hchbiggrass** [comment]
你的程式有兩個問題：
1. 輸出的True和False是真假值，不是字串
2. 帳號也可以只有一個字
