### ISSUE TITLE
[Homework 3] 小明上菜啦 IV

### ISSUE THREAD

**Issue by cc5324** [coding-coworking-club/python-spring-2021#478]
## 提交連結
https://judge.ccclub.io/status/386b4fdf2847209172c293655055dc73

## 程式碼

```python
lumberlst = [int(x) for x in input().split(",")]
lumberlst = sorted(lumberlst, reverse = True)

def LumberPuzzle(lumberlst):
    if sum(lumberlst)%4 != 0:
        return False 
    side = sum(lumberlst) // 4 
    left = [side] * 4  #4個邊的剩餘邊長(待拼湊)
    for i in range(len(left)):
        picking = [] #當次迴圈所選擇的木材
        index = 0
        while True:
            if left[i] == 0: 
                break
            try: #由大到小，依序嘗試組合木材，若總和小於邊長，則繼續選擇下一根木材；若總和大於邊長，則先放回上一根木材，再選擇下一根木材
                if left[i] >= lumberlst[index]:
                    left[i] -= lumberlst[index]
                    picking.append(lumberlst[index])
            except IndexError: #(index超出lumberlst)index 走到底，都沒有找到合適的木材拼完
                return False
                picking.pop()  #(即放回上一根木材)
            index += 1 #(繼續選擇下一根木材)
        for l in picking:
            lumberlst.remove(l) #移除已使用的木材
    if sum(left) == 0:
        return True

print(LumberPuzzle(lumberlst))
```

## 問題描述
卡關太久QQ，最後還是借助助教的提示：
將木材由大到小排序，並依序嘗試組合木材，
若總和小於邊長，則繼續選擇下一根木材；若總和大於邊長，則先放回上一根木材，再選擇下一根木材。
直到確認index 走到底，都沒有找到合適的木材拼完（設定為index超出lumberlst）；
或者是總和 = 邊長，並四邊皆完成(剩餘邊長 = 0)。

嘗試了sample跟不同測資，在jupyter notebook上是對的，
但在judge上還是WrongAnswer，
不知道是否有特殊條件、測資是我沒有考慮到的，
再請助教、同學們指教了，感謝~~!

**Comment by sam7k9621** [comment]
你可以試試看這個：9,6,1,9,6,1,5,5,3,3,2,2,6,6
另外這邊：picking.pop()  #(即放回上一根木材)
我比較建議紀錄找到的index 最後把選到的index 對應的木柴刪掉就好

**Comment by cc5324** [comment]
> 你可以試試看這個：9,6,1,9,6,1,5,5,3,3,2,2,6,6
> 另外這邊：picking.pop() #(即放回上一根木材)
> 我比較建議紀錄找到的index 最後把選到的index 對應的木柴刪掉就好

謝謝你提供的測資跟建議!
根據這個從PyhtonTutor找到問題點，
按照原來的寫法

**Comment by cc5324** [comment]
> 你可以試試看這個：9,6,1,9,6,1,5,5,3,3,2,2,6,6
> 另外這邊：picking.pop() #(即放回上一根木材)
> 我比較建議紀錄找到的index 最後把選到的index 對應的木柴刪掉就好

謝謝你提供的測資&建議!!!!
根據這個找到了問題點，重新處理了"index 走到底，都沒有找到合適的木材拼完"的後續步驟。
