### ISSUE TITLE
[Homework 補交區] 14. 超商取貨

### ISSUE THREAD

**Issue by GaryLu1994** [coding-coworking-club/python-spring-2021#480]
## 提交連結

https://judge.ccclub.io/status/c9e282732745fd2378bd496a70859717

## 程式碼

storage = {}

while True:
    lst = [i for i in input().split(',')]
    if lst[0]=='end':
        break
    else:
        index = lst[0][7:] + ' ' + lst[1]
        storage[index] = lst[2]
        

while True:
    name = input()
    
    try:
        if name in storage:
            print(storage[name])
        else:
            print('Check again!')
    except:
        EOFError
        break

## 錯誤訊息

Runtime Error

## 問題描述

我先將前n行的進貨資訊用while迴圈存入字典
並將電話末三碼＋姓名作為字典的key
物品名稱作為value

之後在取值的時候
便可以直接比照輸入的末三碼＋姓名是否有在字典內
若是有在字典內
便直接印出對應的value
若是沒有則印出Check again!

但是不知道是哪一步驟導致Runtime Error

願助教指點迷津

**Comment by TJ72** [comment]
RE 的原因是 try / except 用法上的錯誤，關於 try / except 的用法，可以參考 ccClub 的 [medium 文章](https://medium.com/ccclub/ccclub-python-for-beginners-tutorial-edd15e2b5d1e)

**Comment by GaryLu1994** [comment]
可是如果是將EOFError放到 except 後的話
仍然顯示RE

https://judge.ccclub.io/status/b8012f04eb3ddac540f2e0f0a3810749

**Comment by TJ72** [comment]
你仔細看文章的話，應該會發現 while-loop 裡的 input 放的位置也不太對～
