### ISSUE TITLE
[General] 3*3矩陣相加

### ISSUE THREAD

**Issue by ghost** [coding-coworking-club/python-spring-2021#481]
## 程式碼

```python
A= [[1,3,5],[7,9,11],[13,15,17]]
B= [[9,8,7],[6,5,4],[3,2,1]]
N=3
C=[[0]*N for i in range(N)]
for i in range(N):
    for j in range(N):
        C[i][j]=A[i][j]+B[i][j]
        print(C)
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/52339710/117799245-79927280-b284-11eb-8613-769e25b7eb1b.png)
![image](https://user-images.githubusercontent.com/52339710/117799279-83b47100-b284-11eb-865c-d277ea68b712.png)
![image](https://user-images.githubusercontent.com/52339710/117799305-8c0cac00-b284-11eb-993f-f4f062ce659b.png)

## 問題描述
主要就是3*3矩陣相加
[[0]*N for i in range(N)] 跟 [[0]*N]*N兩種都有一樣的結果，但為何答案不一樣

**Comment by lazyYC** [comment]
@shanhao1204 
你可以觀察：
``` 
c = [[0] * 3] * 3 
c[0][0] += 2
``` 
的結果，就會發現第二種方法產生的list，裡面的三個list會同步；
原理可以想成使用乘號複製list時，實際上是複製了三個索引（類似門牌？），但他們都指向同一個地址。
