### ISSUE TITLE
[Homework #] 小明上菜 IV

### ISSUE THREAD

**Issue by nalajhu** [coding-coworking-club/python-spring-2021#482]
## 提交連結
https://judge.ccclub.io/status/b28c48b5da8e505207594873e9f055aa

## 程式碼

```python
def lumberpuzzle(lumberlst):
    if sum(lumberlst)%4 > 0:
        return False
    lenth = int(sum(lumberlst)/4)
    leftside = [lenth]*4 #每邊剩餘的長度
    for i in range(len(leftside)): 
        picking = []  #這個邊選擇的木材
        index = 0
        while True:
            if leftside[i] == 0:
                break
            try:
                if leftside[i] >= lumberlst[index]:
                    leftside[i] -= lumberlst[index]
                    picking.append(lumberlst[index])
            except :
                if index == (len(lumberlst)-1):
                    return False
                lastwood = picking[len(picking)-1]
                picking.remove(lastwood)
            index += 1
        for l in picking:
            lumberlst.remove(l) #移除已使用的木材
    if sum(lumberlst) == 0:
        return True
    else:
        return False
        
lumberlst = [int(x) for x in input().split(",")]
lumberlst = sorted(lumberlst)[::-1]
print(lumberlst)
print(lumberpuzzle(lumberlst))
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/58177181/117850760-3520ca00-b2b8-11eb-8ac3-f3aa1da54de1.png)

## 問題描述
我覺得自己在處理，把上一步選擇的木材放回去步驟有問題，出現indexerror

**Comment by sam7k9621** [comment]
出問題的在於 picking[len(picking)-1] 那邊
你發現現有的組合不能拼出來的時候，要返回上一層
但是在返回的過程中要記得把扣掉的加回去
你可以試試看這個：9,6,1,9,6,1,5,5,4,2,5,5,4,2
然後在except 裡面加上print(leftside[i], picking) 去觀察你所選的木材就會知道問題了

**Comment by nalajhu** [comment]
我調整有將木材加回去，但是無法從except跳出，會一直EXCEPT裡面將picking移除到空 QQ

![image](https://user-images.githubusercontent.com/58177181/118005370-e721ca00-b37c-11eb-80fd-dd862ee8ad5d.png)

![image](https://user-images.githubusercontent.com/58177181/118005454-fc96f400-b37c-11eb-902a-3417c1394148.png)

**Comment by sam7k9621** [comment]
你也要把紀錄的index 重新設，不然他其實還是選到會讓他進 except 的組合
