### ISSUE TITLE
[Homework #] 信箱地址檢查

### ISSUE THREAD

**Issue by jennifer090** [coding-coworking-club/python-spring-2021#488]
## 提交連結
https://judge.ccclub.io/status/52809bffcc2857a42034b08c559148ef

## 程式碼

```python
import re
a=input().split(',')
list1=[]
for i in a:   #開頭一定是英文大小寫或是數字 再@前面可以有英文、數字或符號，但符號不能相連因此用| (符號也不一定會出現因此用?)開頭可能只有一個字就接@所以([\.|\+|\_|-]?[A-Za-z0-9])可能是0次或一次以上，@之後接域名(為數字，大小寫英文)，最後可能出現.com 或是.com.tw所以 設定.tw可能出現一次或0次且出現在結尾
    pattern=r'^[A-Za-z0-9]+([\.|\+|\_|-]?[A-Za-z0-9])*@[A-Za-z0-9]+\.com(\.tw){0,1}$'  
    f=re.match(pattern,i)
    if f==None:    #如果從前面開始檢查只要中間不match 就會回傳none

        list1.append(False)
    else:
        list1.append(True)
print(list1)
```

## 錯誤訊息
WA

## 問題描述
測資都沒有問題我在想是
不是([\.|\+|\_|-]?[A-Za-z0-9])的表達方式有問題或是在後面的None那裡不能這樣寫?

**Comment by ghost** [comment]
我不是助教，@前面沒問題，@後面不一定是要.com.tw喔，試試a.a.a@a.a要回傳True

**Comment by waukin** [comment]
感謝熱心學員幫忙！
就如同上面提到的@後面不一定是要.com.tw
比如說：
ccclub@ntu.edu.tw 應該要回傳True才對

**Comment by jennifer090** [comment]
> 我不是助教，@前面沒問題，@後面不一定是要.com.tw喔，試試[a.a.a@a.a](mailto:a.a.a@a.a)要回傳True

感謝你！

**Comment by jennifer090** [comment]
> 感謝熱心學員幫忙！
> 就如同上面提到的@後面不一定是要.com.tw
> 比如說：
> [ccclub@ntu.edu.tw](mailto:ccclub@ntu.edu.tw) 應該要回傳True才對

AC了感謝！

**Comment by jennifer090** [comment]
> > 我不是助教，@前面沒問題，@後面不一定是要.com.tw喔，試試[a.a.a@a.a](mailto:a.a.a@a.a)要回傳True
> 
> 感謝你！



> 我不是助教，@前面沒問題，@後面不一定是要.com.tw喔，試試[a.a.a@a.a](mailto:a.a.a@a.a)要回傳True
