### ISSUE TITLE
[Homework 4] 移動球球

### ISSUE THREAD

**Issue by quickSoon** [coding-coworking-club/python-spring-2021#489]
## 提交連結

https://judge.ccclub.io/status/3ca5349548fc0caa047ec01b53fc5c76

## 程式碼

```python
box = ",".join(input())
box = [int(x) for x in box.split(",")]  #[1, 1, 0]
ans = []

for i in range(len(box)):  #0,1,2
  step = 0
  for j in range(len(box)):  #0,1,2
    step += box[j] * abs(j-i)
  ans.append(step)
print(ans)
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/45255852/118112689-edb14f80-b417-11eb-860d-fc2dbb64edee.png)

## 問題描述

雖然的確沒有照Hint說的用動態規劃的方式做，但測資都過，想知道這樣的解法為什麼會跑很久 (感覺這樣解並不吃力)，或是能否提供其他測資，看看問題出在哪

**Comment by hchbiggrass** [comment]
原因在你的程式的計算步驟是n^2，當箱子有3個的時候，要走9步，當箱子有500個的時候，要走250000步。步驟過多就是超時的原因。這個概念的專有名詞稱為「時間複雜度」，在作業三的「小明上菜啦2」、隨堂練習的「字母麥片」也都有用到。Hint說的動態規劃就是步驟只有n的解法，但其實只要步驟比n^2還要少就可以過這一題。你可以試試看箱子數量為2000的時候，你的程式要跑多久，再以此為基準來改進。

如果不知道要怎麼測程式的時間，請搜尋「%%timeit」
