### ISSUE TITLE
[Homework 1] 吉吉當老師

### ISSUE THREAD

**Issue by 11087tim** [coding-coworking-club/python-spring-2021#49]
## 提交連結

https://judge.ccclub.io/status/96396fbc67341659f9134d1da8a8f75c
## 程式碼

```python
a = float(input())
b = float(input())
c = float(input())

if b == 0 and a == 0 and c == 0:  #無限多
    print("-1")
if b ** 2 - 4 * a * c < 0:  #無實數解
    print("0")

if a == 0 and b == 0 and c != 0:  #無解
    print("0")

if a == 0 and b != 0:  #一個實數解
    print("1")
    print( -c / b)


elif b ** 2 - 4 * a * c >= 0 and a != 0:   #有2理數解
    answer1 = (-b + (b ** 2 - 4 * a * c) ** (1 / 2)) / (2 * a)
    answer2 = (-b - (b ** 2 - 4 * a * c) ** (1 / 2)) / (2 * a)

    answer = []
    answer.append(answer1)
    answer.append(answer2)
    answer.sort()

    if answer1 == answer2:  #重根
        print("2")
        print(answer1)
        print(answer2)
    else:
        print("2")
        for i in range(len(answer)):
            print(answer[i])
```

## 問題描述

系統一直給我wrong answer 但我不知道是哪個測資沒過我覺得我把所有的情況都考慮進去了

**Comment by Din0-3** [comment]
嗨我只是學員
a == 0 and c==0 就無有限解，不論b==0 與否
看要不要先畫個樹狀圖構思一下可能性比較不會漏

另外我對題意的理解是
1. 第一行用int應該就行了
2. 重根應該是只有一個解，第一行=1 第二行=解

*不過我剛剛寫完所以頭也有點昏XD*，如果有搞錯什麼地方請糾正～

**Comment by Yueh-H** [comment]
> 嗨我只是學員
> a == 0 and c==0 就無有限解，不論b==0 與否
> 看要不要先畫個樹狀圖構思一下可能性比較不會漏
> 
> 另外我對題意的理解是
> 
> 1. 第一行用int應該就行了
> 2. 重根應該是只有一個解，第一行=1 第二行=解
> 
> _不過我剛剛寫完所以頭也有點昏XD_，如果有搞錯什麼地方請糾正～

#19 可以幫忙看一下這篇嗎？感謝 
藉樓請問一下
a==0 and c==0:
bx=0 ，x不是唯一零解嗎？

**Comment by 11087tim** [comment]
hi
我是覺得如果測資給的係數不是整數的話，就有casting的問題了
a == 0 , b==0, c ==0應該都要0才能無限多
而且重根我覺得應該是兩個解，但兩個解是相同的

**Comment by Din0-3** [comment]
抱歉抱歉
回文的時候腦袋不太清醒 無限解確實是指abc皆為0的時候

至於我說第一行用int 指的是output沒必要改用string, 就是可以直接`print(1)`這樣，雖然我不知道judge系統會不會看data type，摁摁總之應該不重要

至於為何系統給wrong，我剛剛重新想了一遍然後看了你的code
1. 我自己是把重根視為一個解啦，可能出題目的人是這樣認定？有空可以測看看
2. 你忘了寫四捨五入到小數點第三位的部分

抱歉沒看到通知過了幾天，希望有幫助

**Comment by 11087tim** [comment]
哈囉 感謝你的熱情幫助，已經Ac了哈哈 結果是忘了四捨五入(´･ω･`)不過還是謝謝你幫忙的下次有問題可以再一起討論 一起加油！！！


傳自 iPhone 版的 Yahoo奇摩電子信箱


於 星期三, 3月 10, 2021, 2:41 下午，Din0-3 <notifications@github.com> 寫道：




抱歉抱歉
回文的時候腦袋不太清醒 無限解確實是指abc皆為0的時候

至於我說第一行用int 指的是output沒必要改用string, 就是可以直接print(1)這樣，雖然我不知道judge系統會不會看data type，摁摁總之應該不重要

至於為何系統給wrong，我剛剛重新想了一遍然後看了你的code
   
   - 我自己是把重根視為一個解啦，可能出題目的人是這樣認定？有空可以測看看
   - 你忘了寫四捨五入到小數點第三位的部分

抱歉沒看到通知過了幾天，希望有幫助
