### ISSUE TITLE
[Homework #4推薦系統] problem_title

### ISSUE THREAD

**Issue by s4103052122** [coding-coworking-club/python-spring-2021#493]
## 提交連結

https://judge.ccclub.io/status/821733807f197b9846c80652715c3032
## 程式碼

import math
x = int(input()) #將第一個input轉成整數.此為閥值
list1=[]
dic = {}
while True:
  n = input()
  if n == "end":  #n個輸入,直到end
    break
   
  n = n.split(" ")
  for it in n:   #建立有順序列表
    if it not in list1:
      list1.append(it)

  s=set(n[1:])   
  dic.update( {n[0]:s} )   #建立字典,key為第一個字串(人名),第一個以後的字串(商品)存入集合

for key,value in dic.items():   #依序把人叫出來做比對
  recom_set=set()
  list0=[]
  qu=""
  dic_recom={}
  for i,j in dic.items():   #各別的人配對
    if key == i:    #若配對到自己就跳過.不進行配對
      continue
    else:
      if(len(value&j)/len(value))*100 >= x:    #不同人進行配對後.計算相似度.若>=閥值(第一個輸入的數字)就將物品存入推薦的集合
        recom_set=recom_set.union(j.difference(value))

  for z in range(len(list1)):   #因為集合沒有順序.利用list1建立字典.key為出現順序.value為推薦的物品
    if list1[z] in recom_set:
      dic_recom[z]=list1[z]
  for w in range(len(list1)):     #依照出現順序.將推薦的物品存入list0
    if w in dic_recom.keys():
      list0.append(dic_recom[w])
  for q in list0:    #將有順序的推薦list0裡面的物品依序提出
    qu = qu +" "+q

  print(key+qu)

```python

```

## 錯誤訊息

Wrong Answer

## 問題描述

範例都可以跑出來 但提交就是WA

**Comment by TJ72** [comment]
請修正程式碼，並針對你的程式碼進一步說明解題思路和想法，細節請參考[GitHub 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)
