### ISSUE TITLE
[General]  3-2：大小寫

### ISSUE THREAD

**Issue by mikehung0714** [coding-coworking-club/python-spring-2021#5]
## 提交連結

https://judge.ccclub.io/status/72a5e309d1869a145c37b5bd80c39086
## 程式碼

```python
a = input()
text = ''
for i in a:
    k = ord(i)
    if k < 91:
        k+=32
    text+=chr(k)
text2 = ''
for i in text:
    k = ord(i)
    k-=32
    text2+=chr(k)
print(text2)
print(text)
```

## 問題描述

在編譯器上是對的，但提交程式碼時卻錯誤

**Comment by TJ72** [comment]
在 Judge系統中測資的字串可能不只是英文字母，如果用 ASCII code轉換大小寫可能會出錯。
可以想想看有沒有什麼好用的字串大小寫轉換的方法。
另外，有兩點GitHub Issue的格式下次發文要注意：
1. 提交連結要貼貼提交程式碼之後的 ID 連結，在 Judge裡面的 Status中可以找到。
(i.e. https://judge.ccclub.io/status/72a5e309d1869a145c37b5bd80c39086)
2. 程式碼要貼在指定的位置喔。
