### ISSUE TITLE
[General] 6-3：母音種類個數

### ISSUE THREAD

**Issue by sherrylin-github** [coding-coworking-club/python-spring-2021#50]
## 提交連結

https://judge.ccclub.io/status/91efb9d5442841301690512038de2fbc
## 程式碼

```python
s=input()
vowel=['A','E','I','O','U','a','e','i','o','u' ]
total=0
for i in range (len(s)):
    total+=vowel.count(s[i])
print(total)
```

## 問題描述

在Jupyter Notebook上可以執行該程式碼，並且試了幾個單字算出來都是正確的母音數目，但在judge上都是Wrong Answer，再麻煩指教哪邊有問題，非常感謝。

**Comment by TJ72** [comment]
這樣的確可以算出正確的母音個數，但 Judge上題目要求"正確的母音種類個數"喔！所以像是 Sample Input 1輸出結果好像就不太對！

**Comment by emilyjenjen** [comment]
我自己一開始也是卡關再換算出正確的「個數」而非正確的「種類個數」，後來就寫對了！與其去把s做切割，看一個一個index有沒有是vowel這個list裡面的元素，可以試著去用vowel裡面一個一個元素去看s這個輸入字串裡有沒有這些元素。不知道這樣聽不聽得懂XD

**Comment by sherrylin-github** [comment]
原來是題目理解錯誤，現在成功了，感謝各位．
