### ISSUE TITLE
[General] 請教爬蟲問題

### ISSUE THREAD

**Issue by jingyutsao** [coding-coworking-club/python-spring-2021#500]
## 程式碼

```python
# Metacat 搜尋頁面

# 處理下拉選單 選ISBN
import requests
re = requests.get("https://metacat.ntu.edu.tw")
from bs4 import BeautifulSoup
soup = BeautifulSoup(re.text, "html.parser")
tabs = soup2.find('div', {'class', 'input-group-btn'}).findAll('select') #棒球的範例是找所有選單，Metacat只有一個，但反正沒差
ISBN = tabs[0].findAll('option')[2]['value'] # ISBN選項的位置

# 處理輸入
from selenium import webdriver
driver = webdriver.Chrome()
driver.get("https://metacat.ntu.edu.tw")

element = driver.find_element_by_class_name(“simpleSearchText.form-control”) # 搜尋欄的位置
```

## 問題描述

程式碼還未Run過，只是在寫的過程就發現有問題...
我們希望可以爬Metacat這個找書的系統，目標是可以輸入ISBN(類似書的編碼，一個，為了解決書名可能找到很多不是我們要的書)後，再進搜尋結果爬出符合條件的書。
但是要搜索ISBN要先在搜索框旁邊的一個下拉選單選擇ISBN(預設是書名)，我們的程式碼本來試圖用上課教的中華職棒的那個範例處理下拉選單，但我們發現中華職棒的那個範例用的方法是會改變網址，可是Metacat在選ISBN時並不會影響到網址，包括輸入東西之後跳出的搜尋結果也不會改變網址(很酷的就是按下搜尋之後網址不變，但開發人員工具裡面的程式碼會自己變成新頁面的樣子，蠻想知道這後面的原理，更重要的是這是不是會影響到爬蟲的步驟...)
這些讓我們完全不知道怎麼進行下去...(因為這個步驟就卡住了就完全無法進行後面的動作...)
主要想問的問題有兩個:
1.如何在網址沒有改變的情況下處理選單
2.如何在網址沒有改變的情況下爬搜尋結果(或是其實就是用完selelium之後照正常方式爬...?因為還沒進行到那個步驟，只是覺得很大概率方法會不同)
很抱歉丟一個比較籠統的問題麻煩助教...但實在不知道這樣的問題要怎麼敘述給Google，也想請問助教遇到這些爬蟲上的問題，要怎麼從網路上比較精準的尋求到我想要的答案呢?

**Comment by hchbiggrass** [comment]
我個人習慣使用Selenium，用了這個之後你就會發現可以完全不使用request和BeautifulSoup。你們現在的問題直接用Selenium就可以解決，因為Selenium是模擬人類行為，所以只要把手動要做的每一個步驟都記錄下來，然後叫Selenium這樣做就可以了。其中你們會需要用到的東西大致上包括定位、模擬鍵盤、點擊。定位的部分根據我的經驗，用css selector或xpath就能定位到；模擬鍵盤你們要查一下from selenium.webdriver.common.keys import Keys；點擊的部分在學習使用Selenium的過程就會學到了。

至於要怎麼google，在什麼都不知道的情況下連關鍵字要打什麼都不知道。沒有人可以問的話，也只能沿著根據找到的資料提供的線索一路摸索，根據情況有可能要摸索很長的時間才找到真正的關鍵字，而學會需要的東西又是另一回事了。但如果有人可以問的話可以快速知道關鍵字，會大幅縮短摸索的時間，這就是我們助教存在的意義。不過學會工具基本上還是要靠自己喔。
