### ISSUE TITLE
[General] 爬蟲如何解決下拉式月曆

### ISSUE THREAD

**Issue by ghost** [coding-coworking-club/python-spring-2021#503]
## 程式碼

```python
from selenium import webdriver
from selenium.webdriver.support.ui import Select
driver = webdriver.Chrome('/Users/syuan/chromedriver 2')
driver.get('https://www.uniair.com.tw/rwd/index.aspx')
dep=input()
arr=input()
sel_dep=Select(driver.find_element_by_id('ddl_DEP'))
dic_city={}
for opt in sel_dep.options[1:]:
    dic_city[opt.text[:2]]=opt.text
sel_dep.select_by_visible_text(dic_city[dep])
sel_arr=Select(driver.find_element_by_id('ddl_ARR'))

if dic_city[arr] in [i.text for i in sel_arr.options[1:]]:
    sel_arr.select_by_visible_text(dic_city[arr])
else:
    print('no arrivals')
#以上只是在處理啟程跟目的地，主要問題在下方

driver.execute_script('document.getElementsByName("ctl00$CPH_Body$tb_TRIP_DATE")[0].removeAttribute("readonly")')#把readonly屬性拿掉，但不確定是否需要
start_time=driver.find_element_by_id('CPH_Body_hi_TRIP_DATE')#先定位到該元素位置
driver.execute_script("arguments[0].%s=arguments[1]"%'value',start_time,'2021/05/26')#新增屬性


```

## 錯誤訊息
![LINE_P20210517_200125852](https://user-images.githubusercontent.com/52339710/118485630-3edc7e80-b74b-11eb-9e9b-182c2c060079.jpg)
![LINE_P20210517_125205950](https://user-images.githubusercontent.com/52339710/118485581-32f0bc80-b74b-11eb-928f-9886669a43c6.jpg)
![LINE_P20210517_201415015](https://user-images.githubusercontent.com/52339710/118486722-87486c00-b74c-11eb-97e0-8e0f2edf96ac.jpg)

## 問題描述
主要問題在下面三行，下拉式月曆點開後不會顯示裡面的元素，所以selenium也無法定位。點一個日期會發現type='hidden'那一欄會多出一個屬性value，值就是所選的日期。查了一下發現selenium要用driver.execute_script來執行js代碼，執行後value也確實顯示日期了但網頁卻沒顯示（第三張圖），也有異想天開用一樣的方法把type='hidden'屬性拿掉，但一樣沒辦法。google一下發現input type=hidden是隱藏表單，不會直接顯示，要從瀏覽器點他才會有反應，請問這樣還有解嗎？

**Comment by hchbiggrass** [comment]
不要太早放棄，Selenium是做得到的。首先要知道，Selenium是模擬人類行為，所以將你手動在網頁上操作的步驟，一步一步以Selenium模擬出來即可。這個網頁如果用request的話要用post去傳送請求，手點網頁上的「搜尋」之後，在Network裡面的Name的第一個東西(aspx)裡面的Headers的General裡面就有寫你post了哪些東西。

不過用Selenium也是可以做到的，訣竅在於用鍵盤。在點了日曆之後，無法用滑鼠指定日期，就用鍵盤指定。模擬上下左右鍵，然後按個Enter，就能確定日期了。缺點在於需要在程式裡面轉換現在日期和目標日期之間的相對位置，比較麻煩一點。至於要怎麼模擬鍵盤，請用
from selenium.webdriver.common.keys import Keys
你們還會用到的是類似下面這樣的程式碼
driver.定位.send_keys(Keys.ENTER) #按一下確認鍵

研究一下官方文件的網頁吧
https://selenium-python.readthedocs.io/api.html

不過目前你的程式在定位上會有點麻煩，因為看起來設定啟程地、目的地、出發日期、搭乘人數的這個表格是用javascript寫的，因此如果要用Selenium去點東西，會有明明定位正確但是卻點不到的問題，所以請使用
driver.execute_script('arguments[0].click();', tap) #點擊定位點(JavaScript語法)，tap是定位的變數
基本上上面那一行複製貼上就好，tap設定好定位即可

另外，根據我的經驗，用css selector或xpath就可以定位到，一種定位不到就換另一種，還沒有失敗過。

最後，像是訂機票或房間的網站，其實都會記錄你的cookie或IP(我不太確定是which或both)，你查越多次他價格就越高，所以可以的話建議用無痕模式去查。但是Selenium好像沒有無痕模式，這點要請你們自己確認一下。這可能才是影響專案是否可行的重點。

加油ㄅ

**Comment by ghost** [comment]
謝謝助教回覆，我找到元素了哈哈哈，我以為會在同一個標籤裡面，抱歉擾民。
