### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by sherrylin-github** [coding-coworking-club/python-spring-2021#51]
## 提交連結

https://judge.ccclub.io/status/1351916669d76081bc4df85713ff1344
## 程式碼

```python
a=int(input())
b=int(input())
f=0
c=a
while c>=b:
    f+=(c//b)
    c=(c//b)+(c%b)
print(f+a)
```

## 問題描述

在Jupyter Notebook上可以執行該程式碼，並且試了幾個瓶數算出來都是正確的數目，但在judge上都是Wrong Answer，再麻煩指教哪邊有問題，非常感謝。

**Comment by cyhsieh264** [comment]
問題應該是出在 `c=(c//b)+(c%b)` 這一行？

根據提交連結來看，你在 judge 系統上提交的是 `c=(c//b)+(a%b)` ，可能因此導致運算出錯。

另外下次建議說明每個變數所代表的含義，或是換成有意義的變數名稱，會有助於加快 debug 的速度～

**Comment by sherrylin-github** [comment]
感謝解答與debug的建議，修正後就成功了！
