### ISSUE TITLE
[General] 小華的抽籤程式

### ISSUE THREAD

**Issue by a119164** [coding-coworking-club/python-spring-2021#512]
## 提交連結
https://judge.ccclub.io/status/44c740d25d72993d49b5ecc9598687eb

## 程式碼

```python
#小華的抽籤程式
import random 
line = input().split()
random_seed = int(line[0])
n = int(line[1])
a = random.randint(1,1000000000)
b = random.randint(1,1000000000)
c = random.randint(1,10000)

for i in range(n):
    winner = (a*random_seed + b)%c
    print(winner)
    random_seed = winner
```

## 問題描述

因為這種random的題目每次出來的結果都不一樣
我也不能判斷自己寫對還寫錯
總之提交上去就是WA
但不知道自己錯在哪裡QQ

**Comment by TJ72** [comment]
請參考 Python 的[亂數官方文件](https://docs.python.org/3/library/random.html)，裡面的 `rand.seed()`的用法與介紹是完成這題的關鍵

**Comment by a119164** [comment]
了解！成功AC了！
但建議助教題目可以更改一下
把規則講清楚一點
讓我們知道要用到random.seed()的語法
光看題目我會以為題目給的random_seed單純就只是當成r0而已
不會知道要另外去設定random.seed()
感謝助教！
