### ISSUE TITLE
[General] 爬蟲相關_中華職棒大聯盟範例疑問

### ISSUE THREAD

**Issue by chianshianli** [coding-coworking-club/python-spring-2021#515]
## 程式碼

```python

```

## 錯誤訊息
![image](https://user-images.githubusercontent.com/18030336/119083408-79d40000-ba32-11eb-8c38-e6d366500284.png)

## 問題描述
抱歉昨天沒趕上進度所以來不及發問。

在自己跟著做的過程中，檢查原始碼時發現 table 和 tr 間還有一個 tbody 的 tag，於是就想說直接尋找 tbody 這個 tag 會不會也行，結果出來回傳是 none，想請問助教是為什麼?

![image](https://user-images.githubusercontent.com/18030336/119083643-e8b15900-ba32-11eb-94b2-bb200ea0a063.png)

**Comment by Chongfong** [comment]
開啟網頁→F12叫出原始碼
Elements頁面
F5重新整理整個網頁，你會看到原始碼表格內的資料有顏色在閃，是後來慢慢出現的
所以你一開始針對一群空的東西找
返回的結果是None～～～～～～～～

**Comment by chianshianli** [comment]
慧根不夠不是很懂 😢 但還是謝謝助教!!
