### ISSUE TITLE
[General] Django 無法 run server

### ISSUE THREAD

**Issue by bennettwutw** [coding-coworking-club/python-spring-2021#516]
## 程式碼

```python
!python manage.py runserver
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/80173851/119219266-3acbaa80-bb17-11eb-9bc0-457a5cc7e9d1.png)

## 問題描述

助教，在試做專案時，因為 Linebot 要啟動 Django 當做伺服器來串接數據，但是在最後一步要 run server 的時候，不論 Jupyter notebook 或是 Visual Studio Code 都呈現一直跑、跑不出來的狀況，想請教這會是什麼問題、如何排解？感謝！

**Comment by dada8397** [comment]
@bennettwutw 可以貼一下一直跑、跑不出來的截圖嗎？
如果是跟你說 server 已經啟動，然後停在那邊，那是正常的
因為他是一個服務，啟動後就會持續 run 著
