### ISSUE TITLE
[General] 在做期末專案發現的爬蟲問題

### ISSUE THREAD

**Issue by lilylin99** [coding-coworking-club/python-spring-2021#517]
## 程式碼

```python
import requests
from bs4 import BeautifulSoup
re = requests.get("https://www.junyiacademy.org/course-compare/math-grade-1-a/j-m1ach1/v/c3DGTr7Vmsc") #要爬的頁面
soup_junyi = BeautifulSoup(re.text,"html.parser")

all_contents = soup_junyi.find("div",{"class":"nav-pane hidable"})
li_contents = all_contents.find_all("li")#所有影片網址與名稱都放在li裡

for content in li_contents:
    title = content.find("div",{"class":"nav-title"}).text
    print(title) #印出影片名稱
    print(content.a["href"]) #印出影片網址

```

## 錯誤訊息

跑不出來結果

## 問題描述

（1）
因為我們這組期末專案會需要爬[這個頁面裡](https://www.junyiacademy.org/course-compare/math-grade-1-a/j-m1ach1/v/JMN5LjxD6ds)的課程影片名稱、影片頁網址，但從開發者工具發現，都是集中在 <div class =”nav-pane hidable”> 裡，網站原始碼如下截圖
<img width="695" alt="截圖 2021-05-22 下午5 34 42" src="https://user-images.githubusercontent.com/77061461/119227046-ac6b1f00-bb3e-11eb-8058-1454523a3e28.png">

所以我們才會寫出前述的程式，但結果卻是跑不出來，我們也有試著直接印出 nav-pane hidable 裡的資料，但結果只印出標籤，裡面沒有出現在開發者工具裡的 ul、li，結果如下：
<img width="291" alt="截圖 2021-05-22 下午8 52 46" src="https://user-images.githubusercontent.com/77061461/119227289-af1a4400-bb3f-11eb-982e-c3b0619da444.png">

（2）
我們也在[其他網站](https://ithelp.ithome.com.tw/questions/10198403?sc=rss.qu)看到類似的發問，但我們嘗試過 import json 換格式輸出也無法成功，請問就像網站裡有人回答說的是 js render 出了問題嗎？如果是的話，請問該怎麼改善呢？

**Comment by dada8397** [comment]
這個的問題是有些網站頁面跑出來之後，可能還會另外打 API 去要資料，導致你只做第一次 request 的話，有些地方會沒有東西
最好的方式是用 selenium 去抓網站上的東西，這樣就可以等網頁上的資料都跑出來後再拿你要的東西

**Comment by sam7k9621** [comment]
同學好，我剛有試爬 <div class="video" data-role="page" data-theme="b">
這個底下是可以找到影片標題跟連結唷

**Comment by lilylin99** [comment]
謝謝助教，我改用 selenium 試試！
