### ISSUE TITLE
[General] 期末專案 591 租屋網爬蟲問題    

### ISSUE THREAD

**Issue by yolingyang** [coding-coworking-club/python-spring-2021#518]
## 程式碼

```    
import requests
import json

url = "https://rent.591.com.tw/home/search/rsList"
my_params = { "is_new_list": 1,
              "type": 1,
              "kind": 0,
              "searchtype": 4,
              "region": 1,
              "mrt": 1,
              "mrtcoods": 4183,
              "mrtline": 125,
            }

rent = requests.get(url, params = my_params).json()
print(rent)

```

## 錯誤訊息

     
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/80040871/119695982-4dc8dc80-be81-11eb-8d4f-9d8e625ee22c.png">

## 問題描述

      
1. 我們這組想要搜集靠近各個捷運站的租房列表，想用 get API 處理換頁問題         
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/80040871/119697077-6a194900-be82-11eb-8e86-46ebe2c2f27e.png">     
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/80040871/119697568-e4e26400-be82-11eb-92ee-bdcc427c88e6.png">    

因為 API method 是 get，所以使用了同 Dcard 範例的方式，但出現上方錯誤訊息      
    
2. 有直接在 postman 打這個 API，發現會 419 error （不確定錯誤訊息是否就是因為這個造成）        
在網路上看 419 可能是因為 XSRF token，但查不太到要怎麼在程式上面帶 token，而且看起來 token 是每日都會重新產生的    
ps : 有在 postman 上面帶 token 但還是 error，所以也不確定就算帶到程式上面是否會 ok :cry:     
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/80040871/119696672-03942b00-be82-11eb-8973-25308b45bffe.png">      

再請助教協助 debug 感謝！

**Comment by hchbiggrass** [comment]
對於功能比較豐富的網站，建議使用selenium來爬蟲，不會遇到用request會遇到的各種問題。
