### ISSUE TITLE
爬蟲問題:無法找到網頁元素

### ISSUE THREAD

**Issue by jennifer090** [coding-coworking-club/python-spring-2021#521]
## 提交連結
https://www.instagram.com/guava_photograph/

## 程式碼

```python
from selenium import webdriver
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
import requests
driver=webdriver.Chrome()
driver.get("https://www.instagram.com/accounts/login/")  #get instagram的網站
WebDriverWait(driver,30,0.5).until(EC.presence_of_element_located((By.NAME,'username'))) #定位帳號密碼在的位置
usernaminput=driver.find_element_by_name("username")
passwordinput=driver.find_element_by_name("password")
a=input()  #使用者輸入
b=input()
usernaminput.send_keys(a)  
passwordinput.send_keys(b)
WebDriverWait(driver,30,0.5).until(EC.presence_of_element_located((By.XPATH,"//*[@id='loginForm']/div/div[3]/button/div")))
clickbotton=driver.find_element_by_xpath("//*[@id='loginForm']/div/div[3]/button/div")  #按下搜尋紐
clickbotton.click()
sleep(3)
wrong=driver.find_elements_by_xpath("//*[@id='slfErrorAlert']")
while wrong!=[]:#處理如果輸入的帳號不存在的情況(但如果是直接按enter會出現error，這邊還位處裡)
    print("您的帳號密碼不正確，請重新輸入!")
    usernaminput.send_keys(Keys.CONTROL+'a')  #帳號與密碼接清空，並重新輸入，直到帳密存在為止
    usernaminput.send_keys(Keys.DELETE)
    passwordinput.send_keys(Keys.CONTROL+'a')
    passwordinput.send_keys(Keys.DELETE)
    a=input()
    b=input()
    usernaminput.send_keys(a)
    passwordinput.send_keys(b)
    WebDriverWait(driver,30,0.5).until(EC.presence_of_element_located((By.XPATH,"//*[@id='loginForm']/div/div[3]/button/div")))
    clickbotton=driver.find_element_by_xpath("//*[@id='loginForm']/div/div[3]/button/div")
    clickbotton.click()
    sleep(3)
    wrong=driver.find_elements_by_xpath("//*[@id='slfErrorAlert']")
WebDriverWait(driver,30,0.5).until(EC.presence_of_element_located((By.XPATH,'//*[@id="react-root"]/section/main/div/div/div/div/button')))
z=driver.find_element_by_xpath('//*[@id="react-root"]/section/main/div/div/div/div/button')
z.click()  #選擇稍後儲存帳密
WebDriverWait(driver,30,0.5).until(EC.presence_of_element_located((By.XPATH,"/html/body/div[4]/div/div/div/div[3]/button[2]")))
k=driver.find_element_by_xpath("/html/body/div[4]/div/div/div/div[3]/button[2]")
k.click()  #開啟通知的稍後在說"_6q-tv"
sleep(3)
personal=driver.find_element_by_xpath("//*[@id='react-root']/section/nav/div[2]/div/div/div[3]/div/div[5]/span")
personal.click() 
sleep(3)
connect=driver.find_element_by_xpath("//*[@id='react-root']/section/nav/div[2]/div/div/div[3]/div/div[5]/div[2]/div[2]/div[2]/a[1]")
connect.click()
WebDriverWait(driver,30,0.5).until(EC.presence_of_element_located((By.CLASS_NAME,"v1Nh3 kIKUG  _bz0w")))
i=driver.find_element_by_class_name("v1Nh3 kIKUG  _bz0w").get_attribute("herf")
print(i)
z=driver.find_element_by_tag_name('a').get_attribute('herf')
print(z)
```

## 錯誤訊息
找不到網頁元素
![image](https://user-images.githubusercontent.com/79786093/120414725-fe0c7880-c38c-11eb-9052-0822e57a8282.png)

## 問題描述
我看它的結構是
div class="v1Nh3 kIKUG  _bz0w"
     a href="/p/CNg09haljsZ/" tabindex="0" class=""
           div class="eLAPa"
                 div class="KL4Bh"
但是driver.find_element_by_class_name("v1Nh3 kIKUG _bz0w")或是driver.find_element_by_tag_name('a').get_attribute('herf')都顯示找不到元素

![image](https://user-images.githubusercontent.com/79786093/120414643-e3d29a80-c38c-11eb-86b0-5208959a6402.png)
![image](https://user-images.githubusercontent.com/79786093/120415032-72471c00-c38d-11eb-828e-199c155e0160.png)

**Comment by hchbiggrass** [comment]
請問你爬蟲的目的是什麼?抓圖片嗎?

**Comment by jennifer090** [comment]
> 請問你爬蟲的目的是什麼?抓圖片嗎?

我是想要取得一個帳號中，每張照片中按過讚的所有人(因為我想統計最常幫這個帳戶按讚的粉絲)以及取得所有貼文的發文時間，因為這些資訊我看到是要點開照片才有，所以我本來想說想辦法把照片的超連結抓出來，和ig的主網址結合，然後用request去請求，但是想要先找每張照片(下一層有超聯結)的元素卻找不到。

**Comment by hchbiggrass** [comment]
你好，我剛剛試出來了，純用Selenium就好。按F12之後，滑鼠去點圖片，會移動到那張圖片的定位，然後往上找到有a href的那個定位，然後用get_attribute('href')就可以抓到網址，直接進這個網址去抓你要的資料。至於怎麼回到帳號那邊抓下一張圖就請自己想怎麼for loop了喔

**Comment by jennifer090** [comment]
> 你好，我剛剛試出來了，純用Selenium就好。按F12之後，滑鼠去點圖片，會移動到那張圖片的定位，然後往上找到有a href的那個定位，然後用get_attribute('href')就可以抓到網址，直接進這個網址去抓你要的資料。至於怎麼回到帳號那邊抓下一張圖就請自己想怎麼for loop了喔

不好意思，我想請問一下請問您說的a herf的定位是指div class="v1Nh3 kIKUG  _bz0w"嗎?(上面有截圖)
但是我用driver.find_element_by_class_name("v1Nh3 kIKUG  _bz0w").get_attribute("herf") 或是  driver.find_element_by_tag_name('a').get_attribute('herf')都還是出現nosuch element exception ，就算加了等待的時間還是timeout exception，想請問一下我是哪裡弄錯了，還有為什麼網頁元素上有顯示的用find element會找不到，麻煩了謝謝!!

**Comment by hchbiggrass** [comment]
a在div calss="v1Nh3 kIKUG _bz0w"下面，兩個的定位不同，要定在a，然後取get_attribute('herf')。另外，定位建議用css selector或xpath，比較沒有定位正確但還是抓不到的問題。

**Comment by jennifer090** [comment]
> a在div calss="v1Nh3 kIKUG _bz0w"下面，兩個的定位不同，要定在a，然後取get_attribute('herf')。另外，定位建議用css selector或xpath，比較沒有定位正確但還是抓不到的問題。

可以了!謝謝助教!
