### ISSUE TITLE
[General] Django 安裝

### ISSUE THREAD

**Issue by jingyutsao** [coding-coworking-club/python-spring-2021#522]
## 程式碼

![image](https://user-images.githubusercontent.com/80766297/120287820-30b56300-c2f2-11eb-9586-e088c723a4bc.png)

```python

```

## 問題描述

![image](https://user-images.githubusercontent.com/80766297/120287912-44f96000-c2f2-11eb-8616-2071ce580ade.png)
想按照這個網站的說明去安裝Django，但到虛擬環境這邊就卡住了(前面輸入pip3 install virtualenv有成功)，我其實沒有看懂為什麼要弄虛擬環境，以及接下來在虛擬環境中安裝Django的步驟和原理等等(因為搞不清楚到底要幹嘛，所以很難把網路上的教學改成我的電腦和我這邊的狀況下，到底要輸入甚麼指令才能完成同樣的目的)，除此之外，有看到教學是從Django到jupyter上也需要一些步驟才能在jupyter上用，網路上的教學都是一板一眼告訴你要輸入什麼，可是看起來我這邊和教學上的東西有一些要改的，可是完全不知道怎麼做才對......
https://carolhsu.gitbooks.io/django-girls-tutorial-traditional-chiness/content/django_installation/README.html
這是我看的網站，我覺得已經是比較詳細和好懂的了，但還是進行不下去......

**Comment by chianshianli** [comment]
(非助教，只是路過)

根據我初淺的理解，虛擬環境應該是個專案管理用的東東。
例如你電腦可能裝最新的 python，但你加入的專案是用舊版的，因為擔心相容性的問題所以你也要用舊版的做才可以，這時候虛擬環境就可以派上用場了。

所以若以日後可能會到處有各種專案的狀況下，養成開始新專案就開一個新的虛擬環境聽說是個需要養成的好習慣。

但如果你現在略過他，我猜應該也是可以繼續運作的(咳 ...

對了要用虛擬環境的話，有助教推薦 pipenv。

**Comment by jingyutsao** [comment]
喔喔好的~非常感謝你!
