### ISSUE TITLE
[General] 期末專案 破解API中的Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by LinYuanSheng** [coding-coworking-club/python-spring-2021#525]
## 提交連結

https://swelleye.com/surf-spots/shalun/
## 程式碼

```python
import requests
res = requests.get("https://api.swelleye.com/spreadsheets.php?lat=25.191083&lng=121.413983")
print(res.text)
```

## 錯誤訊息

Whoops... something unexpected occured.

## 問題描述

1.我們這組要爬蟲上面網頁中間的表格(時間、浪高、波浪週期、浪向等)，一開始想要用BeautifulSoup抓不到東西，經過每周問答助教提點後，嘗試可以直接用API串接方式獲得表格資訊。但開發人員工具中的Header中有Access-Control-Allow-Origin字樣，意思是指能從上面網頁發出去的請求API才會回應，上週助教意思是要試著破解這點。

2.解決方法，我們從網路上找過在API的url前面加上https://cors-anywhere.herokuapp.com/ ，但跑出「This demo of CORS Anywhere should only be used for development purposes...」等文字；之後又找到在API的url前面加上https://crossorigin.me/ ，但跑出的資訊似乎是https://crossorigin.me/ 網站的相關資訊。

3.想請問助教有無其他解決Access-Control-Allow-Origin的方式，謝謝!!

**Comment by LinYuanSheng** [comment]
@alexypdu 助教，標記你喔~thx!

**Comment by alexypdu** [comment]
You need the _Origin_ header.

```python
import requests

headers = {
    'Origin': 'https://swelleye.com',
}

params = (
    ('lat', '25.191083'),
    ('lng', '121.413983'),
)

response = requests.get('https://api.swelleye.com/spreadsheets.php', headers=headers, params=params)
print(response.status_code) // 200
```

**Comment by LinYuanSheng** [comment]
原來是header!!感謝 @alexypdu 助教!!
