### ISSUE TITLE
[General]超商取貨

### ISSUE THREAD

**Issue by CKJK47** [coding-coworking-club/python-spring-2021#527]
## 提交連結

https://judge.ccclub.io/status/c95e4a05f5b7235d7b425730ada733b0
## 程式碼

```python
s = input()
dic = {}
#不定行輸入直到end出現
while s != "end":
    s = s.split(",")
    #dic的key放成由(手機末三碼, 名字)組成的tuple，value放買的物品
    dic[(s[0][7:], s[1])] = s[2]
    s = input()
#不定行輸入
while True:
    try:
        #取貨
        get_stuff = input().split(" ")
        #末三碼為get_stuff第0項
        phone = get_stuff[0]
        #姓名為get_stuff後面全部，因為剛剛用空格split，現在把名字之間的空格還回去
        name = " ".join(get_stuff[1:])
        #(末三碼，姓名)的tuple丟回字典搜尋
        get = (phone, name)
        if get in dic:
            print(dic[get])
        else:
            print("Check again!")
    except KeyboardInterrupt:
        break
```

## 錯誤訊息

<img width="1177" alt="截圖 2021-06-08 下午1 17 54" src="https://user-images.githubusercontent.com/79802408/121127167-f270f400-c85b-11eb-9144-7786992643e0.png">

## 問題描述

1. 步驟如註解
2. 代入sample都對，不知道是哪裡沒有考慮到，謝謝助教

**Comment by TJ72** [comment]
try/except 的條件檢查一下

**Comment by CKJK47** [comment]
> try/except 的條件檢查一下

助教好，我發現把except的KeyboardInterrupt刪掉就可以AC了，不過我想請問這兩者在實務上有什麼差別嗎？
我對KeyboardInterrupt的理解就是使用者自己終止程式，為什麼這邊不對呢？謝謝！

**Comment by TJ72** [comment]
因為在 Judge 裡面餵測資的方式是用檔案，不是 KeyboardInterrupt 這種 Error。如果是改成 EOFError 的話也是可以 AC 的喔！

**Comment by CKJK47** [comment]
原來如此，謝謝助教！

> 因為在 Judge 裡面餵測資的方式是用檔案，不是 KeyboardInterrupt 這種 Error。如果是改成 EOFError 的話也是可以 AC 的喔！

原來如此，謝謝助教！
