### ISSUE TITLE
[General] 綜合1-2：一奇多偶

### ISSUE THREAD

**Issue by Jimmylin1515** [coding-coworking-club/python-spring-2021#529]
## 提交連結

https://judge.ccclub.io/status/fabdcd8c63d3684c5ba4b0df71f86845
## 程式碼

```
lst1 = [int(i) for i in input().split()] #將字串以空格分隔存進串列，並且轉成數字型態 
lst1 = sorted(lst1) #數字由小到大排序
#避免用for loop一個個檢查，利用遞迴直接跳到下一個新的數字並接續著判斷
def one_odd(i): 
    a = lst1.count(lst1[i]) # a = 數字出現次數
    if (a % 2) == 1: # 如果 a(出現次數)為奇數儲存
        return lst1[i]
    else:
        i += a #若 a(出現次數為偶數)，index(i)跳到下一個新數字的index
        return one_odd(i)

print(one_odd(0))

```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/79753896/123501888-b40c6f00-d67a-11eb-81b5-a01c0e764b84.png)

## 問題描述

原本想使用迴圈一個個判斷出現次數是否為奇數，但放上judge系統出現time limit exceeded ，我想可能是迴圈在一一個判斷的過程中會重複判斷重複出現的數字，所以我想利用遞迴讓程式在判斷完一個新數字的出現次數後，立即跳到下一個新數字(避免判斷已判定完的數字)，但結果出現runtime error，但我在jupyer notebook上試的結果都是對的，想請問我的解題想法和程式碼在哪個地方出錯了? 感謝各位助教!

**Comment by TJ72** [comment]
RE 是因為在 `a = lst1.count(lst1[i])` 數出現次數，如果是出現奇數跳 else 判斷式時，`i += a` 可能會超出串列的長度。另外會 TLE 是因為每次 call `list.count(ele)` 本身需要跑遍串列一遍才能回傳次數，所以使用太多次的話就會讓程式跑起來比較慢。可以試試看用 set 或是 dictionary 來寫寫看這題喔！
