### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by hualienking** [coding-coworking-club/python-spring-2021#55]
## 提交連結

https://judge.ccclub.io/status/d1368f0eb81073046564032f106c1821
## 程式碼

```python
buy = int(input())
point = int(input())
new = buy // point
while new :
    total = buy + new
    new = new // point
    total = total + new
else:
    total = buy
print(total)
```

## 錯誤訊息

Time Limit Exceeded
## 問題描述

無法理解為什麼這樣子會無法讓程式跑完?
但是用IF又只會跑一次
想請問該如何解決

**Comment by chi811008** [comment]
哈囉～
while-loop 在執行其內部敘述之前，都會先檢查條件判斷式，如果其判斷值為真 (True)，則執行迴圈內部的敘述；否則就結束 while-loop。

可以參考我們的medium文章
[https://medium.com/ccclub/ccclub-python-for-beginners-tutorial-4990a5757aa6](url)
在你的解答中，new值只要"不等於0"就會被判斷成True，等於0才會跳出迴圈
然而
`new = new // point
`
這一行式子不會讓你的new有變成0的機會
所以會一直跑不完唷！
可以再想想怎麼讓new改變，或是while後面應該要放什麼
