### ISSUE TITLE
[Week 2] 停車費 

### ISSUE THREAD

**Issue by zheng-xyx** [coding-coworking-club/python-spring-2021#56]
## 提交連結

https://judge.ccclub.io/status/99c89d21f9ba477ab8fc44461d45d663
## 程式碼

```python
st=input()
le=input()
paper=input()
nst=int(st[0:2])
nnst=(nst*60)+int(st[3:5])
nle=int(le[0:2])
nnle=(nle*60)+int(le[3:5])
final=nnle-nnst
fee=(final//30)*20
if paper=="Y" and final<=30:
    print('0')
if paper=="Y":
    print(fee//2)
if final%30!=0 and paper=="Y":
    print(fee+10)
elif final%30!=0 and paper=="N":
    print(fee+20)
else:
    print(fee)

```

## 問題描述

就是我嘗試放入sample都顯示正確，而且我認為把小時換成分鐘來計算應該也是沒有缺漏的，但是怎麼提交都是wrong answer

**Comment by TJ72** [comment]
請修正提交連結與程式碼，細節請參考[github 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)

**Comment by zheng-xyx** [comment]
> 請修正提交連結與程式碼，細節請參考[github 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)

提交連結已改善，想請問程式碼哪裡有問題，謝謝您

**Comment by TJ72** [comment]
前面計算的部分應該沒有什麼問題，但後面的 if/elif/else 在"有台大證件"時的判斷順序不太對，有很多情況會輸出超過一種的停車費。

另外，下次請將程式碼貼在指定位置喔！

**Comment by zheng-xyx** [comment]
謝謝您的回答
我下次會注意的！
