### ISSUE TITLE
[General] 6-3：母音種類個數

### ISSUE THREAD

**Issue by Din0-3** [coding-coworking-club/python-spring-2021#57]
## 提交連結
https://judge.ccclub.io/status/bb2d6939a2923e2558506622baf0b965

## 程式碼

```python

s1 = input()
vowel_count = 0
v_list = ["a", "e", "i", "o", "u", "A", "E", "I", "O", "U"]

for i in v_list:
    if i in s1 == True :   
        vowel_count += 1
    else:
        continue
        
print(vowel_count)


```

## 問題描述

想法是把母音建立一個list, 用for loop測驗list 裡面的物件是否在input 的string中，若有在裡面則vowel_count +=1

但是最後得到的答案=0，我在檢查的時候加了print在迴圈裡面，發現條件判斷那邊不知道為何都不能符合

但是理論上i 是string, s1 也是string, 後面的判斷是也是看布林值

我試著用list重寫過也還是一樣，想不出問題何在，麻煩幫忙指點，謝謝

**Comment by nick30924** [comment]
你好，我發現你的程式碼中只要將「 == True 」這個去掉就能運行了，我也有遇到同樣的問題，if後面的條件不用額外再寫出符合的部分就能運行，你可以試試看～
我自己在這題是用if else的土法煉鋼去拚十個母音解出來，謝謝你分享你的解法讓我知道怎麼用迴圈解題：）

**Comment by Din0-3** [comment]
> 你好，我發現你的程式碼中只要將「 == True 」這個去掉就能運行了，我也有遇到同樣的問題，if後面的條件不用額外再寫出符合的部分就能運行，你可以試試看～
> 我自己在這題是用if else的土法煉鋼去拚十個母音解出來，謝謝你分享你的解法讓我知道怎麼用迴圈解題：）

啊哈哈原來如此，感謝你幫我找到問題
我懂了，因為(string) in (string) 本身就是一個boolean了，所以在寫條件判斷的時候不能再額外加上新的boolean

比如說
``` python
if 10>5 == True :
    print ("of course")
else :
    print("ummmm...")
```
會得到 ummmm....

不過如果打
`True == True`
會得到True

但是如果打
`10 > 5 == True `
卻會得到False

不知道為什麼呢?

**Comment by nick30924** [comment]
其實對於這個設計的背後我也不是很清楚，還是得請專業的大大來解析一下～

**Comment by Din0-3** [comment]
> 其實對於這個設計的背後我也不是很清楚，還是得請專業的大大來解析一下～


嗨我找到答案囉～

可以參考這個[連結](https://stackoverflow.com/questions/31354429/why-is-true-is-false-false-false-in-python)、或是python的[正式syntax說明](https://docs.python.org/3/reference/expressions.html#comparisons)

簡單來說python裡面的comparison 會產生chain的效果
`a<b<c` 等於 `a<b and b<c`
所以 `10>5 == True` 會被python解釋為 `10>5 and 5 == True`
於是得到 `False`

所以我們遇到的問題不是因為if後面不用寫條件，而是因為 `i in s1` 本身就是一個Boolean值，所以靠他就可以運作了，如果替他加上 `==True` 反而會把條件判斷多增加一個 `s1==True` 而得到 `False` 的結果～

**Comment by nick30924** [comment]
原來如此～感謝你的分享！
又學到一課了！
