### ISSUE TITLE
[General] 7-2：加減長方形

### ISSUE THREAD

**Issue by siddwang827** [coding-coworking-club/python-spring-2021#6]
## 提交連結

https://judge.ccclub.io/status/539043c61f02e06f83fe3625e8d7527a

## 程式碼

```python
l = int(input())
w = int(input())
while w > 0:
    if w % 2 == 1:
        if l % 2 == 1:
            print("+-" * (l // 2) + "+")
        else:
            print("+-" * (l // 2))
    else:
        if l % 2 == 1:
            print("-+" * (l // 2) + "-")
        else:
            print("-+" * (l // 2))
    w -= 1
        
```

## 錯誤訊息

![圖片](https://user-images.githubusercontent.com/69707312/109622607-41c9c900-7b77-11eb-9269-5f25d3af659a.png)

## 問題描述

自己在jupyter上可以正常執行程式，功能也可達到題目需求，
請問是寫得太複雜或是其他原因嗎?
![圖片](https://user-images.githubusercontent.com/69707312/109622986-ab49d780-7b77-11eb-92a4-c0e869fb6cc0.png)

**Comment by siddwang827** [comment]
有發現一個問題，原本的寫法會隨著w是奇數或偶數改變起始的符號，
因此多設了一個變數n來固定第一行一定是從+開始，
但答案還是不對，或著是本題的思路是希望透過其他技巧來解呢?

```python
l = int(input())
w = int(input())
n = 1
while n <= w:
    if n % 2 == 1:
        if l % 2 == 1:
            print("+-" * (l // 2) + "+")
        else:
            print("+-" * (l // 2))
    else:
        if l % 2 == 1:
            print("-+" * (l // 2) + "-")
        else:
            print("-+" * (l // 2))
    n += 1
```
![圖片](https://user-images.githubusercontent.com/69707312/109625987-f1546a80-7b7a-11eb-9842-ed01efe90aee.png)

另外發現題目的sample.2 output的答案應該有誤?
是否應為
+-+-
-+-+
+-+-
![圖片](https://user-images.githubusercontent.com/69707312/109626560-a8e97c80-7b7b-11eb-942c-fb8283a4fb2b.png)

**Comment by siddwang827** [comment]
想說課程標題為更多迴圈，
因此除了寬度w使用while迴圈設變數n記數
又增加了長度l也使用while迴圈設變數m記數
結果答案還是不對

```python

l = int(input())
w = int(input())
n = 1
while n <= w:
    m = 1
    if n % 2 == 1:                     #奇數列
        while m <= l:
            if m < l:                  #非字尾
                if m % 2 == 1:         #奇數字元
                    print('+', end='')
                else:                  #偶數字元
                    print('-', end='')
            else:                      #字尾
                if m % 2 == 1:         #奇數結尾
                    print('+')
                else:                  #偶數結尾
                    print('-')
            m += 1
    else:                              #偶數列
        while m <= l:             
            if m < l:                  #非字尾
                if m % 2 == 1 :        #奇數字元
                    print('-', end='')
                else:                  #偶數字元
                    print('+', end='')
            else:                      #字尾
                if m % 2 == 1 :        #奇數結尾
                    print('-')
                else:                  #偶數結尾
                    print('+')
            m += 1
   
    n += 1
```

**Comment by siddwang827** [comment]
用巢狀for loop再寫了一種算法，
功能都可以執行，但系統還是給了wrong answer，
沒招了，再請幫忙建議感謝~

```python

l = int(input())
w = int(input())
for i in range(1, w+1):
    if i % 2 == 1:
        for j in range(1,l,2):
            print('+-', end='')
        print('+' * (l % 2))          
    else:       
        for j in range(1,l,2):
            print('-+', end='')
        print('-' * (l % 2)) 
```
![圖片](https://user-images.githubusercontent.com/69707312/109646474-35536980-7b93-11eb-94ba-0bca1512ba4a.png)
![圖片](https://user-images.githubusercontent.com/69707312/109646503-44d2b280-7b93-11eb-9410-23e72fdc789d.png)

**Comment by TJ72** [comment]
我覺得你有點誤解題目的意思了喔！你可以從 7-1：長方星的邏輯延續到這題來想：一樣是要輸出(l * m)的長方形，只是要用"+-+-"的符號來排列，然後換行之後排列的順序還是要延續上一行最後一個符號接續下去。

**Comment by hchbiggrass** [comment]
> 有發現一個問題，原本的寫法會隨著w是奇數或偶數改變起始的符號，
> 因此多設了一個變數n來固定第一行一定是從+開始，
> 但答案還是不對，或著是本題的思路是希望透過其他技巧來解呢?
> 
> ```python
> l = int(input())
> w = int(input())
> n = 1
> while n <= w:
>     if n % 2 == 1:
>         if l % 2 == 1:
>             print("+-" * (l // 2) + "+")
>         else:
>             print("+-" * (l // 2))
>     else:
>         if l % 2 == 1:
>             print("-+" * (l // 2) + "-")
>         else:
>             print("-+" * (l // 2))
>     n += 1
> ```
> 
> ![圖片](https://user-images.githubusercontent.com/69707312/109625987-f1546a80-7b7a-11eb-9842-ed01efe90aee.png)
> 
> 另外發現題目的sample.2 output的答案應該有誤?
> 是否應為
> +-+-
> -+-+
> +-+-
> ![圖片](https://user-images.githubusercontent.com/69707312/109626560-a8e97c80-7b7b-11eb-942c-fb8283a4fb2b.png)

sample2的output沒有錯誤喔，這正是你wrong answer的原因

**Comment by siddwang827** [comment]
感謝指教，原來是誤會了題目，一直以為是要類似排列出梅花座的意思，
在udmey上的作業7-2的範例二跟作業系統上的範例二是不同的答案，可能是這樣被誤導，
![圖片](https://user-images.githubusercontent.com/69707312/109783583-1f05e600-7c45-11eb-8572-3cde3ea48d77.png)

重新改過算法後終於Accepted啦！
不過有點糾結的是沒有用到多重迴圈，有符合題目預期的解題思路嗎?
因為從 7-1：長方星自己有寫兩種算法，分別是用一個迴圈與巢狀迴圈，兩個答案都有被Accepted

``` python

l = int(input())
w = int(input())
s = ['+','-']
for i in range(l*w) :
    print(s[i%2], end='')
    if i % l == (l-1): 
        print()
```

**Comment by alexypdu** [comment]
多重迴圈的思路是把長跟寬分兩個 for-loop 來處理：

```python
for i in range(w):
  for j in range(l):
    // your code...
```

一個題目可能有很多種解法，有餘裕的話可以多嘗試不同的切入點！
