### ISSUE TITLE
[Week 2] 小仔填志願

### ISSUE THREAD

**Issue by Molly995** [coding-coworking-club/python-spring-2021#60]
## 提交連結

https://judge.ccclub.io/status/7a262ad2eb4e7f80a6afcd4407872af8

## 程式碼

```python
##輸入成績與科系
score = input()
department = input()
  
chi = int(score[0:2])
eng = int(score[4:6])
mat = int(score[8:10])
soc = int(score[12:14])
sci = int(score[16:18])

##條件
if department == "會計系" and (chi + eng + mat + soc >= 57) and chi >= 15:
    print("1")
elif department == "公衛系" and (eng + mat + sci >= 38):
    print("1")
elif department == "經濟系" and (sci + soc >= 26) and mat >= 15:
    print("1")
elif department == "資工系" and (eng + sci >= 27) and mat >= 15:
    print("1")
else:
    print("0")
```

## 問題描述

交功課時出現Runtime error，但我前看後看左看右看找不到哪一步驟會導致程式當掉，在Jupyter上結果是跑得出來的>"<

**Comment by TJ72** [comment]
5科成績的字串切割那的 index好像怪怪的，再試試看吧～

**Comment by Molly995** [comment]
![13](https://user-images.githubusercontent.com/80046613/110245476-31d92d00-7f5b-11eb-9890-f07b61ec84da.PNG)
![14](https://user-images.githubusercontent.com/80046613/110245480-34d41d80-7f5b-11eb-9b87-7aa6861bb8cb.PNG)
在Jupyter上把每一個值都print出來了，是可以找到值的，還是不懂錯在哪。
請問助教為什麼在Jupyter上跑得出來，但在Judge上跑不出來呢?

**Comment by TJ72** [comment]
因為 Judge系統上的測資是 5科成績中間只用","隔開，所以當`score = "14,15,15,13,11"`，代表 score是一個長度為14的字串；但當妳輸入`score = "14, 15, 15, 13, 11"`時，逗號後面又加了一個空格的話，score的長度就變成18了，所以 string slicing的結果會跟 Judge測資期待的不一樣～

**Comment by Molly995** [comment]
看出來了!原來是這樣子!!
是我檢查時粗心沒有看到，謝謝助教的解答!
