### ISSUE TITLE
[Homework 1] 吉吉當老師

### ISSUE THREAD

**Issue by selina3067** [coding-coworking-club/python-spring-2021#64]
## 提交連結

https://judge.ccclub.io/status/d1f2a572ce0e8d00026596c50f099eee
## 程式碼

```python
import math
a=float(input()) #輸入每個參數a,b,c
b=float(input())
c=float(input())

key=b**2-4*a*c   #如果這個式子大於0會有兩根 /等於0會有重根/小於0會是無解

if key > 0:     #有解的狀況
    x1=(-b+math.sqrt(key))/2*a    #求出第一解x1
    x2=(-b-math.sqrt(key))/2*a    #求出第二解x2
    lista=[round(x1,3),round(x2,3)]   #x1,x2用round()四捨五入到小數點後三位  並置入到lista
    lista[:]=sorted(lista)  #將lista由小排到大
    print(2)  #印出解的數量
    print(lista[0])  #印出比較小的解
    print(lista[1])  #印出比較大的解
elif key == 0:   #有無限多組解的狀況
    print(-1)
elif key< 0:   #無解的狀況
    print(0)
```
 

## 問題描述

已經嘗試過好幾遍了 也試過了judge上面的可能答案
原本猜是不是第一行印出的解的個數(像是2,-1,0) 型式是不是錯誤(像可能要印成str type)
但好像也不是

**Comment by andykuo0956** [comment]
（我不是助教，所以我可能沒辦法解決ㄋ的問題，ㄋ的程式碼看起來很像在line上發問的同學
試試看a=0以及其他係數=0的情況，另外應該不是輸出的問題
此外，以我所知key = 0 的時候應該是唯一解-b/(2*a) （？

**Comment by selina3067** [comment]
> （我不是助教，所以我可能沒辦法解決ㄋ的問題，ㄋ的程式碼看起來很像在line上發問的同學
> 試試看a=0以及其他係數=0的情況，另外應該不是輸出的問題
> 此外，以我所知key = 0 的時候應該是唯一解-b/(2*a) （？

Thanks a lot 那時候太緊張了所以Line 跟Git兩邊都發
現在已經成功解完了 感謝各位!
