### ISSUE TITLE
[General] 4-2：及格分數

### ISSUE THREAD

**Issue by xiu-mei-huang** [coding-coworking-club/python-spring-2021#66]
## 提交連結

https://judge.ccclub.io/problem/180010

## 程式碼

```python
s=input()
if 100>=len(s)>=60:
    print("Pass")
elif 0<=len(s)<60:
    print("Fail")
else:
    print("Error")
```

## 錯誤訊息

Wrong Answer 

## 問題描述

在jupyter上輸入59可以得到Fail，但輸入105依然得到Fail，因此在作業批改系統得到Wrong Answer，但檢查程式碼找不出錯誤的地方。

**Comment by andykuo0956** [comment]
len(s)是s字串的長度喔，應該要是轉成整數
另外程式碼記得縮排喔，不確定是不是貼上來的時候出問題
