### ISSUE TITLE
[Week 2] 停車費

### ISSUE THREAD

**Issue by Lienwuuu** [coding-coworking-club/python-spring-2021#67]
## 提交連結

https://judge.ccclub.io/status/ddd9cf95d626f3189d063a89daca57ea
## 程式碼

```python
start = input()
end = input()
discount = input()

minute = (int(end[0:2])*60 + int(end[3:])) - (int(start[0:2])*60+int(start[3:]))

if minute < 1:
    pay == 0

elif discount =="Y":
    if minute < 30:
        pay == 0
    elif minute >= 30:
        if minute % 30 == 0:
            pay == minute / 30 * 20*0.5
        else:
            pay == (minute//30*20 + 20) *0.5

elif discount == "N":
    if minute < 30:
        pay == 20
    elif minute > 30:
        if minute % 30 == 0:
            pay == minute / 30 * 20 
        else:
            pay == minute//30*20 + 20
    
print(pay)
```

## 問題描述

在jupyter上測試的時候跑不出來
顯示"NameError: name 'pay' is not defined"
但我覺得我有定義pay啊
請問是哪裡出錯了呢?
謝謝!

**Comment by TJ72** [comment]
會顯示 "NameError: name 'pay' is not defined"是因為妳在 assign變數的時候寫成`pay == 0`了！在 assign變數時只需要一個 = 就可以了喔！另外當`discount = "Y"`時，計算出來的 pay會是一個浮點數，會跟 Judge系統上要求的整數答案不太一樣喔～

**Comment by Lienwuuu** [comment]
原來是這樣! 謝謝你的提醒~
我修正等號跟浮點數這兩部分後, 在jupyter可運作了
不過在judge是Runtime Error...

**Comment by Lienwuuu** [comment]
原來是這樣! 謝謝你的提醒~
我修正等號跟浮點數這兩部分後就ｏｋ了！
