### ISSUE TITLE
[General] 5-1：翻箱倒櫃

### ISSUE THREAD

**Issue by GaryChen1140** [coding-coworking-club/python-spring-2021#68]
## 程式碼

```python
lst1=["apple", "pen"]
lst2=["pineapple", "pen"]
s=input()

if str(s)in lst1:
    print("True")
elif str(s)in lst2:
    print("True")
else:
    print("False")
```

我的邏輯是如果s這個東西有在lst1裡那就是true,如果沒有就去檢查有沒有在lst2裡如果有的話也是true,但是如果兩個都沒有的話就是false,但是judge系統說我有錯誤請問是哪裡錯了呢?

**Comment by chi811008** [comment]
哈囉～
可以回去porblem仔細看看題目，題目說
## Input
輸入一共有"三行"
前兩行包含了兩組字串，字串間皆以空格分開，請將其轉換成兩串列 lst1 和 lst2，而第三行則是一個字串 s

你的程式碼只有輸入"一行"

另外，格式要按照：
https://www.notion.so/ccclub/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036
去編輯唷！ 麻煩您了
