### ISSUE TITLE
[General] 字母轉數字

### ISSUE THREAD

**Issue by konichihuahua** [coding-coworking-club/python-spring-2021#69]
## 提交連結

https://judge.ccclub.io/status/865645bddbb4dabeed37d22e79f9d38a
## 程式碼

```python
n=list(input().lower())
for i in range(len(n)):
  n[i]=ord(n[i])-96


for j in n:
  if j==n[-1]:
    print(j)
    break
  print(j,end=",")


```

## 錯誤訊息

wrong answer

## 問題描述

為什麼錯誤呢？

另外想問，像這題要把答案間有空格的輸出，我目前的寫法都是這樣，
有沒有更常用簡潔的寫法呢？

**Comment by TJ72** [comment]
因為最後迴圈在輸出結果的時候，如果 n-list index 0~len(n)-2中有任何一個值跟  n[-1]相同的話，就自動跑到`if j == n[-1]:`的敘述裡面了，所以就不會輸出完整字母對應的整數喔！更簡潔的輸出寫法的話，答案是有的！可以期待這禮拜四的講師課喔！
