### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by chrisjan611** [coding-coworking-club/python-spring-2021#70]
## 提交連結

https://judge.ccclub.io/status/5bef967f11d92e5162b9177c91d7c1ad

## 程式碼

```python
buy=int(input())
exc=int(input())
a=buy//exc
b=buy%exc
a1=a
c=0
while (a1+b)>=exc:
    a1=(a1+b)//exc
    b=(a1+b)%exc
    c+=a1
print(buy+a+c)
```

## 問題描述

exc是兌換門檻，a設為商數，b設為餘數，a1當作a在迴圈內運算的變數（因為最後print的時候要直接用a），每次迴圈都把a1重新令為(a1+b)/exc，而在c的地方加上一次a1。
雖然我直接看著程式進行計算是對的（例如40 6 會得到47），但程式去跑每次出來都會多一或少一（例如40 6會得到48），不知道哪裡出了問題，請助教解答，謝謝。

**Comment by chi811008** [comment]
哈囉！
你while迴圈裡面的b已經是剩下的空瓶數囉！
如果再回到while 迴圈的判斷式
`while (a1+b)>=exc:
`
剩下的空瓶數目又會再被你加上一次換回來的空瓶

另外如果你解決了以上的 bug 卻還有問題的話也可以參考這一篇唷！
#62
