### ISSUE TITLE
[Homework 1] 吉吉印方形

### ISSUE THREAD

**Issue by becky07110711** [coding-coworking-club/python-spring-2021#72]
## 程式碼
```python
stars= int(input())
for s in range(stars):
    if s==0 :
        print("*"*stars)
    if s > 0 and s < stars-1:
        print("*"+" "*(stars-2)+"*")
 
    if s== stars-1 :
        print("*"*stars)
```

## 錯誤訊息
wrong answer

## 問題描述
我的程式碼在jupyter執行 有印出與範例一樣的星星，但在judge顯示: wrong answer。請問老師助教可能的問題出在哪?謝謝!

**Comment by TJ72** [comment]
當 stars = 1時，輸出會與題目要求的不同喔！另外，下次請附上正確的提交連結，細節請參考[GitHub 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)。

**Comment by becky07110711** [comment]
> 當 stars = 1時，輸出會與題目要求的不同喔！另外，下次請附上正確的提交連結，細節請參考[GitHub 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)。

謝謝，已解決!!
