### ISSUE TITLE
[General] 小明幾歲

### ISSUE THREAD

**Issue by CKJK47** [coding-coworking-club/python-spring-2021#73]
## 提交連結

https://judge.ccclub.io/status/6284f54dd103c48dfb042eba6db4f249
## 程式碼

```python
A = int(input())
B = int(input())
s1 = ["I'm", "Little", "Ming,", "I'm", "years", "old." ]
s2 = ["I'm", "Little", "Ming's,", "brother,", "I'm", "years", "old." ]

if int(B) >= 1:
    s1.insert(4, str(A))
    s2.insert(5, str(A + B))
    list_s1 = ' '.join(s1)
    list_s2 = ' '.join(s2)
    print(list_s1)
    print(list_s2)
```

## 錯誤訊息

<img width="1087" alt="截圖 2021-03-08 下午6 24 37" src="https://user-images.githubusercontent.com/79802408/110308871-9e2b5d80-803b-11eb-8edc-8bfd77076293.png">

顯示Wrong Answer

## 問題描述

1. 按照題意讓使用者輸入數字
2. 我把數字以外的文字都先打好變成一個字串
3. 用if為條件式，若有年紀差(B>=1)就符合條件
4. 利用insert把輸入的數字插入到字串正確位置內
5. 再用join的方式轉回字串輸出

問題：我在jupyter notebook上面都可以順利完成範例，提交卻顯示Wrong Answer，不知道哪裡有盲點？謝謝！

**Comment by CKJK47** [comment]
不好意思code部分

if條件式該行筆誤，更正為：
if int(B) >= 1

**Comment by TJ72** [comment]
s2 list裡的 "Ming's"後面多了一個逗號

**Comment by CKJK47** [comment]
我刪除逗號之後仍然出現Wrong Answer，不好意思再麻煩了，謝謝！

**Comment by TJ72** [comment]
建議不要設`if B >= 0:`的條件，這樣會把哥哥和小明同歲的可能排除了。

**Comment by CKJK47** [comment]
解決了，謝謝！
