### ISSUE TITLE
[Homework 1] 吉吉整理書

### ISSUE THREAD

**Issue by yutingchen526** [coding-coworking-club/python-spring-2021#79]
http://localhost:8888/notebooks/Untitled6.ipynb?kernel_name=python3

##程式碼

str1 = input()
list1 = str1.split()
list1.sort()

for i in list1:
    print(i, end=" ")

## 錯誤訊息

輸入為 2 10 35 8 5
結果為 10 2 35 5 8

## 問題描述

解題的想法是先把input的string轉為list，再用sort排序。
然後用for去逐一列出裡面的值，但出來的順序不知道為何沒有規則，然後且不太知道裡面的值是不是int的型態。

**Comment by Din0-3** [comment]
Input 完沒有改過當然都是string 的型態囉

**Comment by chianshianli** [comment]
(非助教，僅供參考
list 的元素如果是 str 的型態，排序出來是按照每個元素第一個數字的大小去排的喔，要轉成 int 型態才會按照數字大小去排。同樣輸入 1 3 13，轉成 int 排完變成 [1, 3, 13]，保持 str 則會排成 ["1", "13", "3"]。

**Comment by alvisyjchen** [comment]
可以試試看在寫程式過程中使用 print 印出變數型態，應該能幫助你解題

**Comment by yutingchen526** [comment]
切開字串後使用list1_int = [int(i) for i in list1]將數列裡的字串改為數值，答案就出來了！！
謝謝大家的提點！！
