### ISSUE TITLE
[General] 1-1：輸出兩次

### ISSUE THREAD

**Issue by penguin1131** [coding-coworking-club/python-spring-2021#8]
## 提交連結

https://judge.ccclub.io/status/baa320cec63faae3948c28a3bd667f67
## 程式碼

```python
a = "pine"
b = "apple"
print(a+b)
print(a+b)
  
a = "Pine"
b = "Apple"
print (a+b,"\n",a+b)
```

## 問題描述

第一種寫法在jupyter notebook撰寫時有順利輸出結果，但在批改系統中卻顯示錯誤。
不確定是否為自身對題目理解有誤，因此想要請問print的部分只能輸出一行嗎？

**Comment by TJ72** [comment]
兩種寫法應該都沒有問題，只是 a和 b是要設定給使用者(or Judge系統)自行輸入的變數，而不是預設的 Sample Input喔！

**Comment by penguin1131** [comment]
喔喔喔！瞭解，原來是這邊出問題。感謝提醒！
