### ISSUE TITLE
[Homework 1] 吉吉整理書

### ISSUE THREAD

**Issue by emilyjenjen** [coding-coworking-club/python-spring-2021#82]
## 提交連結

https://judge.ccclub.io/status/72f2e15077bd54c0e8910714411ae2bf
## 程式碼

```python
a=input()
b=str.split(a)
c=len(b)
list=[]
k=0
for i in range(c):
    if k in b:
        list.append(k)
        i+=1
        k+=1
    else:
        k+=1
print(list)

```

## 問題描述

我的想法是把數字從0開始檢查，只要檢查到b這個使用者輸入的清單中有k此數的話，則將k加入新的list(取名為list)中，可以達到從小排序到大的條件。只要有找到數字，則i+=1，k+=1，沒找到的話就只有k+=1。迴圈range設定在c=len(b)，這樣只要找到c=len(b)個符合數字就break，而這些數字也將依序地加入新的list中。
不過試著在Jupyter上面跑好像跑不出來（都會print[]空白清單），重新看好幾遍程式碼，也找不到卡住的地方，可否麻煩助教指點？

**Comment by andykuo0956** [comment]
（我不是助教，不過希望可以幫到你
1.b=str.split(a)這句語法跟你要的結果可能不一樣，你看到str.split()的意思是String這種資料型態（也就是字串）可以被split，所以你想表示的可能是a.split()
2.沒記錯in語法不是這樣用的
這兩部分ㄋ先改看看，另外建議一步驟就print看看是不是自己想要的，比較好抓bug
加油～

**Comment by chianshianli** [comment]
(非助教，路過提供想法
感覺對 for-loop 的概念有點混淆了，建議可以再複習一下
不過我自己解這題沒用到迴圈，單純是用串列去解(影片12. 串列跟medium第五、六講)
可以去複習串列的內容看看有沒有跟這題題目比較相關的! 加油~
