### ISSUE TITLE
[Homework 1] 吉吉印方形

### ISSUE THREAD

**Issue by emilyjenjen** [coding-coworking-club/python-spring-2021#83]
## 提交連結

https://judge.ccclub.io/status/257053806174915c96163e379c442439
## 程式碼

```python
num=int(input())
print("*"*num)
for i in range(num-2):
    print("*"," "*(num-2),"*",sep="")
    i+=1
print("*"*num)

```

## 問題描述

我的想法是將輸出分為三個部分，第一個部分就是第一行n個星星，直接print("*"*num)。第二個部分就是中空的部分，用for迴圈設定range在num-2(扣掉上下底)，print("*"," "*(num-2),"*",sep="")。第三部分就比照第一部分也是print n個星星。試了很多數字（包含sample）輸出都正確，自己檢視程式碼也覺得邏輯上是正確的，請問為什麼judge系統都是顯示wrong answer呢？是因為只能有一次print function嗎？

**Comment by TJ72** [comment]
Judge系統是可以有一次以上的 print function沒問題的。這裡的問題是當`num = 1`時，輸出結果就與題目期待的不一樣。另外，Python的 for-loop語法`for i in range(num):`的 i在每次執行迴圈時已經會自動 +=1了，不用像 C或其他程式語言需要在迴圈裡面用` i += 1`來控制喔！
