### ISSUE TITLE
[General] 關於List comprehension功能

### ISSUE THREAD

**Issue by CKJK47** [coding-coworking-club/python-spring-2021#86]
## 程式碼

```python
s = input().split()
for x in s:
    int(x)

print(s)
---------------------------
s = input().split()
s = [int(x) for x in s]
print(s)

```

## 問題描述

我想要請問這兩個程式碼的差異
我的理解是list comprehension可以把要跑的回圈濃縮在同一行
我的s輸入為:1 2 3
我想要將List裡面的元素都轉成int
但為什麼輸出時上方的程式碼仍然輸出['1', '2', '3']而非像下方的一樣是[1, 2, 3]
謝謝！

**Comment by TJ72** [comment]
因為你在 for迴圈轉 s-list 元素的時候忘了把轉完的整數重新存回 s-list裡。如果是這樣應該就會一樣了喔～
```python
s = input().split()
for i in range(len(s)):
    s[i] = int(s[i])
```
