### ISSUE TITLE
[General] 記帳本

### ISSUE THREAD

**Issue by ghost** [coding-coworking-club/python-spring-2021#87]
## 提交連結

https://judge.ccclub.io/status/7be2196390f7dcd0505bb77a905e84b5
## 程式碼

```
n_inp=input().split(' ')
n=[int(i) for i in n_inp]
while True:
    inp=input().split(' ')
    if inp[0]=='a':
        n.append(int(inp[1])) #當第一個數為a,加入數字
#         print(n)
    elif inp[0]=='r':
        if int(inp[1]) in n: #如果數字在list裡的話
            n.remove(int(inp[1]))#移除數字
#             print(n)
        else:
            pass
    elif inp[0]=='p':
        if int(inp[1])==-1 and len(n)>=1: #如果數字為-1且長度為1以上
            del n[-1]
        elif len(n)>int(inp[1]) and int(inp[1])!=-1: #如果數字不為-1且長度大於index
            del n[int(inp[1])]
#             print(n)
        else:
            pass
    elif inp[0]=='q':
        if len(n)>abs(int(inp[1])): #考慮到-1以上所以加絕對值 
            print(n[int(inp[1])])
            print(int(sum(n)/len(n)))
        else:
            print('Error')
        break
        


```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/52339710/110656441-ea70cc00-81fa-11eb-9c54-7547ae157095.png)

## 問題描述

我的邏輯是：
1.如果字母為a就用append加在list後面
2.然後移除的部分就是有在list就移除
3.用index刪除的部分就是把是否-1分開討論，因為如果沒有負的話就直接len>index就好，但如果是只有一個數的情況像[1]的len是1，就變成len>=index(-1)就行
4.最後就是長度要大於index絕對值
找了好久都找不到bug，在jupyter notebook都可執行。
最後q後面應該可以接負數吧？還是我最後印出來的格式不對？

**Comment by TJ72** [comment]
計算上好像沒有什麼問題，問題都出在最後輸出"無條件捨去至整數"輸出平均值。建議這題不要用`int(sum(n) / len(n))`，在負數取 floor的時候好像常會出錯，可以試試看`sum(n) // len(n)`或`math.floor()`
