### ISSUE TITLE
[Homework 1] 吉吉整理書

### ISSUE THREAD

**Issue by alonso1331** [coding-coworking-club/python-spring-2021#89]
## 提交連結

https://judge.ccclub.io/status/ab15ffedb7692a9794490008fdc9f7fb

## 程式碼

```python
list = input()
list = sorted(list)
print(list)
```

## 錯誤訊息

Wrong Answer

## 問題描述
我的編碼是以list = [2 10 35 8 5]加上後面list =sorted(list)和print(list)，可以得到2 5 8 10 35為基礎
因為題目說「輸入」所以加了input()指令取代[2 10 35 8 5]
但輸入後顯示[' ', ' ', ' ', ' ', ' ', '0', '1', '2', '3', '5', '5', '8']
請問是哪個步驟出錯呢？

**Comment by TJ72** [comment]
因為`list = input()`輸入完變數 list是一個字串，sorted(list)雖然會輸出串列，但會根據預設的"字典順序"做排序，不會達成期望的"用數字大小作排序"，所以在用 sorted()前應該要先把 list裡面的元素轉換成整數或浮點數(看題目需求)，再丟進去排序喔～
**建議不要使用 list作為變數名稱**

**Comment by alonso1331** [comment]
感謝回覆！
https://judge.ccclub.io/status/bee2948dfde72935bb61f102253d4637

books = int(input())
books = sorted(books)
print(books)

我將第1行增加int指令
雖然會輸出數字，但是沒有辦法排序
請問我還忽略了甚麼呢？

**Comment by TJ72** [comment]
如果直接寫`books = int(input())`，只是將輸入的字串轉成整數型態而已，而且如果像這題輸入的是數個數字以空格作為間隔的話，因為輸入的字串沒辦法轉換成整數，所以 Python就會出現 Runtime Error(Value Error)喔！

所以這題要能成功排序，首先要先能把輸入的每個數字轉成整數之後存進串列中，可以用的方法有 for-loop一個一個存進去串列，或是可以用 list comprehension，兩種方法都會在這星期四的課程中教到喔～

**Comment by alonso1331** [comment]
感謝，我再試看看。

**Comment by alonso1331** [comment]
今天上課已經找到解決方式了，非常感謝您的回覆。
