### ISSUE TITLE
[General] 4-1：密碼強度

### ISSUE THREAD

**Issue by sandyluee** [coding-coworking-club/python-spring-2021#9]
## 提交連結

https://judge.ccclub.io/problem/180009

## 程式碼

```python
s=input()
if len(s)>=int(8):
    print("Success")
else:
    print("fail")
```

## 問題描述

在jupyter notebook上跑時可以跑出想要的結果："Success"和＂Fail＂
但在作業批改系統上則是wrong answer

**Comment by TJ72** [comment]
應該是"Fail"沒有大寫

**Comment by TJ72** [comment]
另外，下次發 GitHub Issues請注意內容的模板：
https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e
