### ISSUE TITLE
[Homework 1] 吉吉當老師

### ISSUE THREAD

**Issue by emilyjenjen** [coding-coworking-club/python-spring-2021#90]
## 提交連結

https://judge.ccclub.io/status/1afc0cc6c63a5889fdb4e5d362295e61
## 程式碼

```python
a=float(input())
b=float(input())
c=float(input())
if a!=0:
    if (b**2-4*a*c)<0:
        print(0)
    elif a==0 and b==0 and c==0:
        print(-1)
    elif(b**2-4*a*c)==0:
        x=-b/(2*a)
        print(2,round(x,3),round(x,3),sep="\n")
    else:
        x1=(-b+(b**2-4*a*c)**(1/2))/2*a
        x2=(-b-(b**2-4*a*c)**(1/2))/2*a
        if x1<x2:
            print(2,round(x1,3),round(x2,3),sep="\n")
        elif x2<x1:
            print(2,round(x2,3),round(x1,3),sep="\n")
else:
    if b!=0 and c!=0:
        x=-c/b
        print(1,round(x,3),sep="\n")
    elif b==0 and c!=0:
        print(0)
    elif b==0 and c==0:
        print(-1)
```

## 問題描述

我的想法是先分成兩個情況：a==0或是a!=0
a!=0的部分先判斷是不是無解或無限多解，再判斷是不是重根。都不是就代表有兩個解，這其中又分成(-b+(b**2-4*a*c)**(1/2))/2*a是比較大的解或是(-b-(b**2-4*a*c)**(1/2))/2*a是比較大的解，分別再去調整print的順序。
解決完a!=0之後就來看a==0的情況（一元一次方程式），分別依據個條件去print相對應的答案。在jupyter上測試sample跟我想的幾個答案都正確，但複製貼上到judge系統上面卻怎麼跑都是wrong answer，也有分別測試重根算一個答案或是兩個答案，都不對，請問是哪裡出了問題呢？

**Comment by chianshianli** [comment]
(非助教)
改了一些我覺得怪怪的地方，但還是WA...不過把我發現的地方跟你分享~

1. 7~8行不需要，因為她是在 if a!=0 之下，程式跟本不會跑到那邊，如果 a==0 他就會跳到最後八行那邊。
2. 重根在題目更新的說明中算一個答案。
3. 沒考慮到 a!=0 and b==0 and c==0 的狀況

不過就算修正這些，還是無法AC，希望你能找到 BUG ~加油!

**Comment by TJ72** [comment]
感謝樓上同學的解答～然後還有一個問題同 #95，計算的時候要小心一點喔～
