### ISSUE TITLE
[Week 2] 停車費

### ISSUE THREAD

**Issue by ann12568** [coding-coworking-club/python-spring-2021#91]
## 提交連結

https://judge.ccclub.io/status/a30e5a9ce8edccfbbcac3d8ae1621c94

## 程式碼

```python
Enter=input()
Exit=input()
ID=input()
t_enter=(int(Enter[0:2])*60)+int(Enter[3:])
t_exit=(int(Exit[0:2])*60)+int(Exit[3:])
if t_exit>t_enter:
    t=t_exit-t_enter
else:
    t=(23*60+59)-t_enter


if ID=="Y":
    print(int((t//30)*10))
elif ID=="N":
    if t//30==0:
        print(int((t//30)*20))
    elif t//30!=0:
        print(int(((t//30)+1)*20))
else:
    print(int(0))

```

## 問題描述

在Jupyter上測試sample皆順利通過，但是judge卻為Wrong Answer，請助教協助解答何處有錯誤需要調整，謝謝！

**Comment by chianshianli** [comment]
(非助教)
沒有全部檢查，但好像少考慮了"3.如果你有台大證件，總停車時間若小於30分鐘，則停車免費"這個條件

**Comment by TJ72** [comment]
感謝上面同學的留言，code中的確少了這個條件。然後"當有台大證件"時，計算停車費條件的討論應該也要跟"沒有台大證件"一樣，不然"不滿30分鐘算為30分鐘(停超過30分鐘)"就沒算在 ID == "Y"的情況下算到了。
另外，因為這題沒有過夜，所以建議第一個 `if t_exit>t_enter`的討論可以省略，不然同分鐘進出的停車時間就會算錯了～

**Comment by ann12568** [comment]
謝謝同學以及助教的回覆，已調整並通過Judge!
