### ISSUE TITLE
[General] 字串加密

### ISSUE THREAD

**Issue by chrisjan611** [coding-coworking-club/python-spring-2021#92]
## 提交連結

https://judge.ccclub.io/status/b95f39a94d5de97e1830fd7465133577

## 程式碼

```python
word=input()
for i in range(len(word)):
    word=word.replace(word[i],(chr(ord(word[i])+1+int(i))))
print(word)
```

## 問題描述

想要用for迴圈依序把字串中每一個字元都改成轉換後的字元，+1再+int(i)可以符合題目要求的規則，實際執行上前一到二個字母卻總是出錯，例如ccClub應該轉換為deFpzh，我輸出是ffFpzh。想請問助教哪裡出錯了，謝謝！

**Comment by TJ72** [comment]
因為在用 `str.replace(s1, s2)`時，會將所有字串內是 s1的地方改成 s2，不會是你在 for-loop中期待的只改到字串指定 index的字元。像是 Sample Input 1："word = abc"，第一次迴圈會改成"word = bbc"，第二次迴圈 word中是 "b"的地方就全被改成 "d"了。
