### ISSUE TITLE
[Homework 1] 吉吉當老師

### ISSUE THREAD

**Issue by LMY0324** [coding-coworking-club/python-spring-2021#96]
## 提交連結

https://judge.ccclub.io/status/bb92dcf5203f1201af3bb6f8b1a48a38

## 程式碼

```python
a=int(input())
b=int(input())
c=int(input())
if a==0:
    if b==0 and c==0:
        print(-1)
    elif b==0:
        print(0)
    elif c==0:
        print(1)
        print(0)
    else:
        print(1)
        anw=(-b)/c
        print(round(anw,3))
elif b==0 and c==0:
    print(1)
    print(0)              
elif(b**2-4*a*c)<0: 
    print(0)
elif (b**2-4*a*c)==0:
    print(1)
    anw=(-b)/(2*a)
    print(round(anw,3))

elif (b**2-4*a*c)>0:
    print(2)
    anw1=((-b)-((b**2-4*a*c)**0.5))/(2*a)
    anw2=((-b)+((b**2-4*a*c)**0.5))/(2*a)
    print(round(anw1,3))
    print(round(anw2,3))
```

## 問題描述

我已經把judge上面的資料都輸進去跑過都沒有問題，但就是無法AC，不知道是不是邏輯有錯誤，希望可以幫忙看一下。

**Comment by TJ72** [comment]
`if a == 0:`裡面的 else的 anw剛好打反了

**Comment by LMY0324** [comment]
> ## 提交連結
> https://judge.ccclub.io/status/bb92dcf5203f1201af3bb6f8b1a48a38
> ## 程式碼
> a=int(input())
> b=int(input())
> c=int(input())
> if a==0:
> if b==0 and c==0:
> print(-1)
> elif b==0:
> print(0)
> elif c==0:
> print(1)
> print(0)
> else:
> print(1)
> anw=(-b)/c
> print(round(anw,3))
> elif b==0 and c==0:
> print(1)
> print(0)
> elif(b**2-4_a_c)<0: print(0) elif (b**2-4_a_c)==0:
> print(1)
> anw=(-b)/(2*a)
> print(round(anw,3))
> 
> elif (b**2-4_a_c)>0: print(2) anw1=((-b)-((b**2-4_a_c)**0.5))/(2*a) anw2=((-b)+((b**2-4_a_c)**0.5))/(2*a)
> print(round(anw1,3))
> print(round(anw2,3))
> 
> ## 錯誤訊息
> ## 問題描述
> 我已經把judge上面的資料都輸進去跑過都沒有問題，但就是無法AC，不知道是不是邏輯有錯誤，希望可以幫忙看一下。
