### ISSUE TITLE
[Homework 1] 小葉喝可樂

### ISSUE THREAD

**Issue by Lucy-Ting** [coding-coworking-club/python-spring-2021#98]
## 提交連結

https://judge.ccclub.io/status/f9313e9da52e930536fef16d27479932

## 程式碼

```python
a=int(input())
b=int(input())
first=a//b+a%b
exchange=0
i=1
while first>=b:
    exchange+=first//b
    first=first//b+a%b
    i+=1
print(a+a//b+exchange)

```

## 問題描述

將題幹給的數字帶進去後能得到正確答案，但批改系統表示WA，後來多帶幾組數字進去後，發現有時可跑出正確數字，有時則顯示不出答案，但不確定問題是哪行設定出錯。

**Comment by TJ72** [comment]
請修正程式碼與提交連結，細節請參考[GitHub 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)

**Comment by Lucy-Ting** [comment]
已修改 !

**Comment by TJ72** [comment]
我覺得 while-loop迴圈裡面 first的算式好像怪怪的，另外感覺好像不用變數 i耶，感覺 i在這邊沒有起到什麼作用（雖然不會影響到答案
