### ISSUE TITLE
[General] problem_Udemy_13迴圈for_

### ISSUE THREAD

**Issue by Janeisstarter** [coding-coworking-club/python-spring-2021#99]
## 程式碼

```python
score = [input(),input(),input(),input(),input()]
n = 0
total = 0
for i in range(len(score)):
    total += score[i]
print(total/n)

```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/80194696/110735394-b500c880-8264-11eb-8c47-a11634c7f85d.png)

## 問題描述

根據Udemy的影片將範例輸入   Jupyter Notebook執行但無法執算出平均分數，想請問在程式碼編寫還需要新增什麼條件呢?
謝謝!

**Comment by TJ72** [comment]
`input()`的內容是字串的型態喔！所以如果你想用運算子做數字運算的話，要先將輸入的內容轉換成整數才可以喔～像是：`score = [int(input()), int(input()), int(input()), int(input()), int(input())]`

**Comment by Janeisstarter** [comment]
了解! 謝謝
